# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_outposts", "0022_outpostprovider_alter_outpost_providers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outpost",
            name="type",
            field=models.TextField(
                choices=[
                    ("proxy", "Proxy"),
                    ("ldap", "Ldap"),
                    ("radius", "Radius"),
                    ("rac", "Rac"),
                    ("kerberos", "Kerberos"),
                ],
                default="proxy",
            ),
        ),
    ]
