# Generated by Django

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import authentik.lib.utils.time
import authentik.providers.kerberos.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentik_core", "0064_user_authentik_c_usernam_2f0e4b_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="KerberosProvider",
            fields=[
                (
                    "provider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.provider",
                    ),
                ),
                ("realm_name", models.CharField(max_length=255, unique=True)),
                (
                    "maximum_ticket_lifetime",
                    models.TextField(
                        default="hours=10",
                        validators=[authentik.lib.utils.time.timedelta_string_validator],
                    ),
                ),
                (
                    "maximum_ticket_renew_lifetime",
                    models.TextField(
                        default="days=7",
                        validators=[authentik.lib.utils.time.timedelta_string_validator],
                    ),
                ),
                (
                    "allowed_enctypes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (17, "aes128-cts-hmac-sha1-96"),
                                (18, "aes256-cts-hmac-sha1-96"),
                                (19, "aes128-cts-hmac-sha256-128"),
                                (20, "aes256-cts-hmac-sha384-192"),
                            ]
                        ),
                        default=authentik.providers.kerberos.models.default_enctypes,
                        size=None,
                    ),
                ),
                (
                    "master_key",
                    models.TextField(
                        default=authentik.providers.kerberos.models.generate_master_key
                    ),
                ),
            ],
            options={
                "verbose_name": "Kerberos Provider",
                "verbose_name_plural": "Kerberos Providers",
            },
            bases=("authentik_core.provider", models.Model),
        ),
        migrations.CreateModel(
            name="KerberosServicePrincipal",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "spn",
                    models.CharField(max_length=1024),
                ),
                ("kvno", models.PositiveIntegerField(default=1)),
                ("keys", models.JSONField(default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_providers_kerberos.kerberosprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kerberos Service Principal",
                "verbose_name_plural": "Kerberos Service Principals",
            },
        ),
        migrations.CreateModel(
            name="KerberosUserKeys",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kvno", models.PositiveIntegerField(default=1)),
                ("keys", models.JSONField(default=dict)),
                ("salt", models.CharField(max_length=1024)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_providers_kerberos.kerberosprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kerberos User Keys",
                "verbose_name_plural": "Kerberos User Keys",
            },
        ),
        migrations.AddConstraint(
            model_name="kerberosserviceprincipal",
            constraint=models.UniqueConstraint(
                fields=("provider", "spn"),
                name="kerberos_provider_spn_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="kerberosuserkeys",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"),
                name="kerberos_user_provider_unique",
            ),
        ),
    ]
