# Generated by Django 5.2.17 on 2026-08-27 14:37

import authentik.lib.utils.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_kerberos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kerberosprovider",
            name="default_domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="default_ticket_lifetime",
            field=models.TextField(
                default="hours=10", validators=[authentik.lib.utils.time.timedelta_string_validator]
            ),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="default_ticket_renew_lifetime",
            field=models.TextField(
                default="days=7", validators=[authentik.lib.utils.time.timedelta_string_validator]
            ),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="forwardable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="principal_username_attribute",
            field=models.CharField(
                choices=[("username", "Username"), ("email", "Email"), ("upn", "UPN")],
                default="username",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="proxiable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="renewable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="require_preauthentication",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="tcp_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="udp_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
