# Generated by Django 5.2.17 on 2026-08-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_crypto", "0006_certificatekeypair_cert_expiry_and_more"),
        ("authentik_providers_kerberos", "0002_kerberosprovider_default_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kerberosprovider",
            name="pkinit_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="Certificate/key pair the KDC uses to sign PKINIT replies. Requires a private key.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authentik_crypto.certificatekeypair",
            ),
        ),
        migrations.AddField(
            model_name="kerberosprovider",
            name="pkinit_client_ca",
            field=models.ForeignKey(
                blank=True,
                help_text="CA certificate used to validate PKINIT client certificates.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authentik_crypto.certificatekeypair",
            ),
        ),
    ]
