# Generated by Django 5.2.17 on 2026-08-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_providers_kerberos', '0004_kerberosprovider_kpasswd_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerberosserviceprincipal',
            name='allowed_delegation_targets',
            field=models.JSONField(blank=True, default=list, help_text='Service principals this service principal may use for constrained delegation.'),
        ),
        migrations.AddField(
            model_name='kerberosserviceprincipal',
            name='ok_to_auth_as_delegate',
            field=models.BooleanField(default=False, help_text='Allow this service principal to authenticate as a user for delegation.'),
        ),
    ]
