# Generated by Django 5.2.17 on 2026-08-28

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_policy_binding_models(apps, schema_editor):
    """Create policy-binding parents for existing service principals."""
    policy_binding_model = apps.get_model("authentik_policies", "PolicyBindingModel")
    service_principal = apps.get_model("authentik_providers_kerberos", "KerberosServicePrincipal")
    for principal in service_principal.objects.all().iterator():
        pbm_uuid = uuid.uuid4()
        policy_binding_model.objects.create(pbm_uuid=pbm_uuid, policy_engine_mode="any")
        service_principal.objects.filter(pk=principal.pk).update(policybindingmodel_ptr_id=pbm_uuid)


def delete_policy_binding_models(apps, schema_editor):
    """Remove policy-binding parents created for service principals."""
    policy_binding_model = apps.get_model("authentik_policies", "PolicyBindingModel")
    service_principal = apps.get_model("authentik_providers_kerberos", "KerberosServicePrincipal")
    parent_ids = service_principal.objects.values_list("policybindingmodel_ptr_id", flat=True)
    policy_binding_model.objects.filter(pbm_uuid__in=parent_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_policies", "0012_alter_policybinding_managers_policybinding_expires_and_more"),
        (
            "authentik_providers_kerberos",
            "0005_kerberosserviceprincipal_allowed_delegation_targets_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kerberosserviceprincipal",
            name="policybindingmodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="authentik_policies.policybindingmodel",
            ),
        ),
        migrations.RunPython(create_policy_binding_models, delete_policy_binding_models),
        migrations.AlterField(
            model_name="kerberosserviceprincipal",
            name="policybindingmodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="authentik_policies.policybindingmodel",
            ),
        ),
    ]
