# Generated by Django 5.2.17 on 2026-08-28 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_kerberos", "0006_kerberosserviceprincipal_policybinding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kerberosserviceprincipal",
            name="service_account",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text=(
                    "Optional authentik user (typically a service account) whose policies are "
                    "evaluated when this principal acts as a Kerberos client."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
