# Generated by Django 5.2.17 on 2026-08-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_crypto', '0006_certificatekeypair_cert_expiry_and_more'),
        ('authentik_providers_kerberos', '0007_kerberosserviceprincipal_service_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerberosprovider',
            name='anonymous_pkinit_enabled',
            field=models.BooleanField(default=False, help_text='Allow anonymous PKINIT requests.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='kkdcp_certificate',
            field=models.ForeignKey(blank=True, help_text='Certificate/key pair the KDC Proxy listener uses for TLS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authentik_crypto.certificatekeypair'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='kkdcp_enabled',
            field=models.BooleanField(default=False, help_text='Enable KDC Proxy over HTTPS (MS-KKDCP).'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='pkinit_require_freshness',
            field=models.BooleanField(default=False, help_text='Require RFC 8070 freshness tokens on PKINIT requests.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='spake_enabled',
            field=models.BooleanField(default=False, help_text='Advertise PA-SPAKE preauthentication (RFC 9588).'),
        ),
    ]
