# Generated by Django 5.2.17 on 2026-08-30 14:31

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_providers_kerberos', '0011_kerberosprovider_otp_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KerberosRealmTrust',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_realm', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('capaths', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Intermediate realms for transited-path checking.', size=None)),
                ('outgoing_kvno', models.PositiveIntegerField(default=1)),
                ('outgoing_keys', models.JSONField(default=dict)),
                ('incoming_kvno', models.PositiveIntegerField(default=1)),
                ('incoming_keys', models.JSONField(default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realm_trusts', to='authentik_providers_kerberos.kerberosprovider')),
            ],
            options={
                'verbose_name': 'Kerberos Realm Trust',
                'verbose_name_plural': 'Kerberos Realm Trusts',
                'constraints': [models.UniqueConstraint(fields=('provider', 'remote_realm'), name='kerberos_provider_remote_realm_unique')],
            },
        ),
    ]
