# Generated by Django 5.2.17 on 2026-08-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_providers_kerberos', '0013_kerberosserviceprincipal_ticket_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerberosprovider',
            name='kprop_client_spn',
            field=models.TextField(blank=True, help_text='Service principal used to authenticate kprop pushes.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='kprop_enabled',
            field=models.BooleanField(default=False, help_text='Push full MIT Kerberos database dumps to replica KDCs.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='kprop_interval',
            field=models.PositiveIntegerField(default=300, help_text='Interval in seconds between full kprop pushes.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='kprop_master_password',
            field=models.TextField(blank=True, help_text='MIT database master password used to encrypt full kprop dumps.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='kprop_targets',
            field=models.JSONField(blank=True, default=list, help_text='Replica targets in host[:port] form; the default kprop port is 754.'),
        ),
    ]
