# Generated by Django 5.2.17 on 2026-09-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_providers_kerberos', '0016_kerberosprovider_kadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerberosprovider',
            name='max_datagram_reply_size',
            field=models.PositiveIntegerField(default=0, help_text='Maximum UDP reply size in bytes; 0 uses the built-in default of 65536 bytes.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='max_tcp_connections',
            field=models.PositiveIntegerField(default=0, help_text='Maximum concurrent KDC TCP connections; 0 uses the built-in default of 45.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='max_udp_workers',
            field=models.PositiveIntegerField(default=0, help_text='Maximum concurrent UDP request handlers; 0 uses the built-in default of 1024.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='tcp_idle_timeout',
            field=models.PositiveIntegerField(default=0, help_text='KDC TCP idle timeout in seconds; 0 uses the built-in default of 60 seconds.'),
        ),
    ]
