# Generated by Django 5.2.17 on 2026-09-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_providers_kerberos', '0017_kerberosprovider_max_datagram_reply_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerberosprovider',
            name='iprop_allowed_replicas',
            field=models.JSONField(blank=True, default=list, help_text='Replica principals authorized to use incremental propagation.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='iprop_enabled',
            field=models.BooleanField(default=False, help_text='Serve MIT incremental propagation requests.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='iprop_spn',
            field=models.TextField(blank=True, default='', help_text='Kiprop service principal used by incremental propagation replicas.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='iprop_ulog_size',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum number of incremental propagation updates to retain.'),
        ),
        migrations.AddField(
            model_name='kerberosprovider',
            name='trace_enabled',
            field=models.BooleanField(default=False, help_text='Emit KRB5_TRACE-style KDC protocol messages to the outpost log.'),
        ),
    ]
