/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosServicePrincipalOutpost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosServicePrincipalOutpost{}

// KerberosServicePrincipalOutpost Service principal data consumed by the KDC outpost.
type KerberosServicePrincipalOutpost struct {
	Spn                      string                 `json:"spn"`
	Kvno                     int32                  `json:"kvno"`
	Keys                     map[string]interface{} `json:"keys"`
	OkToAuthAsDelegate       bool                   `json:"ok_to_auth_as_delegate"`
	AllowedDelegationTargets []string               `json:"allowed_delegation_targets"`
	RequiredAuthIndicators   []string               `json:"required_auth_indicators"`
	TicketFlags              []string               `json:"ticket_flags"`
	AdditionalProperties     map[string]interface{}
}

type _KerberosServicePrincipalOutpost KerberosServicePrincipalOutpost

// NewKerberosServicePrincipalOutpost instantiates a new KerberosServicePrincipalOutpost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosServicePrincipalOutpost(spn string, kvno int32, keys map[string]interface{}, okToAuthAsDelegate bool, allowedDelegationTargets []string, requiredAuthIndicators []string, ticketFlags []string) *KerberosServicePrincipalOutpost {
	this := KerberosServicePrincipalOutpost{}
	this.Spn = spn
	this.Kvno = kvno
	this.Keys = keys
	this.OkToAuthAsDelegate = okToAuthAsDelegate
	this.AllowedDelegationTargets = allowedDelegationTargets
	this.RequiredAuthIndicators = requiredAuthIndicators
	this.TicketFlags = ticketFlags
	return &this
}

// NewKerberosServicePrincipalOutpostWithDefaults instantiates a new KerberosServicePrincipalOutpost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosServicePrincipalOutpostWithDefaults() *KerberosServicePrincipalOutpost {
	this := KerberosServicePrincipalOutpost{}
	return &this
}

// GetSpn returns the Spn field value
func (o *KerberosServicePrincipalOutpost) GetSpn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Spn
}

// GetSpnOk returns a tuple with the Spn field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalOutpost) GetSpnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spn, true
}

// SetSpn sets field value
func (o *KerberosServicePrincipalOutpost) SetSpn(v string) {
	o.Spn = v
}

// GetKvno returns the Kvno field value
func (o *KerberosServicePrincipalOutpost) GetKvno() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Kvno
}

// GetKvnoOk returns a tuple with the Kvno field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalOutpost) GetKvnoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kvno, true
}

// SetKvno sets field value
func (o *KerberosServicePrincipalOutpost) SetKvno(v int32) {
	o.Kvno = v
}

// GetKeys returns the Keys field value
func (o *KerberosServicePrincipalOutpost) GetKeys() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalOutpost) GetKeysOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *KerberosServicePrincipalOutpost) SetKeys(v map[string]interface{}) {
	o.Keys = v
}

// GetOkToAuthAsDelegate returns the OkToAuthAsDelegate field value
func (o *KerberosServicePrincipalOutpost) GetOkToAuthAsDelegate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OkToAuthAsDelegate
}

// GetOkToAuthAsDelegateOk returns a tuple with the OkToAuthAsDelegate field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalOutpost) GetOkToAuthAsDelegateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OkToAuthAsDelegate, true
}

// SetOkToAuthAsDelegate sets field value
func (o *KerberosServicePrincipalOutpost) SetOkToAuthAsDelegate(v bool) {
	o.OkToAuthAsDelegate = v
}

// GetAllowedDelegationTargets returns the AllowedDelegationTargets field value
func (o *KerberosServicePrincipalOutpost) GetAllowedDelegationTargets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedDelegationTargets
}

// GetAllowedDelegationTargetsOk returns a tuple with the AllowedDelegationTargets field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalOutpost) GetAllowedDelegationTargetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedDelegationTargets, true
}

// SetAllowedDelegationTargets sets field value
func (o *KerberosServicePrincipalOutpost) SetAllowedDelegationTargets(v []string) {
	o.AllowedDelegationTargets = v
}

// GetRequiredAuthIndicators returns the RequiredAuthIndicators field value
func (o *KerberosServicePrincipalOutpost) GetRequiredAuthIndicators() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RequiredAuthIndicators
}

// GetRequiredAuthIndicatorsOk returns a tuple with the RequiredAuthIndicators field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalOutpost) GetRequiredAuthIndicatorsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredAuthIndicators, true
}

// SetRequiredAuthIndicators sets field value
func (o *KerberosServicePrincipalOutpost) SetRequiredAuthIndicators(v []string) {
	o.RequiredAuthIndicators = v
}

// GetTicketFlags returns the TicketFlags field value
func (o *KerberosServicePrincipalOutpost) GetTicketFlags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TicketFlags
}

// GetTicketFlagsOk returns a tuple with the TicketFlags field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalOutpost) GetTicketFlagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TicketFlags, true
}

// SetTicketFlags sets field value
func (o *KerberosServicePrincipalOutpost) SetTicketFlags(v []string) {
	o.TicketFlags = v
}

func (o KerberosServicePrincipalOutpost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosServicePrincipalOutpost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spn"] = o.Spn
	toSerialize["kvno"] = o.Kvno
	toSerialize["keys"] = o.Keys
	toSerialize["ok_to_auth_as_delegate"] = o.OkToAuthAsDelegate
	toSerialize["allowed_delegation_targets"] = o.AllowedDelegationTargets
	toSerialize["required_auth_indicators"] = o.RequiredAuthIndicators
	toSerialize["ticket_flags"] = o.TicketFlags

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosServicePrincipalOutpost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spn",
		"kvno",
		"keys",
		"ok_to_auth_as_delegate",
		"allowed_delegation_targets",
		"required_auth_indicators",
		"ticket_flags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosServicePrincipalOutpost := _KerberosServicePrincipalOutpost{}

	err = json.Unmarshal(data, &varKerberosServicePrincipalOutpost)

	if err != nil {
		return err
	}

	*o = KerberosServicePrincipalOutpost(varKerberosServicePrincipalOutpost)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "spn")
		delete(additionalProperties, "kvno")
		delete(additionalProperties, "keys")
		delete(additionalProperties, "ok_to_auth_as_delegate")
		delete(additionalProperties, "allowed_delegation_targets")
		delete(additionalProperties, "required_auth_indicators")
		delete(additionalProperties, "ticket_flags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosServicePrincipalOutpost struct {
	value *KerberosServicePrincipalOutpost
	isSet bool
}

func (v NullableKerberosServicePrincipalOutpost) Get() *KerberosServicePrincipalOutpost {
	return v.value
}

func (v *NullableKerberosServicePrincipalOutpost) Set(val *KerberosServicePrincipalOutpost) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosServicePrincipalOutpost) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosServicePrincipalOutpost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosServicePrincipalOutpost(val *KerberosServicePrincipalOutpost) *NullableKerberosServicePrincipalOutpost {
	return &NullableKerberosServicePrincipalOutpost{value: val, isSet: true}
}

func (v NullableKerberosServicePrincipalOutpost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosServicePrincipalOutpost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
