/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosServicePrincipalUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosServicePrincipalUpdateRequest{}

// KerberosServicePrincipalUpdateRequest Service principal ticket flag update request for the kadm5 outpost.
type KerberosServicePrincipalUpdateRequest struct {
	Spn                  string            `json:"spn"`
	TicketFlags          []TicketFlagsEnum `json:"ticket_flags"`
	AdditionalProperties map[string]interface{}
}

type _KerberosServicePrincipalUpdateRequest KerberosServicePrincipalUpdateRequest

// NewKerberosServicePrincipalUpdateRequest instantiates a new KerberosServicePrincipalUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosServicePrincipalUpdateRequest(spn string, ticketFlags []TicketFlagsEnum) *KerberosServicePrincipalUpdateRequest {
	this := KerberosServicePrincipalUpdateRequest{}
	this.Spn = spn
	this.TicketFlags = ticketFlags
	return &this
}

// NewKerberosServicePrincipalUpdateRequestWithDefaults instantiates a new KerberosServicePrincipalUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosServicePrincipalUpdateRequestWithDefaults() *KerberosServicePrincipalUpdateRequest {
	this := KerberosServicePrincipalUpdateRequest{}
	return &this
}

// GetSpn returns the Spn field value
func (o *KerberosServicePrincipalUpdateRequest) GetSpn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Spn
}

// GetSpnOk returns a tuple with the Spn field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalUpdateRequest) GetSpnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spn, true
}

// SetSpn sets field value
func (o *KerberosServicePrincipalUpdateRequest) SetSpn(v string) {
	o.Spn = v
}

// GetTicketFlags returns the TicketFlags field value
func (o *KerberosServicePrincipalUpdateRequest) GetTicketFlags() []TicketFlagsEnum {
	if o == nil {
		var ret []TicketFlagsEnum
		return ret
	}

	return o.TicketFlags
}

// GetTicketFlagsOk returns a tuple with the TicketFlags field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalUpdateRequest) GetTicketFlagsOk() ([]TicketFlagsEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.TicketFlags, true
}

// SetTicketFlags sets field value
func (o *KerberosServicePrincipalUpdateRequest) SetTicketFlags(v []TicketFlagsEnum) {
	o.TicketFlags = v
}

func (o KerberosServicePrincipalUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosServicePrincipalUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spn"] = o.Spn
	toSerialize["ticket_flags"] = o.TicketFlags

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosServicePrincipalUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spn",
		"ticket_flags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosServicePrincipalUpdateRequest := _KerberosServicePrincipalUpdateRequest{}

	err = json.Unmarshal(data, &varKerberosServicePrincipalUpdateRequest)

	if err != nil {
		return err
	}

	*o = KerberosServicePrincipalUpdateRequest(varKerberosServicePrincipalUpdateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "spn")
		delete(additionalProperties, "ticket_flags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosServicePrincipalUpdateRequest struct {
	value *KerberosServicePrincipalUpdateRequest
	isSet bool
}

func (v NullableKerberosServicePrincipalUpdateRequest) Get() *KerberosServicePrincipalUpdateRequest {
	return v.value
}

func (v *NullableKerberosServicePrincipalUpdateRequest) Set(val *KerberosServicePrincipalUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosServicePrincipalUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosServicePrincipalUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosServicePrincipalUpdateRequest(val *KerberosServicePrincipalUpdateRequest) *NullableKerberosServicePrincipalUpdateRequest {
	return &NullableKerberosServicePrincipalUpdateRequest{value: val, isSet: true}
}

func (v NullableKerberosServicePrincipalUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosServicePrincipalUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
