/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosAuditEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosAuditEventRequest{}

// KerberosAuditEventRequest KDC audit event data submitted by the Kerberos outpost.
type KerberosAuditEventRequest struct {
	Event                EventEnum `json:"event"`
	Success              bool      `json:"success"`
	Client               string    `json:"client"`
	Service              string    `json:"service"`
	Status               string    `json:"status"`
	PreauthType          string    `json:"preauth_type"`
	RemoteAddr           string    `json:"remote_addr"`
	S4u2selfUser         string    `json:"s4u2self_user"`
	AuthIndicators       []string  `json:"auth_indicators"`
	ErrorCode            int32     `json:"error_code"`
	RequestId            string    `json:"request_id"`
	TicketId             string    `json:"ticket_id"`
	AdditionalProperties map[string]interface{}
}

type _KerberosAuditEventRequest KerberosAuditEventRequest

// NewKerberosAuditEventRequest instantiates a new KerberosAuditEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosAuditEventRequest(event EventEnum, success bool, client string, service string, status string, preauthType string, remoteAddr string, s4u2selfUser string, authIndicators []string, errorCode int32, requestId string, ticketId string) *KerberosAuditEventRequest {
	this := KerberosAuditEventRequest{}
	this.Event = event
	this.Success = success
	this.Client = client
	this.Service = service
	this.Status = status
	this.PreauthType = preauthType
	this.RemoteAddr = remoteAddr
	this.S4u2selfUser = s4u2selfUser
	this.AuthIndicators = authIndicators
	this.ErrorCode = errorCode
	this.RequestId = requestId
	this.TicketId = ticketId
	return &this
}

// NewKerberosAuditEventRequestWithDefaults instantiates a new KerberosAuditEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosAuditEventRequestWithDefaults() *KerberosAuditEventRequest {
	this := KerberosAuditEventRequest{}
	return &this
}

// GetEvent returns the Event field value
func (o *KerberosAuditEventRequest) GetEvent() EventEnum {
	if o == nil {
		var ret EventEnum
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetEventOk() (*EventEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *KerberosAuditEventRequest) SetEvent(v EventEnum) {
	o.Event = v
}

// GetSuccess returns the Success field value
func (o *KerberosAuditEventRequest) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *KerberosAuditEventRequest) SetSuccess(v bool) {
	o.Success = v
}

// GetClient returns the Client field value
func (o *KerberosAuditEventRequest) GetClient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Client
}

// GetClientOk returns a tuple with the Client field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Client, true
}

// SetClient sets field value
func (o *KerberosAuditEventRequest) SetClient(v string) {
	o.Client = v
}

// GetService returns the Service field value
func (o *KerberosAuditEventRequest) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *KerberosAuditEventRequest) SetService(v string) {
	o.Service = v
}

// GetStatus returns the Status field value
func (o *KerberosAuditEventRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *KerberosAuditEventRequest) SetStatus(v string) {
	o.Status = v
}

// GetPreauthType returns the PreauthType field value
func (o *KerberosAuditEventRequest) GetPreauthType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreauthType
}

// GetPreauthTypeOk returns a tuple with the PreauthType field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetPreauthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreauthType, true
}

// SetPreauthType sets field value
func (o *KerberosAuditEventRequest) SetPreauthType(v string) {
	o.PreauthType = v
}

// GetRemoteAddr returns the RemoteAddr field value
func (o *KerberosAuditEventRequest) GetRemoteAddr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteAddr
}

// GetRemoteAddrOk returns a tuple with the RemoteAddr field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetRemoteAddrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteAddr, true
}

// SetRemoteAddr sets field value
func (o *KerberosAuditEventRequest) SetRemoteAddr(v string) {
	o.RemoteAddr = v
}

// GetS4u2selfUser returns the S4u2selfUser field value
func (o *KerberosAuditEventRequest) GetS4u2selfUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.S4u2selfUser
}

// GetS4u2selfUserOk returns a tuple with the S4u2selfUser field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetS4u2selfUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.S4u2selfUser, true
}

// SetS4u2selfUser sets field value
func (o *KerberosAuditEventRequest) SetS4u2selfUser(v string) {
	o.S4u2selfUser = v
}

// GetAuthIndicators returns the AuthIndicators field value
func (o *KerberosAuditEventRequest) GetAuthIndicators() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AuthIndicators
}

// GetAuthIndicatorsOk returns a tuple with the AuthIndicators field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetAuthIndicatorsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthIndicators, true
}

// SetAuthIndicators sets field value
func (o *KerberosAuditEventRequest) SetAuthIndicators(v []string) {
	o.AuthIndicators = v
}

// GetErrorCode returns the ErrorCode field value
func (o *KerberosAuditEventRequest) GetErrorCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetErrorCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorCode, true
}

// SetErrorCode sets field value
func (o *KerberosAuditEventRequest) SetErrorCode(v int32) {
	o.ErrorCode = v
}

// GetRequestId returns the RequestId field value
func (o *KerberosAuditEventRequest) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *KerberosAuditEventRequest) SetRequestId(v string) {
	o.RequestId = v
}

// GetTicketId returns the TicketId field value
func (o *KerberosAuditEventRequest) GetTicketId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TicketId
}

// GetTicketIdOk returns a tuple with the TicketId field value
// and a boolean to check if the value has been set.
func (o *KerberosAuditEventRequest) GetTicketIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TicketId, true
}

// SetTicketId sets field value
func (o *KerberosAuditEventRequest) SetTicketId(v string) {
	o.TicketId = v
}

func (o KerberosAuditEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosAuditEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["success"] = o.Success
	toSerialize["client"] = o.Client
	toSerialize["service"] = o.Service
	toSerialize["status"] = o.Status
	toSerialize["preauth_type"] = o.PreauthType
	toSerialize["remote_addr"] = o.RemoteAddr
	toSerialize["s4u2self_user"] = o.S4u2selfUser
	toSerialize["auth_indicators"] = o.AuthIndicators
	toSerialize["error_code"] = o.ErrorCode
	toSerialize["request_id"] = o.RequestId
	toSerialize["ticket_id"] = o.TicketId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosAuditEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"success",
		"client",
		"service",
		"status",
		"preauth_type",
		"remote_addr",
		"s4u2self_user",
		"auth_indicators",
		"error_code",
		"request_id",
		"ticket_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosAuditEventRequest := _KerberosAuditEventRequest{}

	err = json.Unmarshal(data, &varKerberosAuditEventRequest)

	if err != nil {
		return err
	}

	*o = KerberosAuditEventRequest(varKerberosAuditEventRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "success")
		delete(additionalProperties, "client")
		delete(additionalProperties, "service")
		delete(additionalProperties, "status")
		delete(additionalProperties, "preauth_type")
		delete(additionalProperties, "remote_addr")
		delete(additionalProperties, "s4u2self_user")
		delete(additionalProperties, "auth_indicators")
		delete(additionalProperties, "error_code")
		delete(additionalProperties, "request_id")
		delete(additionalProperties, "ticket_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosAuditEventRequest struct {
	value *KerberosAuditEventRequest
	isSet bool
}

func (v NullableKerberosAuditEventRequest) Get() *KerberosAuditEventRequest {
	return v.value
}

func (v *NullableKerberosAuditEventRequest) Set(val *KerberosAuditEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosAuditEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosAuditEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosAuditEventRequest(val *KerberosAuditEventRequest) *NullableKerberosAuditEventRequest {
	return &NullableKerberosAuditEventRequest{value: val, isSet: true}
}

func (v NullableKerberosAuditEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosAuditEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
