/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// PrincipalUsernameAttributeEnum the model 'PrincipalUsernameAttributeEnum'
type PrincipalUsernameAttributeEnum string

// List of PrincipalUsernameAttributeEnum
const (
	PRINCIPALUSERNAMEATTRIBUTEENUM_USERNAME PrincipalUsernameAttributeEnum = "username"
	PRINCIPALUSERNAMEATTRIBUTEENUM_EMAIL    PrincipalUsernameAttributeEnum = "email"
	PRINCIPALUSERNAMEATTRIBUTEENUM_UPN      PrincipalUsernameAttributeEnum = "upn"
)

// All allowed values of PrincipalUsernameAttributeEnum enum
var AllowedPrincipalUsernameAttributeEnumEnumValues = []PrincipalUsernameAttributeEnum{
	"username",
	"email",
	"upn",
}

func (v *PrincipalUsernameAttributeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PrincipalUsernameAttributeEnum(value)
	for _, existing := range AllowedPrincipalUsernameAttributeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PrincipalUsernameAttributeEnum", value)
}

// NewPrincipalUsernameAttributeEnumFromValue returns a pointer to a valid PrincipalUsernameAttributeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPrincipalUsernameAttributeEnumFromValue(v string) (*PrincipalUsernameAttributeEnum, error) {
	ev := PrincipalUsernameAttributeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PrincipalUsernameAttributeEnum: valid values are %v", v, AllowedPrincipalUsernameAttributeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PrincipalUsernameAttributeEnum) IsValid() bool {
	for _, existing := range AllowedPrincipalUsernameAttributeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PrincipalUsernameAttributeEnum value
func (v PrincipalUsernameAttributeEnum) Ptr() *PrincipalUsernameAttributeEnum {
	return &v
}

type NullablePrincipalUsernameAttributeEnum struct {
	value *PrincipalUsernameAttributeEnum
	isSet bool
}

func (v NullablePrincipalUsernameAttributeEnum) Get() *PrincipalUsernameAttributeEnum {
	return v.value
}

func (v *NullablePrincipalUsernameAttributeEnum) Set(val *PrincipalUsernameAttributeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipalUsernameAttributeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipalUsernameAttributeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipalUsernameAttributeEnum(val *PrincipalUsernameAttributeEnum) *NullablePrincipalUsernameAttributeEnum {
	return &NullablePrincipalUsernameAttributeEnum{value: val, isSet: true}
}

func (v NullablePrincipalUsernameAttributeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipalUsernameAttributeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
