/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosUserKeyOutpost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosUserKeyOutpost{}

// KerberosUserKeyOutpost User key data consumed by the KDC outpost.
type KerberosUserKeyOutpost struct {
	Username             string                 `json:"username"`
	Kvno                 int32                  `json:"kvno"`
	Salt                 string                 `json:"salt"`
	Keys                 map[string]interface{} `json:"keys"`
	AdditionalProperties map[string]interface{}
}

type _KerberosUserKeyOutpost KerberosUserKeyOutpost

// NewKerberosUserKeyOutpost instantiates a new KerberosUserKeyOutpost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosUserKeyOutpost(username string, kvno int32, salt string, keys map[string]interface{}) *KerberosUserKeyOutpost {
	this := KerberosUserKeyOutpost{}
	this.Username = username
	this.Kvno = kvno
	this.Salt = salt
	this.Keys = keys
	return &this
}

// NewKerberosUserKeyOutpostWithDefaults instantiates a new KerberosUserKeyOutpost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosUserKeyOutpostWithDefaults() *KerberosUserKeyOutpost {
	this := KerberosUserKeyOutpost{}
	return &this
}

// GetUsername returns the Username field value
func (o *KerberosUserKeyOutpost) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *KerberosUserKeyOutpost) SetUsername(v string) {
	o.Username = v
}

// GetKvno returns the Kvno field value
func (o *KerberosUserKeyOutpost) GetKvno() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Kvno
}

// GetKvnoOk returns a tuple with the Kvno field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetKvnoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kvno, true
}

// SetKvno sets field value
func (o *KerberosUserKeyOutpost) SetKvno(v int32) {
	o.Kvno = v
}

// GetSalt returns the Salt field value
func (o *KerberosUserKeyOutpost) GetSalt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Salt
}

// GetSaltOk returns a tuple with the Salt field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetSaltOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Salt, true
}

// SetSalt sets field value
func (o *KerberosUserKeyOutpost) SetSalt(v string) {
	o.Salt = v
}

// GetKeys returns the Keys field value
func (o *KerberosUserKeyOutpost) GetKeys() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetKeysOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *KerberosUserKeyOutpost) SetKeys(v map[string]interface{}) {
	o.Keys = v
}

func (o KerberosUserKeyOutpost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosUserKeyOutpost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["kvno"] = o.Kvno
	toSerialize["salt"] = o.Salt
	toSerialize["keys"] = o.Keys

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosUserKeyOutpost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"kvno",
		"salt",
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosUserKeyOutpost := _KerberosUserKeyOutpost{}

	err = json.Unmarshal(data, &varKerberosUserKeyOutpost)

	if err != nil {
		return err
	}

	*o = KerberosUserKeyOutpost(varKerberosUserKeyOutpost)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "kvno")
		delete(additionalProperties, "salt")
		delete(additionalProperties, "keys")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosUserKeyOutpost struct {
	value *KerberosUserKeyOutpost
	isSet bool
}

func (v NullableKerberosUserKeyOutpost) Get() *KerberosUserKeyOutpost {
	return v.value
}

func (v *NullableKerberosUserKeyOutpost) Set(val *KerberosUserKeyOutpost) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosUserKeyOutpost) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosUserKeyOutpost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosUserKeyOutpost(val *KerberosUserKeyOutpost) *NullableKerberosUserKeyOutpost {
	return &NullableKerberosUserKeyOutpost{value: val, isSet: true}
}

func (v NullableKerberosUserKeyOutpost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosUserKeyOutpost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
