/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosOTPCheckRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosOTPCheckRequestRequest{}

// KerberosOTPCheckRequestRequest OTP validation request submitted by the KDC outpost.
type KerberosOTPCheckRequestRequest struct {
	Username             string `json:"username"`
	Value                string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _KerberosOTPCheckRequestRequest KerberosOTPCheckRequestRequest

// NewKerberosOTPCheckRequestRequest instantiates a new KerberosOTPCheckRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosOTPCheckRequestRequest(username string, value string) *KerberosOTPCheckRequestRequest {
	this := KerberosOTPCheckRequestRequest{}
	this.Username = username
	this.Value = value
	return &this
}

// NewKerberosOTPCheckRequestRequestWithDefaults instantiates a new KerberosOTPCheckRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosOTPCheckRequestRequestWithDefaults() *KerberosOTPCheckRequestRequest {
	this := KerberosOTPCheckRequestRequest{}
	return &this
}

// GetUsername returns the Username field value
func (o *KerberosOTPCheckRequestRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *KerberosOTPCheckRequestRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *KerberosOTPCheckRequestRequest) SetUsername(v string) {
	o.Username = v
}

// GetValue returns the Value field value
func (o *KerberosOTPCheckRequestRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *KerberosOTPCheckRequestRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *KerberosOTPCheckRequestRequest) SetValue(v string) {
	o.Value = v
}

func (o KerberosOTPCheckRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosOTPCheckRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosOTPCheckRequestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosOTPCheckRequestRequest := _KerberosOTPCheckRequestRequest{}

	err = json.Unmarshal(data, &varKerberosOTPCheckRequestRequest)

	if err != nil {
		return err
	}

	*o = KerberosOTPCheckRequestRequest(varKerberosOTPCheckRequestRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosOTPCheckRequestRequest struct {
	value *KerberosOTPCheckRequestRequest
	isSet bool
}

func (v NullableKerberosOTPCheckRequestRequest) Get() *KerberosOTPCheckRequestRequest {
	return v.value
}

func (v *NullableKerberosOTPCheckRequestRequest) Set(val *KerberosOTPCheckRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosOTPCheckRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosOTPCheckRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosOTPCheckRequestRequest(val *KerberosOTPCheckRequestRequest) *NullableKerberosOTPCheckRequestRequest {
	return &NullableKerberosOTPCheckRequestRequest{value: val, isSet: true}
}

func (v NullableKerberosOTPCheckRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosOTPCheckRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
