/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosServicePrincipalAdminRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosServicePrincipalAdminRequest{}

// KerberosServicePrincipalAdminRequest Service principal management request for the kadm5 outpost.
type KerberosServicePrincipalAdminRequest struct {
	Spn                  string `json:"spn"`
	AdditionalProperties map[string]interface{}
}

type _KerberosServicePrincipalAdminRequest KerberosServicePrincipalAdminRequest

// NewKerberosServicePrincipalAdminRequest instantiates a new KerberosServicePrincipalAdminRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosServicePrincipalAdminRequest(spn string) *KerberosServicePrincipalAdminRequest {
	this := KerberosServicePrincipalAdminRequest{}
	this.Spn = spn
	return &this
}

// NewKerberosServicePrincipalAdminRequestWithDefaults instantiates a new KerberosServicePrincipalAdminRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosServicePrincipalAdminRequestWithDefaults() *KerberosServicePrincipalAdminRequest {
	this := KerberosServicePrincipalAdminRequest{}
	return &this
}

// GetSpn returns the Spn field value
func (o *KerberosServicePrincipalAdminRequest) GetSpn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Spn
}

// GetSpnOk returns a tuple with the Spn field value
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipalAdminRequest) GetSpnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spn, true
}

// SetSpn sets field value
func (o *KerberosServicePrincipalAdminRequest) SetSpn(v string) {
	o.Spn = v
}

func (o KerberosServicePrincipalAdminRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosServicePrincipalAdminRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spn"] = o.Spn

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosServicePrincipalAdminRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosServicePrincipalAdminRequest := _KerberosServicePrincipalAdminRequest{}

	err = json.Unmarshal(data, &varKerberosServicePrincipalAdminRequest)

	if err != nil {
		return err
	}

	*o = KerberosServicePrincipalAdminRequest(varKerberosServicePrincipalAdminRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "spn")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosServicePrincipalAdminRequest struct {
	value *KerberosServicePrincipalAdminRequest
	isSet bool
}

func (v NullableKerberosServicePrincipalAdminRequest) Get() *KerberosServicePrincipalAdminRequest {
	return v.value
}

func (v *NullableKerberosServicePrincipalAdminRequest) Set(val *KerberosServicePrincipalAdminRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosServicePrincipalAdminRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosServicePrincipalAdminRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosServicePrincipalAdminRequest(val *KerberosServicePrincipalAdminRequest) *NullableKerberosServicePrincipalAdminRequest {
	return &NullableKerberosServicePrincipalAdminRequest{value: val, isSet: true}
}

func (v NullableKerberosServicePrincipalAdminRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosServicePrincipalAdminRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
