/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosOutpostConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosOutpostConfig{}

// KerberosOutpostConfig Kerberos provider serializer for outposts.
type KerberosOutpostConfig struct {
	Pk                         int32                           `json:"pk"`
	Name                       string                          `json:"name"`
	RealmName                  string                          `json:"realm_name"`
	DefaultDomain              *string                         `json:"default_domain,omitempty"`
	MaximumTicketLifetime      int32                           `json:"maximum_ticket_lifetime"`
	MaximumTicketRenewLifetime int32                           `json:"maximum_ticket_renew_lifetime"`
	DefaultTicketLifetime      *string                         `json:"default_ticket_lifetime,omitempty"`
	DefaultTicketRenewLifetime *string                         `json:"default_ticket_renew_lifetime,omitempty"`
	AllowedEnctypes            []AllowedEnctypesEnum           `json:"allowed_enctypes,omitempty"`
	RequirePreauthentication   *bool                           `json:"require_preauthentication,omitempty"`
	UdpEnabled                 *bool                           `json:"udp_enabled,omitempty"`
	TcpEnabled                 *bool                           `json:"tcp_enabled,omitempty"`
	Forwardable                *bool                           `json:"forwardable,omitempty"`
	Renewable                  *bool                           `json:"renewable,omitempty"`
	Proxiable                  *bool                           `json:"proxiable,omitempty"`
	PrincipalUsernameAttribute *PrincipalUsernameAttributeEnum `json:"principal_username_attribute,omitempty"`
	// Certificate/key pair the KDC uses to sign PKINIT replies. Requires a private key.
	PkinitCertificate NullableString `json:"pkinit_certificate,omitempty"`
	// CA certificate used to validate PKINIT client certificates.
	PkinitClientCa       NullableString `json:"pkinit_client_ca,omitempty"`
	MasterKey            *string        `json:"master_key,omitempty"`
	ApplicationSlug      string         `json:"application_slug"`
	AdditionalProperties map[string]interface{}
}

type _KerberosOutpostConfig KerberosOutpostConfig

// NewKerberosOutpostConfig instantiates a new KerberosOutpostConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosOutpostConfig(pk int32, name string, realmName string, maximumTicketLifetime int32, maximumTicketRenewLifetime int32, applicationSlug string) *KerberosOutpostConfig {
	this := KerberosOutpostConfig{}
	this.Pk = pk
	this.Name = name
	this.RealmName = realmName
	this.MaximumTicketLifetime = maximumTicketLifetime
	this.MaximumTicketRenewLifetime = maximumTicketRenewLifetime
	this.ApplicationSlug = applicationSlug
	return &this
}

// NewKerberosOutpostConfigWithDefaults instantiates a new KerberosOutpostConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosOutpostConfigWithDefaults() *KerberosOutpostConfig {
	this := KerberosOutpostConfig{}
	return &this
}

// GetPk returns the Pk field value
func (o *KerberosOutpostConfig) GetPk() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pk
}

// GetPkOk returns a tuple with the Pk field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetPkOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pk, true
}

// SetPk sets field value
func (o *KerberosOutpostConfig) SetPk(v int32) {
	o.Pk = v
}

// GetName returns the Name field value
func (o *KerberosOutpostConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KerberosOutpostConfig) SetName(v string) {
	o.Name = v
}

// GetRealmName returns the RealmName field value
func (o *KerberosOutpostConfig) GetRealmName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RealmName
}

// GetRealmNameOk returns a tuple with the RealmName field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetRealmNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RealmName, true
}

// SetRealmName sets field value
func (o *KerberosOutpostConfig) SetRealmName(v string) {
	o.RealmName = v
}

// GetDefaultDomain returns the DefaultDomain field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetDefaultDomain() string {
	if o == nil || IsNil(o.DefaultDomain) {
		var ret string
		return ret
	}
	return *o.DefaultDomain
}

// GetDefaultDomainOk returns a tuple with the DefaultDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetDefaultDomainOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultDomain) {
		return nil, false
	}
	return o.DefaultDomain, true
}

// HasDefaultDomain returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasDefaultDomain() bool {
	if o != nil && !IsNil(o.DefaultDomain) {
		return true
	}

	return false
}

// SetDefaultDomain gets a reference to the given string and assigns it to the DefaultDomain field.
func (o *KerberosOutpostConfig) SetDefaultDomain(v string) {
	o.DefaultDomain = &v
}

// GetMaximumTicketLifetime returns the MaximumTicketLifetime field value
func (o *KerberosOutpostConfig) GetMaximumTicketLifetime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaximumTicketLifetime
}

// GetMaximumTicketLifetimeOk returns a tuple with the MaximumTicketLifetime field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMaximumTicketLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaximumTicketLifetime, true
}

// SetMaximumTicketLifetime sets field value
func (o *KerberosOutpostConfig) SetMaximumTicketLifetime(v int32) {
	o.MaximumTicketLifetime = v
}

// GetMaximumTicketRenewLifetime returns the MaximumTicketRenewLifetime field value
func (o *KerberosOutpostConfig) GetMaximumTicketRenewLifetime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaximumTicketRenewLifetime
}

// GetMaximumTicketRenewLifetimeOk returns a tuple with the MaximumTicketRenewLifetime field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMaximumTicketRenewLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaximumTicketRenewLifetime, true
}

// SetMaximumTicketRenewLifetime sets field value
func (o *KerberosOutpostConfig) SetMaximumTicketRenewLifetime(v int32) {
	o.MaximumTicketRenewLifetime = v
}

// GetDefaultTicketLifetime returns the DefaultTicketLifetime field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetDefaultTicketLifetime() string {
	if o == nil || IsNil(o.DefaultTicketLifetime) {
		var ret string
		return ret
	}
	return *o.DefaultTicketLifetime
}

// GetDefaultTicketLifetimeOk returns a tuple with the DefaultTicketLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetDefaultTicketLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultTicketLifetime) {
		return nil, false
	}
	return o.DefaultTicketLifetime, true
}

// HasDefaultTicketLifetime returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasDefaultTicketLifetime() bool {
	if o != nil && !IsNil(o.DefaultTicketLifetime) {
		return true
	}

	return false
}

// SetDefaultTicketLifetime gets a reference to the given string and assigns it to the DefaultTicketLifetime field.
func (o *KerberosOutpostConfig) SetDefaultTicketLifetime(v string) {
	o.DefaultTicketLifetime = &v
}

// GetDefaultTicketRenewLifetime returns the DefaultTicketRenewLifetime field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetDefaultTicketRenewLifetime() string {
	if o == nil || IsNil(o.DefaultTicketRenewLifetime) {
		var ret string
		return ret
	}
	return *o.DefaultTicketRenewLifetime
}

// GetDefaultTicketRenewLifetimeOk returns a tuple with the DefaultTicketRenewLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetDefaultTicketRenewLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultTicketRenewLifetime) {
		return nil, false
	}
	return o.DefaultTicketRenewLifetime, true
}

// HasDefaultTicketRenewLifetime returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasDefaultTicketRenewLifetime() bool {
	if o != nil && !IsNil(o.DefaultTicketRenewLifetime) {
		return true
	}

	return false
}

// SetDefaultTicketRenewLifetime gets a reference to the given string and assigns it to the DefaultTicketRenewLifetime field.
func (o *KerberosOutpostConfig) SetDefaultTicketRenewLifetime(v string) {
	o.DefaultTicketRenewLifetime = &v
}

// GetAllowedEnctypes returns the AllowedEnctypes field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetAllowedEnctypes() []AllowedEnctypesEnum {
	if o == nil || IsNil(o.AllowedEnctypes) {
		var ret []AllowedEnctypesEnum
		return ret
	}
	return o.AllowedEnctypes
}

// GetAllowedEnctypesOk returns a tuple with the AllowedEnctypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetAllowedEnctypesOk() ([]AllowedEnctypesEnum, bool) {
	if o == nil || IsNil(o.AllowedEnctypes) {
		return nil, false
	}
	return o.AllowedEnctypes, true
}

// HasAllowedEnctypes returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasAllowedEnctypes() bool {
	if o != nil && !IsNil(o.AllowedEnctypes) {
		return true
	}

	return false
}

// SetAllowedEnctypes gets a reference to the given []AllowedEnctypesEnum and assigns it to the AllowedEnctypes field.
func (o *KerberosOutpostConfig) SetAllowedEnctypes(v []AllowedEnctypesEnum) {
	o.AllowedEnctypes = v
}

// GetRequirePreauthentication returns the RequirePreauthentication field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetRequirePreauthentication() bool {
	if o == nil || IsNil(o.RequirePreauthentication) {
		var ret bool
		return ret
	}
	return *o.RequirePreauthentication
}

// GetRequirePreauthenticationOk returns a tuple with the RequirePreauthentication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetRequirePreauthenticationOk() (*bool, bool) {
	if o == nil || IsNil(o.RequirePreauthentication) {
		return nil, false
	}
	return o.RequirePreauthentication, true
}

// HasRequirePreauthentication returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasRequirePreauthentication() bool {
	if o != nil && !IsNil(o.RequirePreauthentication) {
		return true
	}

	return false
}

// SetRequirePreauthentication gets a reference to the given bool and assigns it to the RequirePreauthentication field.
func (o *KerberosOutpostConfig) SetRequirePreauthentication(v bool) {
	o.RequirePreauthentication = &v
}

// GetUdpEnabled returns the UdpEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetUdpEnabled() bool {
	if o == nil || IsNil(o.UdpEnabled) {
		var ret bool
		return ret
	}
	return *o.UdpEnabled
}

// GetUdpEnabledOk returns a tuple with the UdpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetUdpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.UdpEnabled) {
		return nil, false
	}
	return o.UdpEnabled, true
}

// HasUdpEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasUdpEnabled() bool {
	if o != nil && !IsNil(o.UdpEnabled) {
		return true
	}

	return false
}

// SetUdpEnabled gets a reference to the given bool and assigns it to the UdpEnabled field.
func (o *KerberosOutpostConfig) SetUdpEnabled(v bool) {
	o.UdpEnabled = &v
}

// GetTcpEnabled returns the TcpEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetTcpEnabled() bool {
	if o == nil || IsNil(o.TcpEnabled) {
		var ret bool
		return ret
	}
	return *o.TcpEnabled
}

// GetTcpEnabledOk returns a tuple with the TcpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetTcpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.TcpEnabled) {
		return nil, false
	}
	return o.TcpEnabled, true
}

// HasTcpEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasTcpEnabled() bool {
	if o != nil && !IsNil(o.TcpEnabled) {
		return true
	}

	return false
}

// SetTcpEnabled gets a reference to the given bool and assigns it to the TcpEnabled field.
func (o *KerberosOutpostConfig) SetTcpEnabled(v bool) {
	o.TcpEnabled = &v
}

// GetForwardable returns the Forwardable field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetForwardable() bool {
	if o == nil || IsNil(o.Forwardable) {
		var ret bool
		return ret
	}
	return *o.Forwardable
}

// GetForwardableOk returns a tuple with the Forwardable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetForwardableOk() (*bool, bool) {
	if o == nil || IsNil(o.Forwardable) {
		return nil, false
	}
	return o.Forwardable, true
}

// HasForwardable returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasForwardable() bool {
	if o != nil && !IsNil(o.Forwardable) {
		return true
	}

	return false
}

// SetForwardable gets a reference to the given bool and assigns it to the Forwardable field.
func (o *KerberosOutpostConfig) SetForwardable(v bool) {
	o.Forwardable = &v
}

// GetRenewable returns the Renewable field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetRenewable() bool {
	if o == nil || IsNil(o.Renewable) {
		var ret bool
		return ret
	}
	return *o.Renewable
}

// GetRenewableOk returns a tuple with the Renewable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetRenewableOk() (*bool, bool) {
	if o == nil || IsNil(o.Renewable) {
		return nil, false
	}
	return o.Renewable, true
}

// HasRenewable returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasRenewable() bool {
	if o != nil && !IsNil(o.Renewable) {
		return true
	}

	return false
}

// SetRenewable gets a reference to the given bool and assigns it to the Renewable field.
func (o *KerberosOutpostConfig) SetRenewable(v bool) {
	o.Renewable = &v
}

// GetProxiable returns the Proxiable field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetProxiable() bool {
	if o == nil || IsNil(o.Proxiable) {
		var ret bool
		return ret
	}
	return *o.Proxiable
}

// GetProxiableOk returns a tuple with the Proxiable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetProxiableOk() (*bool, bool) {
	if o == nil || IsNil(o.Proxiable) {
		return nil, false
	}
	return o.Proxiable, true
}

// HasProxiable returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasProxiable() bool {
	if o != nil && !IsNil(o.Proxiable) {
		return true
	}

	return false
}

// SetProxiable gets a reference to the given bool and assigns it to the Proxiable field.
func (o *KerberosOutpostConfig) SetProxiable(v bool) {
	o.Proxiable = &v
}

// GetPrincipalUsernameAttribute returns the PrincipalUsernameAttribute field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetPrincipalUsernameAttribute() PrincipalUsernameAttributeEnum {
	if o == nil || IsNil(o.PrincipalUsernameAttribute) {
		var ret PrincipalUsernameAttributeEnum
		return ret
	}
	return *o.PrincipalUsernameAttribute
}

// GetPrincipalUsernameAttributeOk returns a tuple with the PrincipalUsernameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetPrincipalUsernameAttributeOk() (*PrincipalUsernameAttributeEnum, bool) {
	if o == nil || IsNil(o.PrincipalUsernameAttribute) {
		return nil, false
	}
	return o.PrincipalUsernameAttribute, true
}

// HasPrincipalUsernameAttribute returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPrincipalUsernameAttribute() bool {
	if o != nil && !IsNil(o.PrincipalUsernameAttribute) {
		return true
	}

	return false
}

// SetPrincipalUsernameAttribute gets a reference to the given PrincipalUsernameAttributeEnum and assigns it to the PrincipalUsernameAttribute field.
func (o *KerberosOutpostConfig) SetPrincipalUsernameAttribute(v PrincipalUsernameAttributeEnum) {
	o.PrincipalUsernameAttribute = &v
}

// GetPkinitCertificate returns the PkinitCertificate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KerberosOutpostConfig) GetPkinitCertificate() string {
	if o == nil || IsNil(o.PkinitCertificate.Get()) {
		var ret string
		return ret
	}
	return *o.PkinitCertificate.Get()
}

// GetPkinitCertificateOk returns a tuple with the PkinitCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KerberosOutpostConfig) GetPkinitCertificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PkinitCertificate.Get(), o.PkinitCertificate.IsSet()
}

// HasPkinitCertificate returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPkinitCertificate() bool {
	if o != nil && o.PkinitCertificate.IsSet() {
		return true
	}

	return false
}

// SetPkinitCertificate gets a reference to the given NullableString and assigns it to the PkinitCertificate field.
func (o *KerberosOutpostConfig) SetPkinitCertificate(v string) {
	o.PkinitCertificate.Set(&v)
}

// SetPkinitCertificateNil sets the value for PkinitCertificate to be an explicit nil
func (o *KerberosOutpostConfig) SetPkinitCertificateNil() {
	o.PkinitCertificate.Set(nil)
}

// UnsetPkinitCertificate ensures that no value is present for PkinitCertificate, not even an explicit nil
func (o *KerberosOutpostConfig) UnsetPkinitCertificate() {
	o.PkinitCertificate.Unset()
}

// GetPkinitClientCa returns the PkinitClientCa field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KerberosOutpostConfig) GetPkinitClientCa() string {
	if o == nil || IsNil(o.PkinitClientCa.Get()) {
		var ret string
		return ret
	}
	return *o.PkinitClientCa.Get()
}

// GetPkinitClientCaOk returns a tuple with the PkinitClientCa field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KerberosOutpostConfig) GetPkinitClientCaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PkinitClientCa.Get(), o.PkinitClientCa.IsSet()
}

// HasPkinitClientCa returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPkinitClientCa() bool {
	if o != nil && o.PkinitClientCa.IsSet() {
		return true
	}

	return false
}

// SetPkinitClientCa gets a reference to the given NullableString and assigns it to the PkinitClientCa field.
func (o *KerberosOutpostConfig) SetPkinitClientCa(v string) {
	o.PkinitClientCa.Set(&v)
}

// SetPkinitClientCaNil sets the value for PkinitClientCa to be an explicit nil
func (o *KerberosOutpostConfig) SetPkinitClientCaNil() {
	o.PkinitClientCa.Set(nil)
}

// UnsetPkinitClientCa ensures that no value is present for PkinitClientCa, not even an explicit nil
func (o *KerberosOutpostConfig) UnsetPkinitClientCa() {
	o.PkinitClientCa.Unset()
}

// GetMasterKey returns the MasterKey field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetMasterKey() string {
	if o == nil || IsNil(o.MasterKey) {
		var ret string
		return ret
	}
	return *o.MasterKey
}

// GetMasterKeyOk returns a tuple with the MasterKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMasterKeyOk() (*string, bool) {
	if o == nil || IsNil(o.MasterKey) {
		return nil, false
	}
	return o.MasterKey, true
}

// HasMasterKey returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasMasterKey() bool {
	if o != nil && !IsNil(o.MasterKey) {
		return true
	}

	return false
}

// SetMasterKey gets a reference to the given string and assigns it to the MasterKey field.
func (o *KerberosOutpostConfig) SetMasterKey(v string) {
	o.MasterKey = &v
}

// GetApplicationSlug returns the ApplicationSlug field value
func (o *KerberosOutpostConfig) GetApplicationSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationSlug
}

// GetApplicationSlugOk returns a tuple with the ApplicationSlug field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetApplicationSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationSlug, true
}

// SetApplicationSlug sets field value
func (o *KerberosOutpostConfig) SetApplicationSlug(v string) {
	o.ApplicationSlug = v
}

func (o KerberosOutpostConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosOutpostConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pk"] = o.Pk
	toSerialize["name"] = o.Name
	toSerialize["realm_name"] = o.RealmName
	if !IsNil(o.DefaultDomain) {
		toSerialize["default_domain"] = o.DefaultDomain
	}
	toSerialize["maximum_ticket_lifetime"] = o.MaximumTicketLifetime
	toSerialize["maximum_ticket_renew_lifetime"] = o.MaximumTicketRenewLifetime
	if !IsNil(o.DefaultTicketLifetime) {
		toSerialize["default_ticket_lifetime"] = o.DefaultTicketLifetime
	}
	if !IsNil(o.DefaultTicketRenewLifetime) {
		toSerialize["default_ticket_renew_lifetime"] = o.DefaultTicketRenewLifetime
	}
	if !IsNil(o.AllowedEnctypes) {
		toSerialize["allowed_enctypes"] = o.AllowedEnctypes
	}
	if !IsNil(o.RequirePreauthentication) {
		toSerialize["require_preauthentication"] = o.RequirePreauthentication
	}
	if !IsNil(o.UdpEnabled) {
		toSerialize["udp_enabled"] = o.UdpEnabled
	}
	if !IsNil(o.TcpEnabled) {
		toSerialize["tcp_enabled"] = o.TcpEnabled
	}
	if !IsNil(o.Forwardable) {
		toSerialize["forwardable"] = o.Forwardable
	}
	if !IsNil(o.Renewable) {
		toSerialize["renewable"] = o.Renewable
	}
	if !IsNil(o.Proxiable) {
		toSerialize["proxiable"] = o.Proxiable
	}
	if !IsNil(o.PrincipalUsernameAttribute) {
		toSerialize["principal_username_attribute"] = o.PrincipalUsernameAttribute
	}
	if o.PkinitCertificate.IsSet() {
		toSerialize["pkinit_certificate"] = o.PkinitCertificate.Get()
	}
	if o.PkinitClientCa.IsSet() {
		toSerialize["pkinit_client_ca"] = o.PkinitClientCa.Get()
	}
	if !IsNil(o.MasterKey) {
		toSerialize["master_key"] = o.MasterKey
	}
	toSerialize["application_slug"] = o.ApplicationSlug

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosOutpostConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pk",
		"name",
		"realm_name",
		"maximum_ticket_lifetime",
		"maximum_ticket_renew_lifetime",
		"application_slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosOutpostConfig := _KerberosOutpostConfig{}

	err = json.Unmarshal(data, &varKerberosOutpostConfig)

	if err != nil {
		return err
	}

	*o = KerberosOutpostConfig(varKerberosOutpostConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pk")
		delete(additionalProperties, "name")
		delete(additionalProperties, "realm_name")
		delete(additionalProperties, "default_domain")
		delete(additionalProperties, "maximum_ticket_lifetime")
		delete(additionalProperties, "maximum_ticket_renew_lifetime")
		delete(additionalProperties, "default_ticket_lifetime")
		delete(additionalProperties, "default_ticket_renew_lifetime")
		delete(additionalProperties, "allowed_enctypes")
		delete(additionalProperties, "require_preauthentication")
		delete(additionalProperties, "udp_enabled")
		delete(additionalProperties, "tcp_enabled")
		delete(additionalProperties, "forwardable")
		delete(additionalProperties, "renewable")
		delete(additionalProperties, "proxiable")
		delete(additionalProperties, "principal_username_attribute")
		delete(additionalProperties, "pkinit_certificate")
		delete(additionalProperties, "pkinit_client_ca")
		delete(additionalProperties, "master_key")
		delete(additionalProperties, "application_slug")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosOutpostConfig struct {
	value *KerberosOutpostConfig
	isSet bool
}

func (v NullableKerberosOutpostConfig) Get() *KerberosOutpostConfig {
	return v.value
}

func (v *NullableKerberosOutpostConfig) Set(val *KerberosOutpostConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosOutpostConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosOutpostConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosOutpostConfig(val *KerberosOutpostConfig) *NullableKerberosOutpostConfig {
	return &NullableKerberosOutpostConfig{value: val, isSet: true}
}

func (v NullableKerberosOutpostConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosOutpostConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
