/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosRealmTrustOutpost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosRealmTrustOutpost{}

// KerberosRealmTrustOutpost Realm trust data consumed by the KDC outpost.
type KerberosRealmTrustOutpost struct {
	RemoteRealm          string                 `json:"remote_realm"`
	Capaths              []string               `json:"capaths"`
	OutgoingKvno         int32                  `json:"outgoing_kvno"`
	OutgoingKeys         map[string]interface{} `json:"outgoing_keys"`
	IncomingKvno         int32                  `json:"incoming_kvno"`
	IncomingKeys         map[string]interface{} `json:"incoming_keys"`
	AdditionalProperties map[string]interface{}
}

type _KerberosRealmTrustOutpost KerberosRealmTrustOutpost

// NewKerberosRealmTrustOutpost instantiates a new KerberosRealmTrustOutpost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosRealmTrustOutpost(remoteRealm string, capaths []string, outgoingKvno int32, outgoingKeys map[string]interface{}, incomingKvno int32, incomingKeys map[string]interface{}) *KerberosRealmTrustOutpost {
	this := KerberosRealmTrustOutpost{}
	this.RemoteRealm = remoteRealm
	this.Capaths = capaths
	this.OutgoingKvno = outgoingKvno
	this.OutgoingKeys = outgoingKeys
	this.IncomingKvno = incomingKvno
	this.IncomingKeys = incomingKeys
	return &this
}

// NewKerberosRealmTrustOutpostWithDefaults instantiates a new KerberosRealmTrustOutpost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosRealmTrustOutpostWithDefaults() *KerberosRealmTrustOutpost {
	this := KerberosRealmTrustOutpost{}
	return &this
}

// GetRemoteRealm returns the RemoteRealm field value
func (o *KerberosRealmTrustOutpost) GetRemoteRealm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteRealm
}

// GetRemoteRealmOk returns a tuple with the RemoteRealm field value
// and a boolean to check if the value has been set.
func (o *KerberosRealmTrustOutpost) GetRemoteRealmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteRealm, true
}

// SetRemoteRealm sets field value
func (o *KerberosRealmTrustOutpost) SetRemoteRealm(v string) {
	o.RemoteRealm = v
}

// GetCapaths returns the Capaths field value
func (o *KerberosRealmTrustOutpost) GetCapaths() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Capaths
}

// GetCapathsOk returns a tuple with the Capaths field value
// and a boolean to check if the value has been set.
func (o *KerberosRealmTrustOutpost) GetCapathsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Capaths, true
}

// SetCapaths sets field value
func (o *KerberosRealmTrustOutpost) SetCapaths(v []string) {
	o.Capaths = v
}

// GetOutgoingKvno returns the OutgoingKvno field value
func (o *KerberosRealmTrustOutpost) GetOutgoingKvno() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OutgoingKvno
}

// GetOutgoingKvnoOk returns a tuple with the OutgoingKvno field value
// and a boolean to check if the value has been set.
func (o *KerberosRealmTrustOutpost) GetOutgoingKvnoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutgoingKvno, true
}

// SetOutgoingKvno sets field value
func (o *KerberosRealmTrustOutpost) SetOutgoingKvno(v int32) {
	o.OutgoingKvno = v
}

// GetOutgoingKeys returns the OutgoingKeys field value
func (o *KerberosRealmTrustOutpost) GetOutgoingKeys() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.OutgoingKeys
}

// GetOutgoingKeysOk returns a tuple with the OutgoingKeys field value
// and a boolean to check if the value has been set.
func (o *KerberosRealmTrustOutpost) GetOutgoingKeysOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.OutgoingKeys, true
}

// SetOutgoingKeys sets field value
func (o *KerberosRealmTrustOutpost) SetOutgoingKeys(v map[string]interface{}) {
	o.OutgoingKeys = v
}

// GetIncomingKvno returns the IncomingKvno field value
func (o *KerberosRealmTrustOutpost) GetIncomingKvno() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IncomingKvno
}

// GetIncomingKvnoOk returns a tuple with the IncomingKvno field value
// and a boolean to check if the value has been set.
func (o *KerberosRealmTrustOutpost) GetIncomingKvnoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncomingKvno, true
}

// SetIncomingKvno sets field value
func (o *KerberosRealmTrustOutpost) SetIncomingKvno(v int32) {
	o.IncomingKvno = v
}

// GetIncomingKeys returns the IncomingKeys field value
func (o *KerberosRealmTrustOutpost) GetIncomingKeys() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.IncomingKeys
}

// GetIncomingKeysOk returns a tuple with the IncomingKeys field value
// and a boolean to check if the value has been set.
func (o *KerberosRealmTrustOutpost) GetIncomingKeysOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.IncomingKeys, true
}

// SetIncomingKeys sets field value
func (o *KerberosRealmTrustOutpost) SetIncomingKeys(v map[string]interface{}) {
	o.IncomingKeys = v
}

func (o KerberosRealmTrustOutpost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosRealmTrustOutpost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["remote_realm"] = o.RemoteRealm
	toSerialize["capaths"] = o.Capaths
	toSerialize["outgoing_kvno"] = o.OutgoingKvno
	toSerialize["outgoing_keys"] = o.OutgoingKeys
	toSerialize["incoming_kvno"] = o.IncomingKvno
	toSerialize["incoming_keys"] = o.IncomingKeys

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosRealmTrustOutpost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"remote_realm",
		"capaths",
		"outgoing_kvno",
		"outgoing_keys",
		"incoming_kvno",
		"incoming_keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosRealmTrustOutpost := _KerberosRealmTrustOutpost{}

	err = json.Unmarshal(data, &varKerberosRealmTrustOutpost)

	if err != nil {
		return err
	}

	*o = KerberosRealmTrustOutpost(varKerberosRealmTrustOutpost)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "remote_realm")
		delete(additionalProperties, "capaths")
		delete(additionalProperties, "outgoing_kvno")
		delete(additionalProperties, "outgoing_keys")
		delete(additionalProperties, "incoming_kvno")
		delete(additionalProperties, "incoming_keys")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosRealmTrustOutpost struct {
	value *KerberosRealmTrustOutpost
	isSet bool
}

func (v NullableKerberosRealmTrustOutpost) Get() *KerberosRealmTrustOutpost {
	return v.value
}

func (v *NullableKerberosRealmTrustOutpost) Set(val *KerberosRealmTrustOutpost) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosRealmTrustOutpost) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosRealmTrustOutpost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosRealmTrustOutpost(val *KerberosRealmTrustOutpost) *NullableKerberosRealmTrustOutpost {
	return &NullableKerberosRealmTrustOutpost{value: val, isSet: true}
}

func (v NullableKerberosRealmTrustOutpost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosRealmTrustOutpost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
