/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosOutpostConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosOutpostConfig{}

// KerberosOutpostConfig Kerberos provider serializer for outposts.
type KerberosOutpostConfig struct {
	Pk                         int32                 `json:"pk"`
	Name                       string                `json:"name"`
	RealmName                  string                `json:"realm_name"`
	DefaultDomain              *string               `json:"default_domain,omitempty"`
	MaximumTicketLifetime      int32                 `json:"maximum_ticket_lifetime"`
	MaximumTicketRenewLifetime int32                 `json:"maximum_ticket_renew_lifetime"`
	DefaultTicketLifetime      *string               `json:"default_ticket_lifetime,omitempty"`
	DefaultTicketRenewLifetime *string               `json:"default_ticket_renew_lifetime,omitempty"`
	AllowedEnctypes            []AllowedEnctypesEnum `json:"allowed_enctypes,omitempty"`
	RequirePreauthentication   *bool                 `json:"require_preauthentication,omitempty"`
	// Advertise PA-SPAKE preauthentication (RFC 9588).
	SpakeEnabled *bool `json:"spake_enabled,omitempty"`
	UdpEnabled   *bool `json:"udp_enabled,omitempty"`
	TcpEnabled   *bool `json:"tcp_enabled,omitempty"`
	// Enable RFC 3244 password changes through the Kerberos outpost.
	KpasswdEnabled             *bool                           `json:"kpasswd_enabled,omitempty"`
	Forwardable                *bool                           `json:"forwardable,omitempty"`
	Renewable                  *bool                           `json:"renewable,omitempty"`
	Proxiable                  *bool                           `json:"proxiable,omitempty"`
	PrincipalUsernameAttribute *PrincipalUsernameAttributeEnum `json:"principal_username_attribute,omitempty"`
	// Certificate/key pair the KDC uses to sign PKINIT replies. Requires a private key.
	PkinitCertificate NullableString `json:"pkinit_certificate,omitempty"`
	// CA certificate used to validate PKINIT client certificates.
	PkinitClientCa NullableString `json:"pkinit_client_ca,omitempty"`
	// Require RFC 8070 freshness tokens on PKINIT requests.
	PkinitRequireFreshness *bool `json:"pkinit_require_freshness,omitempty"`
	// Authentication indicators asserted after successful PKINIT.
	PkinitIndicators []string `json:"pkinit_indicators,omitempty"`
	// Indicators asserted after SPAKE preauthentication.
	SpakeIndicators []string `json:"spake_indicators,omitempty"`
	// Indicator asserted after encrypted-challenge preauthentication.
	EncryptedChallengeIndicator *string `json:"encrypted_challenge_indicator,omitempty"`
	// Enable RFC 6560 OTP preauthentication backed by the user's authentik TOTP and static authenticator devices.
	OtpEnabled *bool `json:"otp_enabled,omitempty"`
	// Authentication indicators asserted after successful OTP preauthentication.
	OtpIndicators []string `json:"otp_indicators,omitempty"`
	// Allow anonymous PKINIT requests.
	AnonymousPkinitEnabled *bool `json:"anonymous_pkinit_enabled,omitempty"`
	// Enable KDC Proxy over HTTPS (MS-KKDCP).
	KkdcpEnabled *bool `json:"kkdcp_enabled,omitempty"`
	// Certificate/key pair the KDC Proxy listener uses for TLS.
	KkdcpCertificate NullableString `json:"kkdcp_certificate,omitempty"`
	// Include an MS-PAC in issued tickets.
	PacEnabled *bool `json:"pac_enabled,omitempty"`
	// Domain SID used for MS-PAC identities, for example S-1-5-21-1-2-3.
	RealmSid *string `json:"realm_sid,omitempty"`
	// Push full MIT Kerberos database dumps to replica KDCs.
	KpropEnabled *bool    `json:"kprop_enabled,omitempty"`
	KpropTargets []string `json:"kprop_targets,omitempty"`
	// Service principal used to authenticate kprop pushes.
	KpropClientSpn *string `json:"kprop_client_spn,omitempty"`
	// MIT database master password used to encrypt full kprop dumps.
	KpropMasterPassword *string `json:"kprop_master_password,omitempty"`
	// Interval in seconds between full kprop pushes.
	KpropInterval *int32 `json:"kprop_interval,omitempty"`
	// Emit authentik events for KDC ticket operations.
	KdcAuditEnabled *bool `json:"kdc_audit_enabled,omitempty"`
	// Serve the kadm5 admin protocol from the outpost.
	KadminEnabled        *bool    `json:"kadmin_enabled,omitempty"`
	KadminAcl            []string `json:"kadmin_acl,omitempty"`
	MasterKey            *string  `json:"master_key,omitempty"`
	ApplicationSlug      string   `json:"application_slug"`
	AdditionalProperties map[string]interface{}
}

type _KerberosOutpostConfig KerberosOutpostConfig

// NewKerberosOutpostConfig instantiates a new KerberosOutpostConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosOutpostConfig(pk int32, name string, realmName string, maximumTicketLifetime int32, maximumTicketRenewLifetime int32, applicationSlug string) *KerberosOutpostConfig {
	this := KerberosOutpostConfig{}
	this.Pk = pk
	this.Name = name
	this.RealmName = realmName
	this.MaximumTicketLifetime = maximumTicketLifetime
	this.MaximumTicketRenewLifetime = maximumTicketRenewLifetime
	this.ApplicationSlug = applicationSlug
	return &this
}

// NewKerberosOutpostConfigWithDefaults instantiates a new KerberosOutpostConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosOutpostConfigWithDefaults() *KerberosOutpostConfig {
	this := KerberosOutpostConfig{}
	return &this
}

// GetPk returns the Pk field value
func (o *KerberosOutpostConfig) GetPk() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pk
}

// GetPkOk returns a tuple with the Pk field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetPkOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pk, true
}

// SetPk sets field value
func (o *KerberosOutpostConfig) SetPk(v int32) {
	o.Pk = v
}

// GetName returns the Name field value
func (o *KerberosOutpostConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KerberosOutpostConfig) SetName(v string) {
	o.Name = v
}

// GetRealmName returns the RealmName field value
func (o *KerberosOutpostConfig) GetRealmName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RealmName
}

// GetRealmNameOk returns a tuple with the RealmName field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetRealmNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RealmName, true
}

// SetRealmName sets field value
func (o *KerberosOutpostConfig) SetRealmName(v string) {
	o.RealmName = v
}

// GetDefaultDomain returns the DefaultDomain field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetDefaultDomain() string {
	if o == nil || IsNil(o.DefaultDomain) {
		var ret string
		return ret
	}
	return *o.DefaultDomain
}

// GetDefaultDomainOk returns a tuple with the DefaultDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetDefaultDomainOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultDomain) {
		return nil, false
	}
	return o.DefaultDomain, true
}

// HasDefaultDomain returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasDefaultDomain() bool {
	if o != nil && !IsNil(o.DefaultDomain) {
		return true
	}

	return false
}

// SetDefaultDomain gets a reference to the given string and assigns it to the DefaultDomain field.
func (o *KerberosOutpostConfig) SetDefaultDomain(v string) {
	o.DefaultDomain = &v
}

// GetMaximumTicketLifetime returns the MaximumTicketLifetime field value
func (o *KerberosOutpostConfig) GetMaximumTicketLifetime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaximumTicketLifetime
}

// GetMaximumTicketLifetimeOk returns a tuple with the MaximumTicketLifetime field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMaximumTicketLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaximumTicketLifetime, true
}

// SetMaximumTicketLifetime sets field value
func (o *KerberosOutpostConfig) SetMaximumTicketLifetime(v int32) {
	o.MaximumTicketLifetime = v
}

// GetMaximumTicketRenewLifetime returns the MaximumTicketRenewLifetime field value
func (o *KerberosOutpostConfig) GetMaximumTicketRenewLifetime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaximumTicketRenewLifetime
}

// GetMaximumTicketRenewLifetimeOk returns a tuple with the MaximumTicketRenewLifetime field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMaximumTicketRenewLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaximumTicketRenewLifetime, true
}

// SetMaximumTicketRenewLifetime sets field value
func (o *KerberosOutpostConfig) SetMaximumTicketRenewLifetime(v int32) {
	o.MaximumTicketRenewLifetime = v
}

// GetDefaultTicketLifetime returns the DefaultTicketLifetime field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetDefaultTicketLifetime() string {
	if o == nil || IsNil(o.DefaultTicketLifetime) {
		var ret string
		return ret
	}
	return *o.DefaultTicketLifetime
}

// GetDefaultTicketLifetimeOk returns a tuple with the DefaultTicketLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetDefaultTicketLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultTicketLifetime) {
		return nil, false
	}
	return o.DefaultTicketLifetime, true
}

// HasDefaultTicketLifetime returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasDefaultTicketLifetime() bool {
	if o != nil && !IsNil(o.DefaultTicketLifetime) {
		return true
	}

	return false
}

// SetDefaultTicketLifetime gets a reference to the given string and assigns it to the DefaultTicketLifetime field.
func (o *KerberosOutpostConfig) SetDefaultTicketLifetime(v string) {
	o.DefaultTicketLifetime = &v
}

// GetDefaultTicketRenewLifetime returns the DefaultTicketRenewLifetime field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetDefaultTicketRenewLifetime() string {
	if o == nil || IsNil(o.DefaultTicketRenewLifetime) {
		var ret string
		return ret
	}
	return *o.DefaultTicketRenewLifetime
}

// GetDefaultTicketRenewLifetimeOk returns a tuple with the DefaultTicketRenewLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetDefaultTicketRenewLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultTicketRenewLifetime) {
		return nil, false
	}
	return o.DefaultTicketRenewLifetime, true
}

// HasDefaultTicketRenewLifetime returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasDefaultTicketRenewLifetime() bool {
	if o != nil && !IsNil(o.DefaultTicketRenewLifetime) {
		return true
	}

	return false
}

// SetDefaultTicketRenewLifetime gets a reference to the given string and assigns it to the DefaultTicketRenewLifetime field.
func (o *KerberosOutpostConfig) SetDefaultTicketRenewLifetime(v string) {
	o.DefaultTicketRenewLifetime = &v
}

// GetAllowedEnctypes returns the AllowedEnctypes field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetAllowedEnctypes() []AllowedEnctypesEnum {
	if o == nil || IsNil(o.AllowedEnctypes) {
		var ret []AllowedEnctypesEnum
		return ret
	}
	return o.AllowedEnctypes
}

// GetAllowedEnctypesOk returns a tuple with the AllowedEnctypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetAllowedEnctypesOk() ([]AllowedEnctypesEnum, bool) {
	if o == nil || IsNil(o.AllowedEnctypes) {
		return nil, false
	}
	return o.AllowedEnctypes, true
}

// HasAllowedEnctypes returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasAllowedEnctypes() bool {
	if o != nil && !IsNil(o.AllowedEnctypes) {
		return true
	}

	return false
}

// SetAllowedEnctypes gets a reference to the given []AllowedEnctypesEnum and assigns it to the AllowedEnctypes field.
func (o *KerberosOutpostConfig) SetAllowedEnctypes(v []AllowedEnctypesEnum) {
	o.AllowedEnctypes = v
}

// GetRequirePreauthentication returns the RequirePreauthentication field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetRequirePreauthentication() bool {
	if o == nil || IsNil(o.RequirePreauthentication) {
		var ret bool
		return ret
	}
	return *o.RequirePreauthentication
}

// GetRequirePreauthenticationOk returns a tuple with the RequirePreauthentication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetRequirePreauthenticationOk() (*bool, bool) {
	if o == nil || IsNil(o.RequirePreauthentication) {
		return nil, false
	}
	return o.RequirePreauthentication, true
}

// HasRequirePreauthentication returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasRequirePreauthentication() bool {
	if o != nil && !IsNil(o.RequirePreauthentication) {
		return true
	}

	return false
}

// SetRequirePreauthentication gets a reference to the given bool and assigns it to the RequirePreauthentication field.
func (o *KerberosOutpostConfig) SetRequirePreauthentication(v bool) {
	o.RequirePreauthentication = &v
}

// GetSpakeEnabled returns the SpakeEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetSpakeEnabled() bool {
	if o == nil || IsNil(o.SpakeEnabled) {
		var ret bool
		return ret
	}
	return *o.SpakeEnabled
}

// GetSpakeEnabledOk returns a tuple with the SpakeEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetSpakeEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SpakeEnabled) {
		return nil, false
	}
	return o.SpakeEnabled, true
}

// HasSpakeEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasSpakeEnabled() bool {
	if o != nil && !IsNil(o.SpakeEnabled) {
		return true
	}

	return false
}

// SetSpakeEnabled gets a reference to the given bool and assigns it to the SpakeEnabled field.
func (o *KerberosOutpostConfig) SetSpakeEnabled(v bool) {
	o.SpakeEnabled = &v
}

// GetUdpEnabled returns the UdpEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetUdpEnabled() bool {
	if o == nil || IsNil(o.UdpEnabled) {
		var ret bool
		return ret
	}
	return *o.UdpEnabled
}

// GetUdpEnabledOk returns a tuple with the UdpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetUdpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.UdpEnabled) {
		return nil, false
	}
	return o.UdpEnabled, true
}

// HasUdpEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasUdpEnabled() bool {
	if o != nil && !IsNil(o.UdpEnabled) {
		return true
	}

	return false
}

// SetUdpEnabled gets a reference to the given bool and assigns it to the UdpEnabled field.
func (o *KerberosOutpostConfig) SetUdpEnabled(v bool) {
	o.UdpEnabled = &v
}

// GetTcpEnabled returns the TcpEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetTcpEnabled() bool {
	if o == nil || IsNil(o.TcpEnabled) {
		var ret bool
		return ret
	}
	return *o.TcpEnabled
}

// GetTcpEnabledOk returns a tuple with the TcpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetTcpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.TcpEnabled) {
		return nil, false
	}
	return o.TcpEnabled, true
}

// HasTcpEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasTcpEnabled() bool {
	if o != nil && !IsNil(o.TcpEnabled) {
		return true
	}

	return false
}

// SetTcpEnabled gets a reference to the given bool and assigns it to the TcpEnabled field.
func (o *KerberosOutpostConfig) SetTcpEnabled(v bool) {
	o.TcpEnabled = &v
}

// GetKpasswdEnabled returns the KpasswdEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKpasswdEnabled() bool {
	if o == nil || IsNil(o.KpasswdEnabled) {
		var ret bool
		return ret
	}
	return *o.KpasswdEnabled
}

// GetKpasswdEnabledOk returns a tuple with the KpasswdEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKpasswdEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.KpasswdEnabled) {
		return nil, false
	}
	return o.KpasswdEnabled, true
}

// HasKpasswdEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKpasswdEnabled() bool {
	if o != nil && !IsNil(o.KpasswdEnabled) {
		return true
	}

	return false
}

// SetKpasswdEnabled gets a reference to the given bool and assigns it to the KpasswdEnabled field.
func (o *KerberosOutpostConfig) SetKpasswdEnabled(v bool) {
	o.KpasswdEnabled = &v
}

// GetForwardable returns the Forwardable field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetForwardable() bool {
	if o == nil || IsNil(o.Forwardable) {
		var ret bool
		return ret
	}
	return *o.Forwardable
}

// GetForwardableOk returns a tuple with the Forwardable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetForwardableOk() (*bool, bool) {
	if o == nil || IsNil(o.Forwardable) {
		return nil, false
	}
	return o.Forwardable, true
}

// HasForwardable returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasForwardable() bool {
	if o != nil && !IsNil(o.Forwardable) {
		return true
	}

	return false
}

// SetForwardable gets a reference to the given bool and assigns it to the Forwardable field.
func (o *KerberosOutpostConfig) SetForwardable(v bool) {
	o.Forwardable = &v
}

// GetRenewable returns the Renewable field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetRenewable() bool {
	if o == nil || IsNil(o.Renewable) {
		var ret bool
		return ret
	}
	return *o.Renewable
}

// GetRenewableOk returns a tuple with the Renewable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetRenewableOk() (*bool, bool) {
	if o == nil || IsNil(o.Renewable) {
		return nil, false
	}
	return o.Renewable, true
}

// HasRenewable returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasRenewable() bool {
	if o != nil && !IsNil(o.Renewable) {
		return true
	}

	return false
}

// SetRenewable gets a reference to the given bool and assigns it to the Renewable field.
func (o *KerberosOutpostConfig) SetRenewable(v bool) {
	o.Renewable = &v
}

// GetProxiable returns the Proxiable field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetProxiable() bool {
	if o == nil || IsNil(o.Proxiable) {
		var ret bool
		return ret
	}
	return *o.Proxiable
}

// GetProxiableOk returns a tuple with the Proxiable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetProxiableOk() (*bool, bool) {
	if o == nil || IsNil(o.Proxiable) {
		return nil, false
	}
	return o.Proxiable, true
}

// HasProxiable returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasProxiable() bool {
	if o != nil && !IsNil(o.Proxiable) {
		return true
	}

	return false
}

// SetProxiable gets a reference to the given bool and assigns it to the Proxiable field.
func (o *KerberosOutpostConfig) SetProxiable(v bool) {
	o.Proxiable = &v
}

// GetPrincipalUsernameAttribute returns the PrincipalUsernameAttribute field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetPrincipalUsernameAttribute() PrincipalUsernameAttributeEnum {
	if o == nil || IsNil(o.PrincipalUsernameAttribute) {
		var ret PrincipalUsernameAttributeEnum
		return ret
	}
	return *o.PrincipalUsernameAttribute
}

// GetPrincipalUsernameAttributeOk returns a tuple with the PrincipalUsernameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetPrincipalUsernameAttributeOk() (*PrincipalUsernameAttributeEnum, bool) {
	if o == nil || IsNil(o.PrincipalUsernameAttribute) {
		return nil, false
	}
	return o.PrincipalUsernameAttribute, true
}

// HasPrincipalUsernameAttribute returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPrincipalUsernameAttribute() bool {
	if o != nil && !IsNil(o.PrincipalUsernameAttribute) {
		return true
	}

	return false
}

// SetPrincipalUsernameAttribute gets a reference to the given PrincipalUsernameAttributeEnum and assigns it to the PrincipalUsernameAttribute field.
func (o *KerberosOutpostConfig) SetPrincipalUsernameAttribute(v PrincipalUsernameAttributeEnum) {
	o.PrincipalUsernameAttribute = &v
}

// GetPkinitCertificate returns the PkinitCertificate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KerberosOutpostConfig) GetPkinitCertificate() string {
	if o == nil || IsNil(o.PkinitCertificate.Get()) {
		var ret string
		return ret
	}
	return *o.PkinitCertificate.Get()
}

// GetPkinitCertificateOk returns a tuple with the PkinitCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KerberosOutpostConfig) GetPkinitCertificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PkinitCertificate.Get(), o.PkinitCertificate.IsSet()
}

// HasPkinitCertificate returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPkinitCertificate() bool {
	if o != nil && o.PkinitCertificate.IsSet() {
		return true
	}

	return false
}

// SetPkinitCertificate gets a reference to the given NullableString and assigns it to the PkinitCertificate field.
func (o *KerberosOutpostConfig) SetPkinitCertificate(v string) {
	o.PkinitCertificate.Set(&v)
}

// SetPkinitCertificateNil sets the value for PkinitCertificate to be an explicit nil
func (o *KerberosOutpostConfig) SetPkinitCertificateNil() {
	o.PkinitCertificate.Set(nil)
}

// UnsetPkinitCertificate ensures that no value is present for PkinitCertificate, not even an explicit nil
func (o *KerberosOutpostConfig) UnsetPkinitCertificate() {
	o.PkinitCertificate.Unset()
}

// GetPkinitClientCa returns the PkinitClientCa field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KerberosOutpostConfig) GetPkinitClientCa() string {
	if o == nil || IsNil(o.PkinitClientCa.Get()) {
		var ret string
		return ret
	}
	return *o.PkinitClientCa.Get()
}

// GetPkinitClientCaOk returns a tuple with the PkinitClientCa field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KerberosOutpostConfig) GetPkinitClientCaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PkinitClientCa.Get(), o.PkinitClientCa.IsSet()
}

// HasPkinitClientCa returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPkinitClientCa() bool {
	if o != nil && o.PkinitClientCa.IsSet() {
		return true
	}

	return false
}

// SetPkinitClientCa gets a reference to the given NullableString and assigns it to the PkinitClientCa field.
func (o *KerberosOutpostConfig) SetPkinitClientCa(v string) {
	o.PkinitClientCa.Set(&v)
}

// SetPkinitClientCaNil sets the value for PkinitClientCa to be an explicit nil
func (o *KerberosOutpostConfig) SetPkinitClientCaNil() {
	o.PkinitClientCa.Set(nil)
}

// UnsetPkinitClientCa ensures that no value is present for PkinitClientCa, not even an explicit nil
func (o *KerberosOutpostConfig) UnsetPkinitClientCa() {
	o.PkinitClientCa.Unset()
}

// GetPkinitRequireFreshness returns the PkinitRequireFreshness field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetPkinitRequireFreshness() bool {
	if o == nil || IsNil(o.PkinitRequireFreshness) {
		var ret bool
		return ret
	}
	return *o.PkinitRequireFreshness
}

// GetPkinitRequireFreshnessOk returns a tuple with the PkinitRequireFreshness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetPkinitRequireFreshnessOk() (*bool, bool) {
	if o == nil || IsNil(o.PkinitRequireFreshness) {
		return nil, false
	}
	return o.PkinitRequireFreshness, true
}

// HasPkinitRequireFreshness returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPkinitRequireFreshness() bool {
	if o != nil && !IsNil(o.PkinitRequireFreshness) {
		return true
	}

	return false
}

// SetPkinitRequireFreshness gets a reference to the given bool and assigns it to the PkinitRequireFreshness field.
func (o *KerberosOutpostConfig) SetPkinitRequireFreshness(v bool) {
	o.PkinitRequireFreshness = &v
}

// GetPkinitIndicators returns the PkinitIndicators field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetPkinitIndicators() []string {
	if o == nil || IsNil(o.PkinitIndicators) {
		var ret []string
		return ret
	}
	return o.PkinitIndicators
}

// GetPkinitIndicatorsOk returns a tuple with the PkinitIndicators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetPkinitIndicatorsOk() ([]string, bool) {
	if o == nil || IsNil(o.PkinitIndicators) {
		return nil, false
	}
	return o.PkinitIndicators, true
}

// HasPkinitIndicators returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPkinitIndicators() bool {
	if o != nil && !IsNil(o.PkinitIndicators) {
		return true
	}

	return false
}

// SetPkinitIndicators gets a reference to the given []string and assigns it to the PkinitIndicators field.
func (o *KerberosOutpostConfig) SetPkinitIndicators(v []string) {
	o.PkinitIndicators = v
}

// GetSpakeIndicators returns the SpakeIndicators field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetSpakeIndicators() []string {
	if o == nil || IsNil(o.SpakeIndicators) {
		var ret []string
		return ret
	}
	return o.SpakeIndicators
}

// GetSpakeIndicatorsOk returns a tuple with the SpakeIndicators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetSpakeIndicatorsOk() ([]string, bool) {
	if o == nil || IsNil(o.SpakeIndicators) {
		return nil, false
	}
	return o.SpakeIndicators, true
}

// HasSpakeIndicators returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasSpakeIndicators() bool {
	if o != nil && !IsNil(o.SpakeIndicators) {
		return true
	}

	return false
}

// SetSpakeIndicators gets a reference to the given []string and assigns it to the SpakeIndicators field.
func (o *KerberosOutpostConfig) SetSpakeIndicators(v []string) {
	o.SpakeIndicators = v
}

// GetEncryptedChallengeIndicator returns the EncryptedChallengeIndicator field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetEncryptedChallengeIndicator() string {
	if o == nil || IsNil(o.EncryptedChallengeIndicator) {
		var ret string
		return ret
	}
	return *o.EncryptedChallengeIndicator
}

// GetEncryptedChallengeIndicatorOk returns a tuple with the EncryptedChallengeIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetEncryptedChallengeIndicatorOk() (*string, bool) {
	if o == nil || IsNil(o.EncryptedChallengeIndicator) {
		return nil, false
	}
	return o.EncryptedChallengeIndicator, true
}

// HasEncryptedChallengeIndicator returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasEncryptedChallengeIndicator() bool {
	if o != nil && !IsNil(o.EncryptedChallengeIndicator) {
		return true
	}

	return false
}

// SetEncryptedChallengeIndicator gets a reference to the given string and assigns it to the EncryptedChallengeIndicator field.
func (o *KerberosOutpostConfig) SetEncryptedChallengeIndicator(v string) {
	o.EncryptedChallengeIndicator = &v
}

// GetOtpEnabled returns the OtpEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetOtpEnabled() bool {
	if o == nil || IsNil(o.OtpEnabled) {
		var ret bool
		return ret
	}
	return *o.OtpEnabled
}

// GetOtpEnabledOk returns a tuple with the OtpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetOtpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.OtpEnabled) {
		return nil, false
	}
	return o.OtpEnabled, true
}

// HasOtpEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasOtpEnabled() bool {
	if o != nil && !IsNil(o.OtpEnabled) {
		return true
	}

	return false
}

// SetOtpEnabled gets a reference to the given bool and assigns it to the OtpEnabled field.
func (o *KerberosOutpostConfig) SetOtpEnabled(v bool) {
	o.OtpEnabled = &v
}

// GetOtpIndicators returns the OtpIndicators field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetOtpIndicators() []string {
	if o == nil || IsNil(o.OtpIndicators) {
		var ret []string
		return ret
	}
	return o.OtpIndicators
}

// GetOtpIndicatorsOk returns a tuple with the OtpIndicators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetOtpIndicatorsOk() ([]string, bool) {
	if o == nil || IsNil(o.OtpIndicators) {
		return nil, false
	}
	return o.OtpIndicators, true
}

// HasOtpIndicators returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasOtpIndicators() bool {
	if o != nil && !IsNil(o.OtpIndicators) {
		return true
	}

	return false
}

// SetOtpIndicators gets a reference to the given []string and assigns it to the OtpIndicators field.
func (o *KerberosOutpostConfig) SetOtpIndicators(v []string) {
	o.OtpIndicators = v
}

// GetAnonymousPkinitEnabled returns the AnonymousPkinitEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetAnonymousPkinitEnabled() bool {
	if o == nil || IsNil(o.AnonymousPkinitEnabled) {
		var ret bool
		return ret
	}
	return *o.AnonymousPkinitEnabled
}

// GetAnonymousPkinitEnabledOk returns a tuple with the AnonymousPkinitEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetAnonymousPkinitEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.AnonymousPkinitEnabled) {
		return nil, false
	}
	return o.AnonymousPkinitEnabled, true
}

// HasAnonymousPkinitEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasAnonymousPkinitEnabled() bool {
	if o != nil && !IsNil(o.AnonymousPkinitEnabled) {
		return true
	}

	return false
}

// SetAnonymousPkinitEnabled gets a reference to the given bool and assigns it to the AnonymousPkinitEnabled field.
func (o *KerberosOutpostConfig) SetAnonymousPkinitEnabled(v bool) {
	o.AnonymousPkinitEnabled = &v
}

// GetKkdcpEnabled returns the KkdcpEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKkdcpEnabled() bool {
	if o == nil || IsNil(o.KkdcpEnabled) {
		var ret bool
		return ret
	}
	return *o.KkdcpEnabled
}

// GetKkdcpEnabledOk returns a tuple with the KkdcpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKkdcpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.KkdcpEnabled) {
		return nil, false
	}
	return o.KkdcpEnabled, true
}

// HasKkdcpEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKkdcpEnabled() bool {
	if o != nil && !IsNil(o.KkdcpEnabled) {
		return true
	}

	return false
}

// SetKkdcpEnabled gets a reference to the given bool and assigns it to the KkdcpEnabled field.
func (o *KerberosOutpostConfig) SetKkdcpEnabled(v bool) {
	o.KkdcpEnabled = &v
}

// GetKkdcpCertificate returns the KkdcpCertificate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KerberosOutpostConfig) GetKkdcpCertificate() string {
	if o == nil || IsNil(o.KkdcpCertificate.Get()) {
		var ret string
		return ret
	}
	return *o.KkdcpCertificate.Get()
}

// GetKkdcpCertificateOk returns a tuple with the KkdcpCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KerberosOutpostConfig) GetKkdcpCertificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KkdcpCertificate.Get(), o.KkdcpCertificate.IsSet()
}

// HasKkdcpCertificate returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKkdcpCertificate() bool {
	if o != nil && o.KkdcpCertificate.IsSet() {
		return true
	}

	return false
}

// SetKkdcpCertificate gets a reference to the given NullableString and assigns it to the KkdcpCertificate field.
func (o *KerberosOutpostConfig) SetKkdcpCertificate(v string) {
	o.KkdcpCertificate.Set(&v)
}

// SetKkdcpCertificateNil sets the value for KkdcpCertificate to be an explicit nil
func (o *KerberosOutpostConfig) SetKkdcpCertificateNil() {
	o.KkdcpCertificate.Set(nil)
}

// UnsetKkdcpCertificate ensures that no value is present for KkdcpCertificate, not even an explicit nil
func (o *KerberosOutpostConfig) UnsetKkdcpCertificate() {
	o.KkdcpCertificate.Unset()
}

// GetPacEnabled returns the PacEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetPacEnabled() bool {
	if o == nil || IsNil(o.PacEnabled) {
		var ret bool
		return ret
	}
	return *o.PacEnabled
}

// GetPacEnabledOk returns a tuple with the PacEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetPacEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.PacEnabled) {
		return nil, false
	}
	return o.PacEnabled, true
}

// HasPacEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasPacEnabled() bool {
	if o != nil && !IsNil(o.PacEnabled) {
		return true
	}

	return false
}

// SetPacEnabled gets a reference to the given bool and assigns it to the PacEnabled field.
func (o *KerberosOutpostConfig) SetPacEnabled(v bool) {
	o.PacEnabled = &v
}

// GetRealmSid returns the RealmSid field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetRealmSid() string {
	if o == nil || IsNil(o.RealmSid) {
		var ret string
		return ret
	}
	return *o.RealmSid
}

// GetRealmSidOk returns a tuple with the RealmSid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetRealmSidOk() (*string, bool) {
	if o == nil || IsNil(o.RealmSid) {
		return nil, false
	}
	return o.RealmSid, true
}

// HasRealmSid returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasRealmSid() bool {
	if o != nil && !IsNil(o.RealmSid) {
		return true
	}

	return false
}

// SetRealmSid gets a reference to the given string and assigns it to the RealmSid field.
func (o *KerberosOutpostConfig) SetRealmSid(v string) {
	o.RealmSid = &v
}

// GetKpropEnabled returns the KpropEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKpropEnabled() bool {
	if o == nil || IsNil(o.KpropEnabled) {
		var ret bool
		return ret
	}
	return *o.KpropEnabled
}

// GetKpropEnabledOk returns a tuple with the KpropEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKpropEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.KpropEnabled) {
		return nil, false
	}
	return o.KpropEnabled, true
}

// HasKpropEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKpropEnabled() bool {
	if o != nil && !IsNil(o.KpropEnabled) {
		return true
	}

	return false
}

// SetKpropEnabled gets a reference to the given bool and assigns it to the KpropEnabled field.
func (o *KerberosOutpostConfig) SetKpropEnabled(v bool) {
	o.KpropEnabled = &v
}

// GetKpropTargets returns the KpropTargets field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKpropTargets() []string {
	if o == nil || IsNil(o.KpropTargets) {
		var ret []string
		return ret
	}
	return o.KpropTargets
}

// GetKpropTargetsOk returns a tuple with the KpropTargets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKpropTargetsOk() ([]string, bool) {
	if o == nil || IsNil(o.KpropTargets) {
		return nil, false
	}
	return o.KpropTargets, true
}

// HasKpropTargets returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKpropTargets() bool {
	if o != nil && !IsNil(o.KpropTargets) {
		return true
	}

	return false
}

// SetKpropTargets gets a reference to the given []string and assigns it to the KpropTargets field.
func (o *KerberosOutpostConfig) SetKpropTargets(v []string) {
	o.KpropTargets = v
}

// GetKpropClientSpn returns the KpropClientSpn field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKpropClientSpn() string {
	if o == nil || IsNil(o.KpropClientSpn) {
		var ret string
		return ret
	}
	return *o.KpropClientSpn
}

// GetKpropClientSpnOk returns a tuple with the KpropClientSpn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKpropClientSpnOk() (*string, bool) {
	if o == nil || IsNil(o.KpropClientSpn) {
		return nil, false
	}
	return o.KpropClientSpn, true
}

// HasKpropClientSpn returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKpropClientSpn() bool {
	if o != nil && !IsNil(o.KpropClientSpn) {
		return true
	}

	return false
}

// SetKpropClientSpn gets a reference to the given string and assigns it to the KpropClientSpn field.
func (o *KerberosOutpostConfig) SetKpropClientSpn(v string) {
	o.KpropClientSpn = &v
}

// GetKpropMasterPassword returns the KpropMasterPassword field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKpropMasterPassword() string {
	if o == nil || IsNil(o.KpropMasterPassword) {
		var ret string
		return ret
	}
	return *o.KpropMasterPassword
}

// GetKpropMasterPasswordOk returns a tuple with the KpropMasterPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKpropMasterPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.KpropMasterPassword) {
		return nil, false
	}
	return o.KpropMasterPassword, true
}

// HasKpropMasterPassword returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKpropMasterPassword() bool {
	if o != nil && !IsNil(o.KpropMasterPassword) {
		return true
	}

	return false
}

// SetKpropMasterPassword gets a reference to the given string and assigns it to the KpropMasterPassword field.
func (o *KerberosOutpostConfig) SetKpropMasterPassword(v string) {
	o.KpropMasterPassword = &v
}

// GetKpropInterval returns the KpropInterval field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKpropInterval() int32 {
	if o == nil || IsNil(o.KpropInterval) {
		var ret int32
		return ret
	}
	return *o.KpropInterval
}

// GetKpropIntervalOk returns a tuple with the KpropInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKpropIntervalOk() (*int32, bool) {
	if o == nil || IsNil(o.KpropInterval) {
		return nil, false
	}
	return o.KpropInterval, true
}

// HasKpropInterval returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKpropInterval() bool {
	if o != nil && !IsNil(o.KpropInterval) {
		return true
	}

	return false
}

// SetKpropInterval gets a reference to the given int32 and assigns it to the KpropInterval field.
func (o *KerberosOutpostConfig) SetKpropInterval(v int32) {
	o.KpropInterval = &v
}

// GetKdcAuditEnabled returns the KdcAuditEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKdcAuditEnabled() bool {
	if o == nil || IsNil(o.KdcAuditEnabled) {
		var ret bool
		return ret
	}
	return *o.KdcAuditEnabled
}

// GetKdcAuditEnabledOk returns a tuple with the KdcAuditEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKdcAuditEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.KdcAuditEnabled) {
		return nil, false
	}
	return o.KdcAuditEnabled, true
}

// HasKdcAuditEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKdcAuditEnabled() bool {
	if o != nil && !IsNil(o.KdcAuditEnabled) {
		return true
	}

	return false
}

// SetKdcAuditEnabled gets a reference to the given bool and assigns it to the KdcAuditEnabled field.
func (o *KerberosOutpostConfig) SetKdcAuditEnabled(v bool) {
	o.KdcAuditEnabled = &v
}

// GetKadminEnabled returns the KadminEnabled field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKadminEnabled() bool {
	if o == nil || IsNil(o.KadminEnabled) {
		var ret bool
		return ret
	}
	return *o.KadminEnabled
}

// GetKadminEnabledOk returns a tuple with the KadminEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKadminEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.KadminEnabled) {
		return nil, false
	}
	return o.KadminEnabled, true
}

// HasKadminEnabled returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKadminEnabled() bool {
	if o != nil && !IsNil(o.KadminEnabled) {
		return true
	}

	return false
}

// SetKadminEnabled gets a reference to the given bool and assigns it to the KadminEnabled field.
func (o *KerberosOutpostConfig) SetKadminEnabled(v bool) {
	o.KadminEnabled = &v
}

// GetKadminAcl returns the KadminAcl field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetKadminAcl() []string {
	if o == nil || IsNil(o.KadminAcl) {
		var ret []string
		return ret
	}
	return o.KadminAcl
}

// GetKadminAclOk returns a tuple with the KadminAcl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetKadminAclOk() ([]string, bool) {
	if o == nil || IsNil(o.KadminAcl) {
		return nil, false
	}
	return o.KadminAcl, true
}

// HasKadminAcl returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasKadminAcl() bool {
	if o != nil && !IsNil(o.KadminAcl) {
		return true
	}

	return false
}

// SetKadminAcl gets a reference to the given []string and assigns it to the KadminAcl field.
func (o *KerberosOutpostConfig) SetKadminAcl(v []string) {
	o.KadminAcl = v
}

// GetMasterKey returns the MasterKey field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetMasterKey() string {
	if o == nil || IsNil(o.MasterKey) {
		var ret string
		return ret
	}
	return *o.MasterKey
}

// GetMasterKeyOk returns a tuple with the MasterKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMasterKeyOk() (*string, bool) {
	if o == nil || IsNil(o.MasterKey) {
		return nil, false
	}
	return o.MasterKey, true
}

// HasMasterKey returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasMasterKey() bool {
	if o != nil && !IsNil(o.MasterKey) {
		return true
	}

	return false
}

// SetMasterKey gets a reference to the given string and assigns it to the MasterKey field.
func (o *KerberosOutpostConfig) SetMasterKey(v string) {
	o.MasterKey = &v
}

// GetApplicationSlug returns the ApplicationSlug field value
func (o *KerberosOutpostConfig) GetApplicationSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationSlug
}

// GetApplicationSlugOk returns a tuple with the ApplicationSlug field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetApplicationSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationSlug, true
}

// SetApplicationSlug sets field value
func (o *KerberosOutpostConfig) SetApplicationSlug(v string) {
	o.ApplicationSlug = v
}

func (o KerberosOutpostConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosOutpostConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pk"] = o.Pk
	toSerialize["name"] = o.Name
	toSerialize["realm_name"] = o.RealmName
	if !IsNil(o.DefaultDomain) {
		toSerialize["default_domain"] = o.DefaultDomain
	}
	toSerialize["maximum_ticket_lifetime"] = o.MaximumTicketLifetime
	toSerialize["maximum_ticket_renew_lifetime"] = o.MaximumTicketRenewLifetime
	if !IsNil(o.DefaultTicketLifetime) {
		toSerialize["default_ticket_lifetime"] = o.DefaultTicketLifetime
	}
	if !IsNil(o.DefaultTicketRenewLifetime) {
		toSerialize["default_ticket_renew_lifetime"] = o.DefaultTicketRenewLifetime
	}
	if !IsNil(o.AllowedEnctypes) {
		toSerialize["allowed_enctypes"] = o.AllowedEnctypes
	}
	if !IsNil(o.RequirePreauthentication) {
		toSerialize["require_preauthentication"] = o.RequirePreauthentication
	}
	if !IsNil(o.SpakeEnabled) {
		toSerialize["spake_enabled"] = o.SpakeEnabled
	}
	if !IsNil(o.UdpEnabled) {
		toSerialize["udp_enabled"] = o.UdpEnabled
	}
	if !IsNil(o.TcpEnabled) {
		toSerialize["tcp_enabled"] = o.TcpEnabled
	}
	if !IsNil(o.KpasswdEnabled) {
		toSerialize["kpasswd_enabled"] = o.KpasswdEnabled
	}
	if !IsNil(o.Forwardable) {
		toSerialize["forwardable"] = o.Forwardable
	}
	if !IsNil(o.Renewable) {
		toSerialize["renewable"] = o.Renewable
	}
	if !IsNil(o.Proxiable) {
		toSerialize["proxiable"] = o.Proxiable
	}
	if !IsNil(o.PrincipalUsernameAttribute) {
		toSerialize["principal_username_attribute"] = o.PrincipalUsernameAttribute
	}
	if o.PkinitCertificate.IsSet() {
		toSerialize["pkinit_certificate"] = o.PkinitCertificate.Get()
	}
	if o.PkinitClientCa.IsSet() {
		toSerialize["pkinit_client_ca"] = o.PkinitClientCa.Get()
	}
	if !IsNil(o.PkinitRequireFreshness) {
		toSerialize["pkinit_require_freshness"] = o.PkinitRequireFreshness
	}
	if !IsNil(o.PkinitIndicators) {
		toSerialize["pkinit_indicators"] = o.PkinitIndicators
	}
	if !IsNil(o.SpakeIndicators) {
		toSerialize["spake_indicators"] = o.SpakeIndicators
	}
	if !IsNil(o.EncryptedChallengeIndicator) {
		toSerialize["encrypted_challenge_indicator"] = o.EncryptedChallengeIndicator
	}
	if !IsNil(o.OtpEnabled) {
		toSerialize["otp_enabled"] = o.OtpEnabled
	}
	if !IsNil(o.OtpIndicators) {
		toSerialize["otp_indicators"] = o.OtpIndicators
	}
	if !IsNil(o.AnonymousPkinitEnabled) {
		toSerialize["anonymous_pkinit_enabled"] = o.AnonymousPkinitEnabled
	}
	if !IsNil(o.KkdcpEnabled) {
		toSerialize["kkdcp_enabled"] = o.KkdcpEnabled
	}
	if o.KkdcpCertificate.IsSet() {
		toSerialize["kkdcp_certificate"] = o.KkdcpCertificate.Get()
	}
	if !IsNil(o.PacEnabled) {
		toSerialize["pac_enabled"] = o.PacEnabled
	}
	if !IsNil(o.RealmSid) {
		toSerialize["realm_sid"] = o.RealmSid
	}
	if !IsNil(o.KpropEnabled) {
		toSerialize["kprop_enabled"] = o.KpropEnabled
	}
	if !IsNil(o.KpropTargets) {
		toSerialize["kprop_targets"] = o.KpropTargets
	}
	if !IsNil(o.KpropClientSpn) {
		toSerialize["kprop_client_spn"] = o.KpropClientSpn
	}
	if !IsNil(o.KpropMasterPassword) {
		toSerialize["kprop_master_password"] = o.KpropMasterPassword
	}
	if !IsNil(o.KpropInterval) {
		toSerialize["kprop_interval"] = o.KpropInterval
	}
	if !IsNil(o.KdcAuditEnabled) {
		toSerialize["kdc_audit_enabled"] = o.KdcAuditEnabled
	}
	if !IsNil(o.KadminEnabled) {
		toSerialize["kadmin_enabled"] = o.KadminEnabled
	}
	if !IsNil(o.KadminAcl) {
		toSerialize["kadmin_acl"] = o.KadminAcl
	}
	if !IsNil(o.MasterKey) {
		toSerialize["master_key"] = o.MasterKey
	}
	toSerialize["application_slug"] = o.ApplicationSlug

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosOutpostConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pk",
		"name",
		"realm_name",
		"maximum_ticket_lifetime",
		"maximum_ticket_renew_lifetime",
		"application_slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosOutpostConfig := _KerberosOutpostConfig{}

	err = json.Unmarshal(data, &varKerberosOutpostConfig)

	if err != nil {
		return err
	}

	*o = KerberosOutpostConfig(varKerberosOutpostConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pk")
		delete(additionalProperties, "name")
		delete(additionalProperties, "realm_name")
		delete(additionalProperties, "default_domain")
		delete(additionalProperties, "maximum_ticket_lifetime")
		delete(additionalProperties, "maximum_ticket_renew_lifetime")
		delete(additionalProperties, "default_ticket_lifetime")
		delete(additionalProperties, "default_ticket_renew_lifetime")
		delete(additionalProperties, "allowed_enctypes")
		delete(additionalProperties, "require_preauthentication")
		delete(additionalProperties, "spake_enabled")
		delete(additionalProperties, "udp_enabled")
		delete(additionalProperties, "tcp_enabled")
		delete(additionalProperties, "kpasswd_enabled")
		delete(additionalProperties, "forwardable")
		delete(additionalProperties, "renewable")
		delete(additionalProperties, "proxiable")
		delete(additionalProperties, "principal_username_attribute")
		delete(additionalProperties, "pkinit_certificate")
		delete(additionalProperties, "pkinit_client_ca")
		delete(additionalProperties, "pkinit_require_freshness")
		delete(additionalProperties, "pkinit_indicators")
		delete(additionalProperties, "spake_indicators")
		delete(additionalProperties, "encrypted_challenge_indicator")
		delete(additionalProperties, "otp_enabled")
		delete(additionalProperties, "otp_indicators")
		delete(additionalProperties, "anonymous_pkinit_enabled")
		delete(additionalProperties, "kkdcp_enabled")
		delete(additionalProperties, "kkdcp_certificate")
		delete(additionalProperties, "pac_enabled")
		delete(additionalProperties, "realm_sid")
		delete(additionalProperties, "kprop_enabled")
		delete(additionalProperties, "kprop_targets")
		delete(additionalProperties, "kprop_client_spn")
		delete(additionalProperties, "kprop_master_password")
		delete(additionalProperties, "kprop_interval")
		delete(additionalProperties, "kdc_audit_enabled")
		delete(additionalProperties, "kadmin_enabled")
		delete(additionalProperties, "kadmin_acl")
		delete(additionalProperties, "master_key")
		delete(additionalProperties, "application_slug")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosOutpostConfig struct {
	value *KerberosOutpostConfig
	isSet bool
}

func (v NullableKerberosOutpostConfig) Get() *KerberosOutpostConfig {
	return v.value
}

func (v *NullableKerberosOutpostConfig) Set(val *KerberosOutpostConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosOutpostConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosOutpostConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosOutpostConfig(val *KerberosOutpostConfig) *NullableKerberosOutpostConfig {
	return &NullableKerberosOutpostConfig{value: val, isSet: true}
}

func (v NullableKerberosOutpostConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosOutpostConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
