/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// TicketFlagsEnum the model 'TicketFlagsEnum'
type TicketFlagsEnum string

// List of TicketFlagsEnum
const (
	TICKETFLAGSENUM_REQUIRES_PREAUTH     TicketFlagsEnum = "requires_preauth"
	TICKETFLAGSENUM_REQUIRES_HWAUTH      TicketFlagsEnum = "requires_hwauth"
	TICKETFLAGSENUM_DISALLOW_POSTDATED   TicketFlagsEnum = "disallow_postdated"
	TICKETFLAGSENUM_DISALLOW_FORWARDABLE TicketFlagsEnum = "disallow_forwardable"
	TICKETFLAGSENUM_DISALLOW_PROXIABLE   TicketFlagsEnum = "disallow_proxiable"
	TICKETFLAGSENUM_DISALLOW_RENEWABLE   TicketFlagsEnum = "disallow_renewable"
	TICKETFLAGSENUM_DISALLOW_TGT_BASED   TicketFlagsEnum = "disallow_tgt_based"
	TICKETFLAGSENUM_DISALLOW_SERVER      TicketFlagsEnum = "disallow_server"
)

// All allowed values of TicketFlagsEnum enum
var AllowedTicketFlagsEnumEnumValues = []TicketFlagsEnum{
	"requires_preauth",
	"requires_hwauth",
	"disallow_postdated",
	"disallow_forwardable",
	"disallow_proxiable",
	"disallow_renewable",
	"disallow_tgt_based",
	"disallow_server",
}

func (v *TicketFlagsEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TicketFlagsEnum(value)
	for _, existing := range AllowedTicketFlagsEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TicketFlagsEnum", value)
}

// NewTicketFlagsEnumFromValue returns a pointer to a valid TicketFlagsEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTicketFlagsEnumFromValue(v string) (*TicketFlagsEnum, error) {
	ev := TicketFlagsEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TicketFlagsEnum: valid values are %v", v, AllowedTicketFlagsEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TicketFlagsEnum) IsValid() bool {
	for _, existing := range AllowedTicketFlagsEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TicketFlagsEnum value
func (v TicketFlagsEnum) Ptr() *TicketFlagsEnum {
	return &v
}

type NullableTicketFlagsEnum struct {
	value *TicketFlagsEnum
	isSet bool
}

func (v NullableTicketFlagsEnum) Get() *TicketFlagsEnum {
	return v.value
}

func (v *NullableTicketFlagsEnum) Set(val *TicketFlagsEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTicketFlagsEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTicketFlagsEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTicketFlagsEnum(val *TicketFlagsEnum) *NullableTicketFlagsEnum {
	return &NullableTicketFlagsEnum{value: val, isSet: true}
}

func (v NullableTicketFlagsEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTicketFlagsEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
