/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the KerberosUserKeyOutpost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosUserKeyOutpost{}

// KerberosUserKeyOutpost User key data consumed by the KDC outpost.
type KerberosUserKeyOutpost struct {
	Username               string                 `json:"username"`
	Enabled                bool                   `json:"enabled"`
	Principal              string                 `json:"principal"`
	Kvno                   int32                  `json:"kvno"`
	Salt                   string                 `json:"salt"`
	Keys                   map[string]interface{} `json:"keys"`
	MaxTicketLifetime      NullableInt32          `json:"max_ticket_lifetime"`
	MaxRenewLifetime       NullableInt32          `json:"max_renew_lifetime"`
	RequiresPasswordChange bool                   `json:"requires_password_change"`
	PacUserId              int32                  `json:"pac_user_id"`
	PacPrimaryGroupId      int32                  `json:"pac_primary_group_id"`
	PacGroupIds            []int32                `json:"pac_group_ids"`
	PacName                string                 `json:"pac_name"`
	PacUpn                 string                 `json:"pac_upn"`
	PasswordExpiration     NullableTime           `json:"password_expiration"`
	Flags                  []string               `json:"flags"`
	AdditionalProperties   map[string]interface{}
}

type _KerberosUserKeyOutpost KerberosUserKeyOutpost

// NewKerberosUserKeyOutpost instantiates a new KerberosUserKeyOutpost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosUserKeyOutpost(username string, enabled bool, principal string, kvno int32, salt string, keys map[string]interface{}, maxTicketLifetime NullableInt32, maxRenewLifetime NullableInt32, requiresPasswordChange bool, pacUserId int32, pacPrimaryGroupId int32, pacGroupIds []int32, pacName string, pacUpn string, passwordExpiration NullableTime, flags []string) *KerberosUserKeyOutpost {
	this := KerberosUserKeyOutpost{}
	this.Username = username
	this.Enabled = enabled
	this.Principal = principal
	this.Kvno = kvno
	this.Salt = salt
	this.Keys = keys
	this.MaxTicketLifetime = maxTicketLifetime
	this.MaxRenewLifetime = maxRenewLifetime
	this.RequiresPasswordChange = requiresPasswordChange
	this.PacUserId = pacUserId
	this.PacPrimaryGroupId = pacPrimaryGroupId
	this.PacGroupIds = pacGroupIds
	this.PacName = pacName
	this.PacUpn = pacUpn
	this.PasswordExpiration = passwordExpiration
	this.Flags = flags
	return &this
}

// NewKerberosUserKeyOutpostWithDefaults instantiates a new KerberosUserKeyOutpost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosUserKeyOutpostWithDefaults() *KerberosUserKeyOutpost {
	this := KerberosUserKeyOutpost{}
	return &this
}

// GetUsername returns the Username field value
func (o *KerberosUserKeyOutpost) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *KerberosUserKeyOutpost) SetUsername(v string) {
	o.Username = v
}

// GetEnabled returns the Enabled field value
func (o *KerberosUserKeyOutpost) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *KerberosUserKeyOutpost) SetEnabled(v bool) {
	o.Enabled = v
}

// GetPrincipal returns the Principal field value
func (o *KerberosUserKeyOutpost) GetPrincipal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetPrincipalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Principal, true
}

// SetPrincipal sets field value
func (o *KerberosUserKeyOutpost) SetPrincipal(v string) {
	o.Principal = v
}

// GetKvno returns the Kvno field value
func (o *KerberosUserKeyOutpost) GetKvno() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Kvno
}

// GetKvnoOk returns a tuple with the Kvno field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetKvnoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kvno, true
}

// SetKvno sets field value
func (o *KerberosUserKeyOutpost) SetKvno(v int32) {
	o.Kvno = v
}

// GetSalt returns the Salt field value
func (o *KerberosUserKeyOutpost) GetSalt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Salt
}

// GetSaltOk returns a tuple with the Salt field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetSaltOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Salt, true
}

// SetSalt sets field value
func (o *KerberosUserKeyOutpost) SetSalt(v string) {
	o.Salt = v
}

// GetKeys returns the Keys field value
func (o *KerberosUserKeyOutpost) GetKeys() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetKeysOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *KerberosUserKeyOutpost) SetKeys(v map[string]interface{}) {
	o.Keys = v
}

// GetMaxTicketLifetime returns the MaxTicketLifetime field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *KerberosUserKeyOutpost) GetMaxTicketLifetime() int32 {
	if o == nil || o.MaxTicketLifetime.Get() == nil {
		var ret int32
		return ret
	}

	return *o.MaxTicketLifetime.Get()
}

// GetMaxTicketLifetimeOk returns a tuple with the MaxTicketLifetime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KerberosUserKeyOutpost) GetMaxTicketLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxTicketLifetime.Get(), o.MaxTicketLifetime.IsSet()
}

// SetMaxTicketLifetime sets field value
func (o *KerberosUserKeyOutpost) SetMaxTicketLifetime(v int32) {
	o.MaxTicketLifetime.Set(&v)
}

// GetMaxRenewLifetime returns the MaxRenewLifetime field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *KerberosUserKeyOutpost) GetMaxRenewLifetime() int32 {
	if o == nil || o.MaxRenewLifetime.Get() == nil {
		var ret int32
		return ret
	}

	return *o.MaxRenewLifetime.Get()
}

// GetMaxRenewLifetimeOk returns a tuple with the MaxRenewLifetime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KerberosUserKeyOutpost) GetMaxRenewLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxRenewLifetime.Get(), o.MaxRenewLifetime.IsSet()
}

// SetMaxRenewLifetime sets field value
func (o *KerberosUserKeyOutpost) SetMaxRenewLifetime(v int32) {
	o.MaxRenewLifetime.Set(&v)
}

// GetRequiresPasswordChange returns the RequiresPasswordChange field value
func (o *KerberosUserKeyOutpost) GetRequiresPasswordChange() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresPasswordChange
}

// GetRequiresPasswordChangeOk returns a tuple with the RequiresPasswordChange field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetRequiresPasswordChangeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresPasswordChange, true
}

// SetRequiresPasswordChange sets field value
func (o *KerberosUserKeyOutpost) SetRequiresPasswordChange(v bool) {
	o.RequiresPasswordChange = v
}

// GetPacUserId returns the PacUserId field value
func (o *KerberosUserKeyOutpost) GetPacUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PacUserId
}

// GetPacUserIdOk returns a tuple with the PacUserId field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetPacUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PacUserId, true
}

// SetPacUserId sets field value
func (o *KerberosUserKeyOutpost) SetPacUserId(v int32) {
	o.PacUserId = v
}

// GetPacPrimaryGroupId returns the PacPrimaryGroupId field value
func (o *KerberosUserKeyOutpost) GetPacPrimaryGroupId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PacPrimaryGroupId
}

// GetPacPrimaryGroupIdOk returns a tuple with the PacPrimaryGroupId field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetPacPrimaryGroupIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PacPrimaryGroupId, true
}

// SetPacPrimaryGroupId sets field value
func (o *KerberosUserKeyOutpost) SetPacPrimaryGroupId(v int32) {
	o.PacPrimaryGroupId = v
}

// GetPacGroupIds returns the PacGroupIds field value
func (o *KerberosUserKeyOutpost) GetPacGroupIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.PacGroupIds
}

// GetPacGroupIdsOk returns a tuple with the PacGroupIds field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetPacGroupIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PacGroupIds, true
}

// SetPacGroupIds sets field value
func (o *KerberosUserKeyOutpost) SetPacGroupIds(v []int32) {
	o.PacGroupIds = v
}

// GetPacName returns the PacName field value
func (o *KerberosUserKeyOutpost) GetPacName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PacName
}

// GetPacNameOk returns a tuple with the PacName field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetPacNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PacName, true
}

// SetPacName sets field value
func (o *KerberosUserKeyOutpost) SetPacName(v string) {
	o.PacName = v
}

// GetPacUpn returns the PacUpn field value
func (o *KerberosUserKeyOutpost) GetPacUpn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PacUpn
}

// GetPacUpnOk returns a tuple with the PacUpn field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetPacUpnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PacUpn, true
}

// SetPacUpn sets field value
func (o *KerberosUserKeyOutpost) SetPacUpn(v string) {
	o.PacUpn = v
}

// GetPasswordExpiration returns the PasswordExpiration field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *KerberosUserKeyOutpost) GetPasswordExpiration() time.Time {
	if o == nil || o.PasswordExpiration.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.PasswordExpiration.Get()
}

// GetPasswordExpirationOk returns a tuple with the PasswordExpiration field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KerberosUserKeyOutpost) GetPasswordExpirationOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PasswordExpiration.Get(), o.PasswordExpiration.IsSet()
}

// SetPasswordExpiration sets field value
func (o *KerberosUserKeyOutpost) SetPasswordExpiration(v time.Time) {
	o.PasswordExpiration.Set(&v)
}

// GetFlags returns the Flags field value
func (o *KerberosUserKeyOutpost) GetFlags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value
// and a boolean to check if the value has been set.
func (o *KerberosUserKeyOutpost) GetFlagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Flags, true
}

// SetFlags sets field value
func (o *KerberosUserKeyOutpost) SetFlags(v []string) {
	o.Flags = v
}

func (o KerberosUserKeyOutpost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosUserKeyOutpost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["enabled"] = o.Enabled
	toSerialize["principal"] = o.Principal
	toSerialize["kvno"] = o.Kvno
	toSerialize["salt"] = o.Salt
	toSerialize["keys"] = o.Keys
	toSerialize["max_ticket_lifetime"] = o.MaxTicketLifetime.Get()
	toSerialize["max_renew_lifetime"] = o.MaxRenewLifetime.Get()
	toSerialize["requires_password_change"] = o.RequiresPasswordChange
	toSerialize["pac_user_id"] = o.PacUserId
	toSerialize["pac_primary_group_id"] = o.PacPrimaryGroupId
	toSerialize["pac_group_ids"] = o.PacGroupIds
	toSerialize["pac_name"] = o.PacName
	toSerialize["pac_upn"] = o.PacUpn
	toSerialize["password_expiration"] = o.PasswordExpiration.Get()
	toSerialize["flags"] = o.Flags

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosUserKeyOutpost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"enabled",
		"principal",
		"kvno",
		"salt",
		"keys",
		"max_ticket_lifetime",
		"max_renew_lifetime",
		"requires_password_change",
		"pac_user_id",
		"pac_primary_group_id",
		"pac_group_ids",
		"pac_name",
		"pac_upn",
		"password_expiration",
		"flags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosUserKeyOutpost := _KerberosUserKeyOutpost{}

	err = json.Unmarshal(data, &varKerberosUserKeyOutpost)

	if err != nil {
		return err
	}

	*o = KerberosUserKeyOutpost(varKerberosUserKeyOutpost)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "principal")
		delete(additionalProperties, "kvno")
		delete(additionalProperties, "salt")
		delete(additionalProperties, "keys")
		delete(additionalProperties, "max_ticket_lifetime")
		delete(additionalProperties, "max_renew_lifetime")
		delete(additionalProperties, "requires_password_change")
		delete(additionalProperties, "pac_user_id")
		delete(additionalProperties, "pac_primary_group_id")
		delete(additionalProperties, "pac_group_ids")
		delete(additionalProperties, "pac_name")
		delete(additionalProperties, "pac_upn")
		delete(additionalProperties, "password_expiration")
		delete(additionalProperties, "flags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosUserKeyOutpost struct {
	value *KerberosUserKeyOutpost
	isSet bool
}

func (v NullableKerberosUserKeyOutpost) Get() *KerberosUserKeyOutpost {
	return v.value
}

func (v *NullableKerberosUserKeyOutpost) Set(val *KerberosUserKeyOutpost) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosUserKeyOutpost) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosUserKeyOutpost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosUserKeyOutpost(val *KerberosUserKeyOutpost) *NullableKerberosUserKeyOutpost {
	return &NullableKerberosUserKeyOutpost{value: val, isSet: true}
}

func (v NullableKerberosUserKeyOutpost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosUserKeyOutpost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
