/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosOutpostConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosOutpostConfig{}

// KerberosOutpostConfig Kerberos provider serializer for outposts.
type KerberosOutpostConfig struct {
	Pk                         int32                 `json:"pk"`
	Name                       string                `json:"name"`
	RealmName                  string                `json:"realm_name"`
	MaximumTicketLifetime      int32                 `json:"maximum_ticket_lifetime"`
	MaximumTicketRenewLifetime int32                 `json:"maximum_ticket_renew_lifetime"`
	AllowedEnctypes            []AllowedEnctypesEnum `json:"allowed_enctypes,omitempty"`
	MasterKey                  *string               `json:"master_key,omitempty"`
	ApplicationSlug            string                `json:"application_slug"`
	AdditionalProperties       map[string]interface{}
}

type _KerberosOutpostConfig KerberosOutpostConfig

// NewKerberosOutpostConfig instantiates a new KerberosOutpostConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosOutpostConfig(pk int32, name string, realmName string, maximumTicketLifetime int32, maximumTicketRenewLifetime int32, applicationSlug string) *KerberosOutpostConfig {
	this := KerberosOutpostConfig{}
	this.Pk = pk
	this.Name = name
	this.RealmName = realmName
	this.MaximumTicketLifetime = maximumTicketLifetime
	this.MaximumTicketRenewLifetime = maximumTicketRenewLifetime
	this.ApplicationSlug = applicationSlug
	return &this
}

// NewKerberosOutpostConfigWithDefaults instantiates a new KerberosOutpostConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosOutpostConfigWithDefaults() *KerberosOutpostConfig {
	this := KerberosOutpostConfig{}
	return &this
}

// GetPk returns the Pk field value
func (o *KerberosOutpostConfig) GetPk() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pk
}

// GetPkOk returns a tuple with the Pk field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetPkOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pk, true
}

// SetPk sets field value
func (o *KerberosOutpostConfig) SetPk(v int32) {
	o.Pk = v
}

// GetName returns the Name field value
func (o *KerberosOutpostConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KerberosOutpostConfig) SetName(v string) {
	o.Name = v
}

// GetRealmName returns the RealmName field value
func (o *KerberosOutpostConfig) GetRealmName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RealmName
}

// GetRealmNameOk returns a tuple with the RealmName field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetRealmNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RealmName, true
}

// SetRealmName sets field value
func (o *KerberosOutpostConfig) SetRealmName(v string) {
	o.RealmName = v
}

// GetMaximumTicketLifetime returns the MaximumTicketLifetime field value
func (o *KerberosOutpostConfig) GetMaximumTicketLifetime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaximumTicketLifetime
}

// GetMaximumTicketLifetimeOk returns a tuple with the MaximumTicketLifetime field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMaximumTicketLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaximumTicketLifetime, true
}

// SetMaximumTicketLifetime sets field value
func (o *KerberosOutpostConfig) SetMaximumTicketLifetime(v int32) {
	o.MaximumTicketLifetime = v
}

// GetMaximumTicketRenewLifetime returns the MaximumTicketRenewLifetime field value
func (o *KerberosOutpostConfig) GetMaximumTicketRenewLifetime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaximumTicketRenewLifetime
}

// GetMaximumTicketRenewLifetimeOk returns a tuple with the MaximumTicketRenewLifetime field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMaximumTicketRenewLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaximumTicketRenewLifetime, true
}

// SetMaximumTicketRenewLifetime sets field value
func (o *KerberosOutpostConfig) SetMaximumTicketRenewLifetime(v int32) {
	o.MaximumTicketRenewLifetime = v
}

// GetAllowedEnctypes returns the AllowedEnctypes field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetAllowedEnctypes() []AllowedEnctypesEnum {
	if o == nil || IsNil(o.AllowedEnctypes) {
		var ret []AllowedEnctypesEnum
		return ret
	}
	return o.AllowedEnctypes
}

// GetAllowedEnctypesOk returns a tuple with the AllowedEnctypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetAllowedEnctypesOk() ([]AllowedEnctypesEnum, bool) {
	if o == nil || IsNil(o.AllowedEnctypes) {
		return nil, false
	}
	return o.AllowedEnctypes, true
}

// HasAllowedEnctypes returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasAllowedEnctypes() bool {
	if o != nil && !IsNil(o.AllowedEnctypes) {
		return true
	}

	return false
}

// SetAllowedEnctypes gets a reference to the given []AllowedEnctypesEnum and assigns it to the AllowedEnctypes field.
func (o *KerberosOutpostConfig) SetAllowedEnctypes(v []AllowedEnctypesEnum) {
	o.AllowedEnctypes = v
}

// GetMasterKey returns the MasterKey field value if set, zero value otherwise.
func (o *KerberosOutpostConfig) GetMasterKey() string {
	if o == nil || IsNil(o.MasterKey) {
		var ret string
		return ret
	}
	return *o.MasterKey
}

// GetMasterKeyOk returns a tuple with the MasterKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetMasterKeyOk() (*string, bool) {
	if o == nil || IsNil(o.MasterKey) {
		return nil, false
	}
	return o.MasterKey, true
}

// HasMasterKey returns a boolean if a field has been set.
func (o *KerberosOutpostConfig) HasMasterKey() bool {
	if o != nil && !IsNil(o.MasterKey) {
		return true
	}

	return false
}

// SetMasterKey gets a reference to the given string and assigns it to the MasterKey field.
func (o *KerberosOutpostConfig) SetMasterKey(v string) {
	o.MasterKey = &v
}

// GetApplicationSlug returns the ApplicationSlug field value
func (o *KerberosOutpostConfig) GetApplicationSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationSlug
}

// GetApplicationSlugOk returns a tuple with the ApplicationSlug field value
// and a boolean to check if the value has been set.
func (o *KerberosOutpostConfig) GetApplicationSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationSlug, true
}

// SetApplicationSlug sets field value
func (o *KerberosOutpostConfig) SetApplicationSlug(v string) {
	o.ApplicationSlug = v
}

func (o KerberosOutpostConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosOutpostConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pk"] = o.Pk
	toSerialize["name"] = o.Name
	toSerialize["realm_name"] = o.RealmName
	toSerialize["maximum_ticket_lifetime"] = o.MaximumTicketLifetime
	toSerialize["maximum_ticket_renew_lifetime"] = o.MaximumTicketRenewLifetime
	if !IsNil(o.AllowedEnctypes) {
		toSerialize["allowed_enctypes"] = o.AllowedEnctypes
	}
	if !IsNil(o.MasterKey) {
		toSerialize["master_key"] = o.MasterKey
	}
	toSerialize["application_slug"] = o.ApplicationSlug

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosOutpostConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pk",
		"name",
		"realm_name",
		"maximum_ticket_lifetime",
		"maximum_ticket_renew_lifetime",
		"application_slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosOutpostConfig := _KerberosOutpostConfig{}

	err = json.Unmarshal(data, &varKerberosOutpostConfig)

	if err != nil {
		return err
	}

	*o = KerberosOutpostConfig(varKerberosOutpostConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pk")
		delete(additionalProperties, "name")
		delete(additionalProperties, "realm_name")
		delete(additionalProperties, "maximum_ticket_lifetime")
		delete(additionalProperties, "maximum_ticket_renew_lifetime")
		delete(additionalProperties, "allowed_enctypes")
		delete(additionalProperties, "master_key")
		delete(additionalProperties, "application_slug")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosOutpostConfig struct {
	value *KerberosOutpostConfig
	isSet bool
}

func (v NullableKerberosOutpostConfig) Get() *KerberosOutpostConfig {
	return v.value
}

func (v *NullableKerberosOutpostConfig) Set(val *KerberosOutpostConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosOutpostConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosOutpostConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosOutpostConfig(val *KerberosOutpostConfig) *NullableKerberosOutpostConfig {
	return &NullableKerberosOutpostConfig{value: val, isSet: true}
}

func (v NullableKerberosOutpostConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosOutpostConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
