/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosSetPasswordRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosSetPasswordRequest{}

// KerberosSetPasswordRequest Password change request for the Kerberos outpost.
type KerberosSetPasswordRequest struct {
	Username             string `json:"username"`
	Password             string `json:"password"`
	AdditionalProperties map[string]interface{}
}

type _KerberosSetPasswordRequest KerberosSetPasswordRequest

// NewKerberosSetPasswordRequest instantiates a new KerberosSetPasswordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosSetPasswordRequest(username string, password string) *KerberosSetPasswordRequest {
	this := KerberosSetPasswordRequest{}
	this.Username = username
	this.Password = password
	return &this
}

// NewKerberosSetPasswordRequestWithDefaults instantiates a new KerberosSetPasswordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosSetPasswordRequestWithDefaults() *KerberosSetPasswordRequest {
	this := KerberosSetPasswordRequest{}
	return &this
}

// GetUsername returns the Username field value
func (o *KerberosSetPasswordRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *KerberosSetPasswordRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *KerberosSetPasswordRequest) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *KerberosSetPasswordRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *KerberosSetPasswordRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *KerberosSetPasswordRequest) SetPassword(v string) {
	o.Password = v
}

func (o KerberosSetPasswordRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosSetPasswordRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosSetPasswordRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosSetPasswordRequest := _KerberosSetPasswordRequest{}

	err = json.Unmarshal(data, &varKerberosSetPasswordRequest)

	if err != nil {
		return err
	}

	*o = KerberosSetPasswordRequest(varKerberosSetPasswordRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosSetPasswordRequest struct {
	value *KerberosSetPasswordRequest
	isSet bool
}

func (v NullableKerberosSetPasswordRequest) Get() *KerberosSetPasswordRequest {
	return v.value
}

func (v *NullableKerberosSetPasswordRequest) Set(val *KerberosSetPasswordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosSetPasswordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosSetPasswordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosSetPasswordRequest(val *KerberosSetPasswordRequest) *NullableKerberosSetPasswordRequest {
	return &NullableKerberosSetPasswordRequest{value: val, isSet: true}
}

func (v NullableKerberosSetPasswordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosSetPasswordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
