/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedKerberosUserKeyOutpostList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedKerberosUserKeyOutpostList{}

// PaginatedKerberosUserKeyOutpostList struct for PaginatedKerberosUserKeyOutpostList
type PaginatedKerberosUserKeyOutpostList struct {
	Pagination           Pagination               `json:"pagination"`
	Results              []KerberosUserKeyOutpost `json:"results"`
	Autocomplete         map[string]interface{}   `json:"autocomplete"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedKerberosUserKeyOutpostList PaginatedKerberosUserKeyOutpostList

// NewPaginatedKerberosUserKeyOutpostList instantiates a new PaginatedKerberosUserKeyOutpostList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedKerberosUserKeyOutpostList(pagination Pagination, results []KerberosUserKeyOutpost, autocomplete map[string]interface{}) *PaginatedKerberosUserKeyOutpostList {
	this := PaginatedKerberosUserKeyOutpostList{}
	this.Pagination = pagination
	this.Results = results
	this.Autocomplete = autocomplete
	return &this
}

// NewPaginatedKerberosUserKeyOutpostListWithDefaults instantiates a new PaginatedKerberosUserKeyOutpostList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedKerberosUserKeyOutpostListWithDefaults() *PaginatedKerberosUserKeyOutpostList {
	this := PaginatedKerberosUserKeyOutpostList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedKerberosUserKeyOutpostList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedKerberosUserKeyOutpostList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedKerberosUserKeyOutpostList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedKerberosUserKeyOutpostList) GetResults() []KerberosUserKeyOutpost {
	if o == nil {
		var ret []KerberosUserKeyOutpost
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedKerberosUserKeyOutpostList) GetResultsOk() ([]KerberosUserKeyOutpost, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedKerberosUserKeyOutpostList) SetResults(v []KerberosUserKeyOutpost) {
	o.Results = v
}

// GetAutocomplete returns the Autocomplete field value
func (o *PaginatedKerberosUserKeyOutpostList) GetAutocomplete() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Autocomplete
}

// GetAutocompleteOk returns a tuple with the Autocomplete field value
// and a boolean to check if the value has been set.
func (o *PaginatedKerberosUserKeyOutpostList) GetAutocompleteOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Autocomplete, true
}

// SetAutocomplete sets field value
func (o *PaginatedKerberosUserKeyOutpostList) SetAutocomplete(v map[string]interface{}) {
	o.Autocomplete = v
}

func (o PaginatedKerberosUserKeyOutpostList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedKerberosUserKeyOutpostList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["results"] = o.Results
	toSerialize["autocomplete"] = o.Autocomplete

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedKerberosUserKeyOutpostList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"results",
		"autocomplete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedKerberosUserKeyOutpostList := _PaginatedKerberosUserKeyOutpostList{}

	err = json.Unmarshal(data, &varPaginatedKerberosUserKeyOutpostList)

	if err != nil {
		return err
	}

	*o = PaginatedKerberosUserKeyOutpostList(varPaginatedKerberosUserKeyOutpostList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "results")
		delete(additionalProperties, "autocomplete")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedKerberosUserKeyOutpostList struct {
	value *PaginatedKerberosUserKeyOutpostList
	isSet bool
}

func (v NullablePaginatedKerberosUserKeyOutpostList) Get() *PaginatedKerberosUserKeyOutpostList {
	return v.value
}

func (v *NullablePaginatedKerberosUserKeyOutpostList) Set(val *PaginatedKerberosUserKeyOutpostList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedKerberosUserKeyOutpostList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedKerberosUserKeyOutpostList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedKerberosUserKeyOutpostList(val *PaginatedKerberosUserKeyOutpostList) *NullablePaginatedKerberosUserKeyOutpostList {
	return &NullablePaginatedKerberosUserKeyOutpostList{value: val, isSet: true}
}

func (v NullablePaginatedKerberosUserKeyOutpostList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedKerberosUserKeyOutpostList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
