/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedKerberosOutpostConfigList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedKerberosOutpostConfigList{}

// PaginatedKerberosOutpostConfigList struct for PaginatedKerberosOutpostConfigList
type PaginatedKerberosOutpostConfigList struct {
	Pagination           Pagination              `json:"pagination"`
	Results              []KerberosOutpostConfig `json:"results"`
	Autocomplete         map[string]interface{}  `json:"autocomplete"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedKerberosOutpostConfigList PaginatedKerberosOutpostConfigList

// NewPaginatedKerberosOutpostConfigList instantiates a new PaginatedKerberosOutpostConfigList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedKerberosOutpostConfigList(pagination Pagination, results []KerberosOutpostConfig, autocomplete map[string]interface{}) *PaginatedKerberosOutpostConfigList {
	this := PaginatedKerberosOutpostConfigList{}
	this.Pagination = pagination
	this.Results = results
	this.Autocomplete = autocomplete
	return &this
}

// NewPaginatedKerberosOutpostConfigListWithDefaults instantiates a new PaginatedKerberosOutpostConfigList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedKerberosOutpostConfigListWithDefaults() *PaginatedKerberosOutpostConfigList {
	this := PaginatedKerberosOutpostConfigList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedKerberosOutpostConfigList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedKerberosOutpostConfigList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedKerberosOutpostConfigList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedKerberosOutpostConfigList) GetResults() []KerberosOutpostConfig {
	if o == nil {
		var ret []KerberosOutpostConfig
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedKerberosOutpostConfigList) GetResultsOk() ([]KerberosOutpostConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedKerberosOutpostConfigList) SetResults(v []KerberosOutpostConfig) {
	o.Results = v
}

// GetAutocomplete returns the Autocomplete field value
func (o *PaginatedKerberosOutpostConfigList) GetAutocomplete() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Autocomplete
}

// GetAutocompleteOk returns a tuple with the Autocomplete field value
// and a boolean to check if the value has been set.
func (o *PaginatedKerberosOutpostConfigList) GetAutocompleteOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Autocomplete, true
}

// SetAutocomplete sets field value
func (o *PaginatedKerberosOutpostConfigList) SetAutocomplete(v map[string]interface{}) {
	o.Autocomplete = v
}

func (o PaginatedKerberosOutpostConfigList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedKerberosOutpostConfigList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["results"] = o.Results
	toSerialize["autocomplete"] = o.Autocomplete

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedKerberosOutpostConfigList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"results",
		"autocomplete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedKerberosOutpostConfigList := _PaginatedKerberosOutpostConfigList{}

	err = json.Unmarshal(data, &varPaginatedKerberosOutpostConfigList)

	if err != nil {
		return err
	}

	*o = PaginatedKerberosOutpostConfigList(varPaginatedKerberosOutpostConfigList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "results")
		delete(additionalProperties, "autocomplete")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedKerberosOutpostConfigList struct {
	value *PaginatedKerberosOutpostConfigList
	isSet bool
}

func (v NullablePaginatedKerberosOutpostConfigList) Get() *PaginatedKerberosOutpostConfigList {
	return v.value
}

func (v *NullablePaginatedKerberosOutpostConfigList) Set(val *PaginatedKerberosOutpostConfigList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedKerberosOutpostConfigList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedKerberosOutpostConfigList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedKerberosOutpostConfigList(val *PaginatedKerberosOutpostConfigList) *NullablePaginatedKerberosOutpostConfigList {
	return &NullablePaginatedKerberosOutpostConfigList{value: val, isSet: true}
}

func (v NullablePaginatedKerberosOutpostConfigList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedKerberosOutpostConfigList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
