/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the KerberosPasswordPolicyError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosPasswordPolicyError{}

// KerberosPasswordPolicyError Password policy failure returned by the Kerberos outpost.
type KerberosPasswordPolicyError struct {
	Messages             []string `json:"messages"`
	AdditionalProperties map[string]interface{}
}

type _KerberosPasswordPolicyError KerberosPasswordPolicyError

// NewKerberosPasswordPolicyError instantiates a new KerberosPasswordPolicyError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosPasswordPolicyError(messages []string) *KerberosPasswordPolicyError {
	this := KerberosPasswordPolicyError{}
	this.Messages = messages
	return &this
}

// NewKerberosPasswordPolicyErrorWithDefaults instantiates a new KerberosPasswordPolicyError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosPasswordPolicyErrorWithDefaults() *KerberosPasswordPolicyError {
	this := KerberosPasswordPolicyError{}
	return &this
}

// GetMessages returns the Messages field value
func (o *KerberosPasswordPolicyError) GetMessages() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *KerberosPasswordPolicyError) GetMessagesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *KerberosPasswordPolicyError) SetMessages(v []string) {
	o.Messages = v
}

func (o KerberosPasswordPolicyError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosPasswordPolicyError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messages"] = o.Messages

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KerberosPasswordPolicyError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKerberosPasswordPolicyError := _KerberosPasswordPolicyError{}

	err = json.Unmarshal(data, &varKerberosPasswordPolicyError)

	if err != nil {
		return err
	}

	*o = KerberosPasswordPolicyError(varKerberosPasswordPolicyError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "messages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKerberosPasswordPolicyError struct {
	value *KerberosPasswordPolicyError
	isSet bool
}

func (v NullableKerberosPasswordPolicyError) Get() *KerberosPasswordPolicyError {
	return v.value
}

func (v *NullableKerberosPasswordPolicyError) Set(val *KerberosPasswordPolicyError) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosPasswordPolicyError) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosPasswordPolicyError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosPasswordPolicyError(val *KerberosPasswordPolicyError) *NullableKerberosPasswordPolicyError {
	return &NullableKerberosPasswordPolicyError{value: val, isSet: true}
}

func (v NullableKerberosPasswordPolicyError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosPasswordPolicyError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
