/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const AllowedEnctypesEnum = {
    NUMBER_17: 17,
    NUMBER_18: 18,
    NUMBER_19: 19,
    NUMBER_20: 20,
    NUMBER_unknown_default_open_api: 11184809,
} as const;
export type AllowedEnctypesEnum = (typeof AllowedEnctypesEnum)[keyof typeof AllowedEnctypesEnum];

export function instanceOfAllowedEnctypesEnum(value: any): boolean {
    for (const key in AllowedEnctypesEnum) {
        if (Object.prototype.hasOwnProperty.call(AllowedEnctypesEnum, key)) {
            if (AllowedEnctypesEnum[key as keyof typeof AllowedEnctypesEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AllowedEnctypesEnumFromJSON(json: any): AllowedEnctypesEnum {
    return AllowedEnctypesEnumFromJSONTyped(json, false);
}

export function AllowedEnctypesEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AllowedEnctypesEnum {
    return json as AllowedEnctypesEnum;
}

export function AllowedEnctypesEnumToJSON(value?: AllowedEnctypesEnum | null): any {
    return value as any;
}

export function AllowedEnctypesEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): AllowedEnctypesEnum {
    return value as AllowedEnctypesEnum;
}
