/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const EventEnum = {
    AsReq: "as_req",
    TgsReq: "tgs_req",
    S4u2self: "s4u2self",
    S4u2proxy: "s4u2proxy",
    U2u: "u2u",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type EventEnum = (typeof EventEnum)[keyof typeof EventEnum];

export function instanceOfEventEnum(value: any): boolean {
    for (const key in EventEnum) {
        if (Object.prototype.hasOwnProperty.call(EventEnum, key)) {
            if (EventEnum[key as keyof typeof EventEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EventEnumFromJSON(json: any): EventEnum {
    return EventEnumFromJSONTyped(json, false);
}

export function EventEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventEnum {
    return json as EventEnum;
}

export function EventEnumToJSON(value?: EventEnum | null): any {
    return value as any;
}

export function EventEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): EventEnum {
    return value as EventEnum;
}
