/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EventEnum } from "./EventEnum";
import { EventEnumFromJSON, EventEnumToJSON } from "./EventEnum";

/**
 * KDC audit event data submitted by the Kerberos outpost.
 * @export
 * @interface KerberosAuditEventRequest
 */
export interface KerberosAuditEventRequest {
    /**
     *
     * @type {EventEnum}
     * @memberof KerberosAuditEventRequest
     */
    event: EventEnum;
    /**
     *
     * @type {boolean}
     * @memberof KerberosAuditEventRequest
     */
    success: boolean;
    /**
     *
     * @type {string}
     * @memberof KerberosAuditEventRequest
     */
    client: string;
    /**
     *
     * @type {string}
     * @memberof KerberosAuditEventRequest
     */
    service: string;
    /**
     *
     * @type {string}
     * @memberof KerberosAuditEventRequest
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof KerberosAuditEventRequest
     */
    preauthType: string;
    /**
     *
     * @type {string}
     * @memberof KerberosAuditEventRequest
     */
    remoteAddr: string;
    /**
     *
     * @type {string}
     * @memberof KerberosAuditEventRequest
     */
    s4u2selfUser: string;
    /**
     *
     * @type {Array<string>}
     * @memberof KerberosAuditEventRequest
     */
    authIndicators: Array<string>;
    /**
     *
     * @type {number}
     * @memberof KerberosAuditEventRequest
     */
    errorCode: number;
    /**
     *
     * @type {string}
     * @memberof KerberosAuditEventRequest
     */
    requestId: string;
    /**
     *
     * @type {string}
     * @memberof KerberosAuditEventRequest
     */
    ticketId: string;
}

/**
 * Check if a given object implements the KerberosAuditEventRequest interface.
 */
export function instanceOfKerberosAuditEventRequest(
    value: object,
): value is KerberosAuditEventRequest {
    if (!("event" in value) || value["event"] === undefined) return false;
    if (!("success" in value) || value["success"] === undefined) return false;
    if (!("client" in value) || value["client"] === undefined) return false;
    if (!("service" in value) || value["service"] === undefined) return false;
    if (!("status" in value) || value["status"] === undefined) return false;
    if (
        (!("preauthType" in (value as Record<string, any>)) &&
            !("preauth_type" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["preauthType"] === undefined &&
            (value as Record<string, any>)["preauth_type"] === undefined)
    )
        return false;
    if (
        (!("remoteAddr" in (value as Record<string, any>)) &&
            !("remote_addr" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["remoteAddr"] === undefined &&
            (value as Record<string, any>)["remote_addr"] === undefined)
    )
        return false;
    if (
        (!("s4u2selfUser" in (value as Record<string, any>)) &&
            !("s4u2self_user" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["s4u2selfUser"] === undefined &&
            (value as Record<string, any>)["s4u2self_user"] === undefined)
    )
        return false;
    if (
        (!("authIndicators" in (value as Record<string, any>)) &&
            !("auth_indicators" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["authIndicators"] === undefined &&
            (value as Record<string, any>)["auth_indicators"] === undefined)
    )
        return false;
    if (
        (!("errorCode" in (value as Record<string, any>)) &&
            !("error_code" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["errorCode"] === undefined &&
            (value as Record<string, any>)["error_code"] === undefined)
    )
        return false;
    if (
        (!("requestId" in (value as Record<string, any>)) &&
            !("request_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["requestId"] === undefined &&
            (value as Record<string, any>)["request_id"] === undefined)
    )
        return false;
    if (
        (!("ticketId" in (value as Record<string, any>)) &&
            !("ticket_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["ticketId"] === undefined &&
            (value as Record<string, any>)["ticket_id"] === undefined)
    )
        return false;
    return true;
}

export function KerberosAuditEventRequestFromJSON(json: any): KerberosAuditEventRequest {
    return KerberosAuditEventRequestFromJSONTyped(json, false);
}

export function KerberosAuditEventRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosAuditEventRequest {
    if (json == null) {
        return json;
    }
    return {
        event: EventEnumFromJSON(json["event"]),
        success: json["success"],
        client: json["client"],
        service: json["service"],
        status: json["status"],
        preauthType: json["preauth_type"],
        remoteAddr: json["remote_addr"],
        s4u2selfUser: json["s4u2self_user"],
        authIndicators: json["auth_indicators"],
        errorCode: json["error_code"],
        requestId: json["request_id"],
        ticketId: json["ticket_id"],
    };
}

export function KerberosAuditEventRequestToJSON(json: any): KerberosAuditEventRequest {
    return KerberosAuditEventRequestToJSONTyped(json, false);
}

export function KerberosAuditEventRequestToJSONTyped(
    value?: KerberosAuditEventRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        event: EventEnumToJSON(value["event"]),
        success: value["success"],
        client: value["client"],
        service: value["service"],
        status: value["status"],
        preauth_type: value["preauthType"],
        remote_addr: value["remoteAddr"],
        s4u2self_user: value["s4u2selfUser"],
        auth_indicators: value["authIndicators"],
        error_code: value["errorCode"],
        request_id: value["requestId"],
        ticket_id: value["ticketId"],
    };
}
