/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Password change request for the Kerberos outpost.
 * @export
 * @interface KerberosSetPasswordRequest
 */
export interface KerberosSetPasswordRequest {
    /**
     *
     * @type {string}
     * @memberof KerberosSetPasswordRequest
     */
    username: string;
    /**
     *
     * @type {string}
     * @memberof KerberosSetPasswordRequest
     */
    password: string;
}

/**
 * Check if a given object implements the KerberosSetPasswordRequest interface.
 */
export function instanceOfKerberosSetPasswordRequest(
    value: object,
): value is KerberosSetPasswordRequest {
    if (!("username" in value) || value["username"] === undefined) return false;
    if (!("password" in value) || value["password"] === undefined) return false;
    return true;
}

export function KerberosSetPasswordRequestFromJSON(json: any): KerberosSetPasswordRequest {
    return KerberosSetPasswordRequestFromJSONTyped(json, false);
}

export function KerberosSetPasswordRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosSetPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        username: json["username"],
        password: json["password"],
    };
}

export function KerberosSetPasswordRequestToJSON(json: any): KerberosSetPasswordRequest {
    return KerberosSetPasswordRequestToJSONTyped(json, false);
}

export function KerberosSetPasswordRequestToJSONTyped(
    value?: KerberosSetPasswordRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        username: value["username"],
        password: value["password"],
    };
}
