/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TicketFlagsEnum } from "./TicketFlagsEnum";
import { TicketFlagsEnumFromJSON, TicketFlagsEnumToJSON } from "./TicketFlagsEnum";

/**
 * Service principal ticket flag update request for the kadm5 outpost.
 * @export
 * @interface KerberosServicePrincipalUpdateRequest
 */
export interface KerberosServicePrincipalUpdateRequest {
    /**
     *
     * @type {string}
     * @memberof KerberosServicePrincipalUpdateRequest
     */
    spn: string;
    /**
     *
     * @type {Array<TicketFlagsEnum>}
     * @memberof KerberosServicePrincipalUpdateRequest
     */
    ticketFlags: Array<TicketFlagsEnum>;
}

/**
 * Check if a given object implements the KerberosServicePrincipalUpdateRequest interface.
 */
export function instanceOfKerberosServicePrincipalUpdateRequest(
    value: object,
): value is KerberosServicePrincipalUpdateRequest {
    if (!("spn" in value) || value["spn"] === undefined) return false;
    if (
        (!("ticketFlags" in (value as Record<string, any>)) &&
            !("ticket_flags" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["ticketFlags"] === undefined &&
            (value as Record<string, any>)["ticket_flags"] === undefined)
    )
        return false;
    return true;
}

export function KerberosServicePrincipalUpdateRequestFromJSON(
    json: any,
): KerberosServicePrincipalUpdateRequest {
    return KerberosServicePrincipalUpdateRequestFromJSONTyped(json, false);
}

export function KerberosServicePrincipalUpdateRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosServicePrincipalUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        spn: json["spn"],
        ticketFlags: (json["ticket_flags"] as Array<any>).map(TicketFlagsEnumFromJSON),
    };
}

export function KerberosServicePrincipalUpdateRequestToJSON(
    json: any,
): KerberosServicePrincipalUpdateRequest {
    return KerberosServicePrincipalUpdateRequestToJSONTyped(json, false);
}

export function KerberosServicePrincipalUpdateRequestToJSONTyped(
    value?: KerberosServicePrincipalUpdateRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        spn: value["spn"],
        ticket_flags: (value["ticketFlags"] as Array<any>).map(TicketFlagsEnumToJSON),
    };
}
