/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * User key data consumed by the KDC outpost.
 * @export
 * @interface KerberosUserKeyOutpost
 */
export interface KerberosUserKeyOutpost {
    /**
     *
     * @type {string}
     * @memberof KerberosUserKeyOutpost
     */
    username: string;
    /**
     *
     * @type {string}
     * @memberof KerberosUserKeyOutpost
     */
    readonly principal: string;
    /**
     *
     * @type {number}
     * @memberof KerberosUserKeyOutpost
     */
    kvno: number;
    /**
     *
     * @type {string}
     * @memberof KerberosUserKeyOutpost
     */
    salt: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof KerberosUserKeyOutpost
     */
    readonly keys: { [key: string]: any };
}

/**
 * Check if a given object implements the KerberosUserKeyOutpost interface.
 */
export function instanceOfKerberosUserKeyOutpost(value: object): value is KerberosUserKeyOutpost {
    if (!("username" in value) || value["username"] === undefined) return false;
    if (!("principal" in value) || value["principal"] === undefined) return false;
    if (!("kvno" in value) || value["kvno"] === undefined) return false;
    if (!("salt" in value) || value["salt"] === undefined) return false;
    if (!("keys" in value) || value["keys"] === undefined) return false;
    return true;
}

export function KerberosUserKeyOutpostFromJSON(json: any): KerberosUserKeyOutpost {
    return KerberosUserKeyOutpostFromJSONTyped(json, false);
}

export function KerberosUserKeyOutpostFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosUserKeyOutpost {
    if (json == null) {
        return json;
    }
    return {
        username: json["username"],
        principal: json["principal"],
        kvno: json["kvno"],
        salt: json["salt"],
        keys: json["keys"],
    };
}

export function KerberosUserKeyOutpostToJSON(json: any): KerberosUserKeyOutpost {
    return KerberosUserKeyOutpostToJSONTyped(json, false);
}

export function KerberosUserKeyOutpostToJSONTyped(
    value?: Omit<KerberosUserKeyOutpost, "principal" | "keys"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        username: value["username"],
        kvno: value["kvno"],
        salt: value["salt"],
    };
}
