/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Password policy failure returned by the Kerberos outpost.
 * @export
 * @interface KerberosPasswordPolicyError
 */
export interface KerberosPasswordPolicyError {
    /**
     *
     * @type {Array<string>}
     * @memberof KerberosPasswordPolicyError
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the KerberosPasswordPolicyError interface.
 */
export function instanceOfKerberosPasswordPolicyError(
    value: object,
): value is KerberosPasswordPolicyError {
    if (!("messages" in value) || value["messages"] === undefined) return false;
    return true;
}

export function KerberosPasswordPolicyErrorFromJSON(json: any): KerberosPasswordPolicyError {
    return KerberosPasswordPolicyErrorFromJSONTyped(json, false);
}

export function KerberosPasswordPolicyErrorFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosPasswordPolicyError {
    if (json == null) {
        return json;
    }
    return {
        messages: json["messages"],
    };
}

export function KerberosPasswordPolicyErrorToJSON(json: any): KerberosPasswordPolicyError {
    return KerberosPasswordPolicyErrorToJSONTyped(json, false);
}

export function KerberosPasswordPolicyErrorToJSONTyped(
    value?: KerberosPasswordPolicyError | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        messages: value["messages"],
    };
}
