/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Realm trust data consumed by the KDC outpost.
 * @export
 * @interface KerberosRealmTrustOutpost
 */
export interface KerberosRealmTrustOutpost {
    /**
     *
     * @type {string}
     * @memberof KerberosRealmTrustOutpost
     */
    remoteRealm: string;
    /**
     *
     * @type {Array<string>}
     * @memberof KerberosRealmTrustOutpost
     */
    capaths: Array<string>;
    /**
     *
     * @type {number}
     * @memberof KerberosRealmTrustOutpost
     */
    outgoingKvno: number;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof KerberosRealmTrustOutpost
     */
    readonly outgoingKeys: { [key: string]: any };
    /**
     *
     * @type {number}
     * @memberof KerberosRealmTrustOutpost
     */
    incomingKvno: number;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof KerberosRealmTrustOutpost
     */
    readonly incomingKeys: { [key: string]: any };
}

/**
 * Check if a given object implements the KerberosRealmTrustOutpost interface.
 */
export function instanceOfKerberosRealmTrustOutpost(
    value: object,
): value is KerberosRealmTrustOutpost {
    if (
        (!("remoteRealm" in (value as Record<string, any>)) &&
            !("remote_realm" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["remoteRealm"] === undefined &&
            (value as Record<string, any>)["remote_realm"] === undefined)
    )
        return false;
    if (!("capaths" in value) || value["capaths"] === undefined) return false;
    if (
        (!("outgoingKvno" in (value as Record<string, any>)) &&
            !("outgoing_kvno" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["outgoingKvno"] === undefined &&
            (value as Record<string, any>)["outgoing_kvno"] === undefined)
    )
        return false;
    if (
        (!("outgoingKeys" in (value as Record<string, any>)) &&
            !("outgoing_keys" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["outgoingKeys"] === undefined &&
            (value as Record<string, any>)["outgoing_keys"] === undefined)
    )
        return false;
    if (
        (!("incomingKvno" in (value as Record<string, any>)) &&
            !("incoming_kvno" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["incomingKvno"] === undefined &&
            (value as Record<string, any>)["incoming_kvno"] === undefined)
    )
        return false;
    if (
        (!("incomingKeys" in (value as Record<string, any>)) &&
            !("incoming_keys" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["incomingKeys"] === undefined &&
            (value as Record<string, any>)["incoming_keys"] === undefined)
    )
        return false;
    return true;
}

export function KerberosRealmTrustOutpostFromJSON(json: any): KerberosRealmTrustOutpost {
    return KerberosRealmTrustOutpostFromJSONTyped(json, false);
}

export function KerberosRealmTrustOutpostFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosRealmTrustOutpost {
    if (json == null) {
        return json;
    }
    return {
        remoteRealm: json["remote_realm"],
        capaths: json["capaths"],
        outgoingKvno: json["outgoing_kvno"],
        outgoingKeys: json["outgoing_keys"],
        incomingKvno: json["incoming_kvno"],
        incomingKeys: json["incoming_keys"],
    };
}

export function KerberosRealmTrustOutpostToJSON(json: any): KerberosRealmTrustOutpost {
    return KerberosRealmTrustOutpostToJSONTyped(json, false);
}

export function KerberosRealmTrustOutpostToJSONTyped(
    value?: Omit<KerberosRealmTrustOutpost, "outgoingKeys" | "incomingKeys"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        remote_realm: value["remoteRealm"],
        capaths: value["capaths"],
        outgoing_kvno: value["outgoingKvno"],
        incoming_kvno: value["incomingKvno"],
    };
}
