/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * OTP validation data consumed by the KDC outpost.
 * @export
 * @interface KerberosOTPCheck
 */
export interface KerberosOTPCheck {
    /**
     *
     * @type {boolean}
     * @memberof KerberosOTPCheck
     */
    allowed: boolean;
}

/**
 * Check if a given object implements the KerberosOTPCheck interface.
 */
export function instanceOfKerberosOTPCheck(value: object): value is KerberosOTPCheck {
    if (!("allowed" in value) || value["allowed"] === undefined) return false;
    return true;
}

export function KerberosOTPCheckFromJSON(json: any): KerberosOTPCheck {
    return KerberosOTPCheckFromJSONTyped(json, false);
}

export function KerberosOTPCheckFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosOTPCheck {
    if (json == null) {
        return json;
    }
    return {
        allowed: json["allowed"],
    };
}

export function KerberosOTPCheckToJSON(json: any): KerberosOTPCheck {
    return KerberosOTPCheckToJSONTyped(json, false);
}

export function KerberosOTPCheckToJSONTyped(
    value?: KerberosOTPCheck | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        allowed: value["allowed"],
    };
}
