/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * OTP validation request submitted by the KDC outpost.
 * @export
 * @interface KerberosOTPCheckRequestRequest
 */
export interface KerberosOTPCheckRequestRequest {
    /**
     *
     * @type {string}
     * @memberof KerberosOTPCheckRequestRequest
     */
    username: string;
    /**
     *
     * @type {string}
     * @memberof KerberosOTPCheckRequestRequest
     */
    value: string;
}

/**
 * Check if a given object implements the KerberosOTPCheckRequestRequest interface.
 */
export function instanceOfKerberosOTPCheckRequestRequest(
    value: object,
): value is KerberosOTPCheckRequestRequest {
    if (!("username" in value) || value["username"] === undefined) return false;
    if (!("value" in value) || value["value"] === undefined) return false;
    return true;
}

export function KerberosOTPCheckRequestRequestFromJSON(json: any): KerberosOTPCheckRequestRequest {
    return KerberosOTPCheckRequestRequestFromJSONTyped(json, false);
}

export function KerberosOTPCheckRequestRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosOTPCheckRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        username: json["username"],
        value: json["value"],
    };
}

export function KerberosOTPCheckRequestRequestToJSON(json: any): KerberosOTPCheckRequestRequest {
    return KerberosOTPCheckRequestRequestToJSONTyped(json, false);
}

export function KerberosOTPCheckRequestRequestToJSONTyped(
    value?: KerberosOTPCheckRequestRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        username: value["username"],
        value: value["value"],
    };
}
