/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Kerberos service principal serializer.
 * @export
 * @interface KerberosServicePrincipal
 */
export interface KerberosServicePrincipal {
    /**
     *
     * @type {string}
     * @memberof KerberosServicePrincipal
     */
    readonly uuid: string;
    /**
     *
     * @type {number}
     * @memberof KerberosServicePrincipal
     */
    provider: number;
    /**
     *
     * @type {string}
     * @memberof KerberosServicePrincipal
     */
    spn: string;
    /**
     *
     * @type {number}
     * @memberof KerberosServicePrincipal
     */
    readonly kvno: number;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof KerberosServicePrincipal
     */
    readonly keys: { [key: string]: any };
}

/**
 * Check if a given object implements the KerberosServicePrincipal interface.
 */
export function instanceOfKerberosServicePrincipal(
    value: object,
): value is KerberosServicePrincipal {
    if (!("uuid" in value) || value["uuid"] === undefined) return false;
    if (!("provider" in value) || value["provider"] === undefined) return false;
    if (!("spn" in value) || value["spn"] === undefined) return false;
    if (!("kvno" in value) || value["kvno"] === undefined) return false;
    if (!("keys" in value) || value["keys"] === undefined) return false;
    return true;
}

export function KerberosServicePrincipalFromJSON(json: any): KerberosServicePrincipal {
    return KerberosServicePrincipalFromJSONTyped(json, false);
}

export function KerberosServicePrincipalFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosServicePrincipal {
    if (json == null) {
        return json;
    }
    return {
        uuid: json["uuid"],
        provider: json["provider"],
        spn: json["spn"],
        kvno: json["kvno"],
        keys: json["keys"],
    };
}

export function KerberosServicePrincipalToJSON(json: any): KerberosServicePrincipal {
    return KerberosServicePrincipalToJSONTyped(json, false);
}

export function KerberosServicePrincipalToJSONTyped(
    value?: Omit<KerberosServicePrincipal, "uuid" | "kvno" | "keys"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        provider: value["provider"],
        spn: value["spn"],
    };
}
