/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Kerberos realm trust serializer.
 * @export
 * @interface KerberosRealmTrustRequest
 */
export interface KerberosRealmTrustRequest {
    /**
     *
     * @type {number}
     * @memberof KerberosRealmTrustRequest
     */
    provider: number;
    /**
     *
     * @type {string}
     * @memberof KerberosRealmTrustRequest
     */
    remoteRealm: string;
    /**
     * Intermediate realms for transited-path checking.
     * @type {Array<string>}
     * @memberof KerberosRealmTrustRequest
     */
    capaths?: Array<string>;
}

/**
 * Check if a given object implements the KerberosRealmTrustRequest interface.
 */
export function instanceOfKerberosRealmTrustRequest(
    value: object,
): value is KerberosRealmTrustRequest {
    if (!("provider" in value) || value["provider"] === undefined) return false;
    if (
        (!("remoteRealm" in (value as Record<string, any>)) &&
            !("remote_realm" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["remoteRealm"] === undefined &&
            (value as Record<string, any>)["remote_realm"] === undefined)
    )
        return false;
    return true;
}

export function KerberosRealmTrustRequestFromJSON(json: any): KerberosRealmTrustRequest {
    return KerberosRealmTrustRequestFromJSONTyped(json, false);
}

export function KerberosRealmTrustRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosRealmTrustRequest {
    if (json == null) {
        return json;
    }
    return {
        provider: json["provider"],
        remoteRealm: json["remote_realm"],
        capaths: json["capaths"] == null ? undefined : json["capaths"],
    };
}

export function KerberosRealmTrustRequestToJSON(json: any): KerberosRealmTrustRequest {
    return KerberosRealmTrustRequestToJSONTyped(json, false);
}

export function KerberosRealmTrustRequestToJSONTyped(
    value?: KerberosRealmTrustRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        provider: value["provider"],
        remote_realm: value["remoteRealm"],
        capaths: value["capaths"],
    };
}
