/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * User key data consumed by the KDC outpost.
 * @export
 * @interface KerberosUserKeyOutpost
 */
export interface KerberosUserKeyOutpost {
    /**
     *
     * @type {string}
     * @memberof KerberosUserKeyOutpost
     */
    username: string;
    /**
     *
     * @type {boolean}
     * @memberof KerberosUserKeyOutpost
     */
    enabled: boolean;
    /**
     *
     * @type {string}
     * @memberof KerberosUserKeyOutpost
     */
    readonly principal: string;
    /**
     *
     * @type {number}
     * @memberof KerberosUserKeyOutpost
     */
    kvno: number;
    /**
     *
     * @type {string}
     * @memberof KerberosUserKeyOutpost
     */
    salt: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof KerberosUserKeyOutpost
     */
    readonly keys: { [key: string]: any };
    /**
     *
     * @type {number}
     * @memberof KerberosUserKeyOutpost
     */
    readonly maxTicketLifetime: number | null;
    /**
     *
     * @type {number}
     * @memberof KerberosUserKeyOutpost
     */
    readonly maxRenewLifetime: number | null;
    /**
     *
     * @type {number}
     * @memberof KerberosUserKeyOutpost
     */
    readonly pacUserId: number;
    /**
     *
     * @type {number}
     * @memberof KerberosUserKeyOutpost
     */
    readonly pacPrimaryGroupId: number;
    /**
     *
     * @type {Array<number>}
     * @memberof KerberosUserKeyOutpost
     */
    readonly pacGroupIds: Array<number>;
    /**
     *
     * @type {string}
     * @memberof KerberosUserKeyOutpost
     */
    pacName: string;
    /**
     *
     * @type {string}
     * @memberof KerberosUserKeyOutpost
     */
    readonly pacUpn: string;
    /**
     *
     * @type {Date}
     * @memberof KerberosUserKeyOutpost
     */
    readonly passwordExpiration: Date | null;
}

/**
 * Check if a given object implements the KerberosUserKeyOutpost interface.
 */
export function instanceOfKerberosUserKeyOutpost(value: object): value is KerberosUserKeyOutpost {
    if (!("username" in value) || value["username"] === undefined) return false;
    if (!("enabled" in value) || value["enabled"] === undefined) return false;
    if (!("principal" in value) || value["principal"] === undefined) return false;
    if (!("kvno" in value) || value["kvno"] === undefined) return false;
    if (!("salt" in value) || value["salt"] === undefined) return false;
    if (!("keys" in value) || value["keys"] === undefined) return false;
    if (
        (!("maxTicketLifetime" in (value as Record<string, any>)) &&
            !("max_ticket_lifetime" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["maxTicketLifetime"] === undefined &&
            (value as Record<string, any>)["max_ticket_lifetime"] === undefined)
    )
        return false;
    if (
        (!("maxRenewLifetime" in (value as Record<string, any>)) &&
            !("max_renew_lifetime" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["maxRenewLifetime"] === undefined &&
            (value as Record<string, any>)["max_renew_lifetime"] === undefined)
    )
        return false;
    if (
        (!("pacUserId" in (value as Record<string, any>)) &&
            !("pac_user_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["pacUserId"] === undefined &&
            (value as Record<string, any>)["pac_user_id"] === undefined)
    )
        return false;
    if (
        (!("pacPrimaryGroupId" in (value as Record<string, any>)) &&
            !("pac_primary_group_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["pacPrimaryGroupId"] === undefined &&
            (value as Record<string, any>)["pac_primary_group_id"] === undefined)
    )
        return false;
    if (
        (!("pacGroupIds" in (value as Record<string, any>)) &&
            !("pac_group_ids" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["pacGroupIds"] === undefined &&
            (value as Record<string, any>)["pac_group_ids"] === undefined)
    )
        return false;
    if (
        (!("pacName" in (value as Record<string, any>)) &&
            !("pac_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["pacName"] === undefined &&
            (value as Record<string, any>)["pac_name"] === undefined)
    )
        return false;
    if (
        (!("pacUpn" in (value as Record<string, any>)) &&
            !("pac_upn" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["pacUpn"] === undefined &&
            (value as Record<string, any>)["pac_upn"] === undefined)
    )
        return false;
    if (
        (!("passwordExpiration" in (value as Record<string, any>)) &&
            !("password_expiration" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["passwordExpiration"] === undefined &&
            (value as Record<string, any>)["password_expiration"] === undefined)
    )
        return false;
    return true;
}

export function KerberosUserKeyOutpostFromJSON(json: any): KerberosUserKeyOutpost {
    return KerberosUserKeyOutpostFromJSONTyped(json, false);
}

export function KerberosUserKeyOutpostFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosUserKeyOutpost {
    if (json == null) {
        return json;
    }
    return {
        username: json["username"],
        enabled: json["enabled"],
        principal: json["principal"],
        kvno: json["kvno"],
        salt: json["salt"],
        keys: json["keys"],
        maxTicketLifetime: json["max_ticket_lifetime"],
        maxRenewLifetime: json["max_renew_lifetime"],
        pacUserId: json["pac_user_id"],
        pacPrimaryGroupId: json["pac_primary_group_id"],
        pacGroupIds: json["pac_group_ids"],
        pacName: json["pac_name"],
        pacUpn: json["pac_upn"],
        passwordExpiration:
            json["password_expiration"] == null ? null : new Date(json["password_expiration"]),
    };
}

export function KerberosUserKeyOutpostToJSON(json: any): KerberosUserKeyOutpost {
    return KerberosUserKeyOutpostToJSONTyped(json, false);
}

export function KerberosUserKeyOutpostToJSONTyped(
    value?: Omit<
        KerberosUserKeyOutpost,
        | "principal"
        | "keys"
        | "maxTicketLifetime"
        | "maxRenewLifetime"
        | "pacUserId"
        | "pacPrimaryGroupId"
        | "pacGroupIds"
        | "pacUpn"
        | "passwordExpiration"
    > | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        username: value["username"],
        enabled: value["enabled"],
        kvno: value["kvno"],
        salt: value["salt"],
        pac_name: value["pacName"],
    };
}
