/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AllowedEnctypesEnum } from "./AllowedEnctypesEnum";
import { AllowedEnctypesEnumFromJSON, AllowedEnctypesEnumToJSON } from "./AllowedEnctypesEnum";
import type { PrincipalUsernameAttributeEnum } from "./PrincipalUsernameAttributeEnum";
import {
    PrincipalUsernameAttributeEnumFromJSON,
    PrincipalUsernameAttributeEnumToJSON,
} from "./PrincipalUsernameAttributeEnum";

/**
 * KerberosProvider serializer.
 * @export
 * @interface KerberosProvider
 */
export interface KerberosProvider {
    /**
     *
     * @type {number}
     * @memberof KerberosProvider
     */
    readonly pk: number;
    /**
     *
     * @type {string}
     * @memberof KerberosProvider
     */
    name: string;
    /**
     * Flow used for authentication when the associated application is accessed by an un-authenticated user.
     * @type {string}
     * @memberof KerberosProvider
     */
    authenticationFlow?: string | null;
    /**
     * Flow used when authorizing this provider.
     * @type {string}
     * @memberof KerberosProvider
     */
    authorizationFlow?: string | null;
    /**
     * Flow used ending the session from a provider.
     * @type {string}
     * @memberof KerberosProvider
     */
    invalidationFlow?: string | null;
    /**
     *
     * @type {Array<string>}
     * @memberof KerberosProvider
     */
    propertyMappings?: Array<string>;
    /**
     * Get object component so that we know how to edit the object
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly component: string;
    /**
     * Internal application name, used in URLs.
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly assignedApplicationSlug: string | null;
    /**
     * Application's display Name.
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly assignedApplicationName: string | null;
    /**
     * Internal application name, used in URLs.
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly assignedBackchannelApplicationSlug: string | null;
    /**
     * Application's display Name.
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly assignedBackchannelApplicationName: string | null;
    /**
     * Return object's verbose_name
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly verboseName: string;
    /**
     * Return object's plural verbose_name
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly verboseNamePlural: string;
    /**
     * Return internal model name
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly metaModelName: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProvider
     */
    realmName: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProvider
     */
    defaultDomain?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProvider
     */
    maximumTicketLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProvider
     */
    maximumTicketRenewLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProvider
     */
    defaultTicketLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProvider
     */
    defaultTicketRenewLifetime?: string;
    /**
     *
     * @type {Array<AllowedEnctypesEnum>}
     * @memberof KerberosProvider
     */
    allowedEnctypes?: Array<AllowedEnctypesEnum>;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProvider
     */
    requirePreauthentication?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProvider
     */
    udpEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProvider
     */
    tcpEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProvider
     */
    forwardable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProvider
     */
    renewable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProvider
     */
    proxiable?: boolean;
    /**
     *
     * @type {PrincipalUsernameAttributeEnum}
     * @memberof KerberosProvider
     */
    principalUsernameAttribute?: PrincipalUsernameAttributeEnum;
    /**
     *
     * @type {string}
     * @memberof KerberosProvider
     */
    readonly masterKey: string;
    /**
     *
     * @type {Array<string>}
     * @memberof KerberosProvider
     */
    readonly outpostSet: Array<string>;
}

/**
 * Check if a given object implements the KerberosProvider interface.
 */
export function instanceOfKerberosProvider(value: object): value is KerberosProvider {
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("component" in value) || value["component"] === undefined) return false;
    if (
        (!("assignedApplicationSlug" in (value as Record<string, any>)) &&
            !("assigned_application_slug" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["assignedApplicationSlug"] === undefined &&
            (value as Record<string, any>)["assigned_application_slug"] === undefined)
    )
        return false;
    if (
        (!("assignedApplicationName" in (value as Record<string, any>)) &&
            !("assigned_application_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["assignedApplicationName"] === undefined &&
            (value as Record<string, any>)["assigned_application_name"] === undefined)
    )
        return false;
    if (
        (!("assignedBackchannelApplicationSlug" in (value as Record<string, any>)) &&
            !("assigned_backchannel_application_slug" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["assignedBackchannelApplicationSlug"] === undefined &&
            (value as Record<string, any>)["assigned_backchannel_application_slug"] === undefined)
    )
        return false;
    if (
        (!("assignedBackchannelApplicationName" in (value as Record<string, any>)) &&
            !("assigned_backchannel_application_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["assignedBackchannelApplicationName"] === undefined &&
            (value as Record<string, any>)["assigned_backchannel_application_name"] === undefined)
    )
        return false;
    if (
        (!("verboseName" in (value as Record<string, any>)) &&
            !("verbose_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["verboseName"] === undefined &&
            (value as Record<string, any>)["verbose_name"] === undefined)
    )
        return false;
    if (
        (!("verboseNamePlural" in (value as Record<string, any>)) &&
            !("verbose_name_plural" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["verboseNamePlural"] === undefined &&
            (value as Record<string, any>)["verbose_name_plural"] === undefined)
    )
        return false;
    if (
        (!("metaModelName" in (value as Record<string, any>)) &&
            !("meta_model_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["metaModelName"] === undefined &&
            (value as Record<string, any>)["meta_model_name"] === undefined)
    )
        return false;
    if (
        (!("realmName" in (value as Record<string, any>)) &&
            !("realm_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["realmName"] === undefined &&
            (value as Record<string, any>)["realm_name"] === undefined)
    )
        return false;
    if (
        (!("masterKey" in (value as Record<string, any>)) &&
            !("master_key" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["masterKey"] === undefined &&
            (value as Record<string, any>)["master_key"] === undefined)
    )
        return false;
    if (
        (!("outpostSet" in (value as Record<string, any>)) &&
            !("outpost_set" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["outpostSet"] === undefined &&
            (value as Record<string, any>)["outpost_set"] === undefined)
    )
        return false;
    return true;
}

export function KerberosProviderFromJSON(json: any): KerberosProvider {
    return KerberosProviderFromJSONTyped(json, false);
}

export function KerberosProviderFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosProvider {
    if (json == null) {
        return json;
    }
    return {
        pk: json["pk"],
        name: json["name"],
        authenticationFlow:
            json["authentication_flow"] === undefined
                ? undefined
                : json["authentication_flow"] === null
                  ? null
                  : json["authentication_flow"],
        authorizationFlow:
            json["authorization_flow"] === undefined
                ? undefined
                : json["authorization_flow"] === null
                  ? null
                  : json["authorization_flow"],
        invalidationFlow:
            json["invalidation_flow"] === undefined
                ? undefined
                : json["invalidation_flow"] === null
                  ? null
                  : json["invalidation_flow"],
        propertyMappings: json["property_mappings"] == null ? undefined : json["property_mappings"],
        component: json["component"],
        assignedApplicationSlug: json["assigned_application_slug"],
        assignedApplicationName: json["assigned_application_name"],
        assignedBackchannelApplicationSlug: json["assigned_backchannel_application_slug"],
        assignedBackchannelApplicationName: json["assigned_backchannel_application_name"],
        verboseName: json["verbose_name"],
        verboseNamePlural: json["verbose_name_plural"],
        metaModelName: json["meta_model_name"],
        realmName: json["realm_name"],
        defaultDomain: json["default_domain"] == null ? undefined : json["default_domain"],
        maximumTicketLifetime:
            json["maximum_ticket_lifetime"] == null ? undefined : json["maximum_ticket_lifetime"],
        maximumTicketRenewLifetime:
            json["maximum_ticket_renew_lifetime"] == null
                ? undefined
                : json["maximum_ticket_renew_lifetime"],
        defaultTicketLifetime:
            json["default_ticket_lifetime"] == null ? undefined : json["default_ticket_lifetime"],
        defaultTicketRenewLifetime:
            json["default_ticket_renew_lifetime"] == null
                ? undefined
                : json["default_ticket_renew_lifetime"],
        allowedEnctypes:
            json["allowed_enctypes"] == null
                ? undefined
                : (json["allowed_enctypes"] as Array<any>).map(AllowedEnctypesEnumFromJSON),
        requirePreauthentication:
            json["require_preauthentication"] == null
                ? undefined
                : json["require_preauthentication"],
        udpEnabled: json["udp_enabled"] == null ? undefined : json["udp_enabled"],
        tcpEnabled: json["tcp_enabled"] == null ? undefined : json["tcp_enabled"],
        forwardable: json["forwardable"] == null ? undefined : json["forwardable"],
        renewable: json["renewable"] == null ? undefined : json["renewable"],
        proxiable: json["proxiable"] == null ? undefined : json["proxiable"],
        principalUsernameAttribute:
            json["principal_username_attribute"] == null
                ? undefined
                : PrincipalUsernameAttributeEnumFromJSON(json["principal_username_attribute"]),
        masterKey: json["master_key"],
        outpostSet: json["outpost_set"],
    };
}

export function KerberosProviderToJSON(json: any): KerberosProvider {
    return KerberosProviderToJSONTyped(json, false);
}

export function KerberosProviderToJSONTyped(
    value?: Omit<
        KerberosProvider,
        | "pk"
        | "component"
        | "assignedApplicationSlug"
        | "assignedApplicationName"
        | "assignedBackchannelApplicationSlug"
        | "assignedBackchannelApplicationName"
        | "verboseName"
        | "verboseNamePlural"
        | "metaModelName"
        | "masterKey"
        | "outpostSet"
    > | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        authentication_flow: value["authenticationFlow"],
        authorization_flow: value["authorizationFlow"],
        invalidation_flow: value["invalidationFlow"],
        property_mappings: value["propertyMappings"],
        realm_name: value["realmName"],
        default_domain: value["defaultDomain"],
        maximum_ticket_lifetime: value["maximumTicketLifetime"],
        maximum_ticket_renew_lifetime: value["maximumTicketRenewLifetime"],
        default_ticket_lifetime: value["defaultTicketLifetime"],
        default_ticket_renew_lifetime: value["defaultTicketRenewLifetime"],
        allowed_enctypes:
            value["allowedEnctypes"] == null
                ? undefined
                : (value["allowedEnctypes"] as Array<any>).map(AllowedEnctypesEnumToJSON),
        require_preauthentication: value["requirePreauthentication"],
        udp_enabled: value["udpEnabled"],
        tcp_enabled: value["tcpEnabled"],
        forwardable: value["forwardable"],
        renewable: value["renewable"],
        proxiable: value["proxiable"],
        principal_username_attribute: PrincipalUsernameAttributeEnumToJSON(
            value["principalUsernameAttribute"],
        ),
    };
}
