/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AllowedEnctypesEnum } from "./AllowedEnctypesEnum";
import { AllowedEnctypesEnumFromJSON, AllowedEnctypesEnumToJSON } from "./AllowedEnctypesEnum";

/**
 * Kerberos provider serializer for outposts.
 * @export
 * @interface KerberosOutpostConfig
 */
export interface KerberosOutpostConfig {
    /**
     *
     * @type {number}
     * @memberof KerberosOutpostConfig
     */
    readonly pk: number;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    realmName: string;
    /**
     *
     * @type {number}
     * @memberof KerberosOutpostConfig
     */
    readonly maximumTicketLifetime: number;
    /**
     *
     * @type {number}
     * @memberof KerberosOutpostConfig
     */
    readonly maximumTicketRenewLifetime: number;
    /**
     *
     * @type {Array<AllowedEnctypesEnum>}
     * @memberof KerberosOutpostConfig
     */
    allowedEnctypes?: Array<AllowedEnctypesEnum>;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    masterKey?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    applicationSlug: string;
}

/**
 * Check if a given object implements the KerberosOutpostConfig interface.
 */
export function instanceOfKerberosOutpostConfig(value: object): value is KerberosOutpostConfig {
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (
        (!("realmName" in (value as Record<string, any>)) &&
            !("realm_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["realmName"] === undefined &&
            (value as Record<string, any>)["realm_name"] === undefined)
    )
        return false;
    if (
        (!("maximumTicketLifetime" in (value as Record<string, any>)) &&
            !("maximum_ticket_lifetime" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["maximumTicketLifetime"] === undefined &&
            (value as Record<string, any>)["maximum_ticket_lifetime"] === undefined)
    )
        return false;
    if (
        (!("maximumTicketRenewLifetime" in (value as Record<string, any>)) &&
            !("maximum_ticket_renew_lifetime" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["maximumTicketRenewLifetime"] === undefined &&
            (value as Record<string, any>)["maximum_ticket_renew_lifetime"] === undefined)
    )
        return false;
    if (
        (!("applicationSlug" in (value as Record<string, any>)) &&
            !("application_slug" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["applicationSlug"] === undefined &&
            (value as Record<string, any>)["application_slug"] === undefined)
    )
        return false;
    return true;
}

export function KerberosOutpostConfigFromJSON(json: any): KerberosOutpostConfig {
    return KerberosOutpostConfigFromJSONTyped(json, false);
}

export function KerberosOutpostConfigFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosOutpostConfig {
    if (json == null) {
        return json;
    }
    return {
        pk: json["pk"],
        name: json["name"],
        realmName: json["realm_name"],
        maximumTicketLifetime: json["maximum_ticket_lifetime"],
        maximumTicketRenewLifetime: json["maximum_ticket_renew_lifetime"],
        allowedEnctypes:
            json["allowed_enctypes"] == null
                ? undefined
                : (json["allowed_enctypes"] as Array<any>).map(AllowedEnctypesEnumFromJSON),
        masterKey: json["master_key"] == null ? undefined : json["master_key"],
        applicationSlug: json["application_slug"],
    };
}

export function KerberosOutpostConfigToJSON(json: any): KerberosOutpostConfig {
    return KerberosOutpostConfigToJSONTyped(json, false);
}

export function KerberosOutpostConfigToJSONTyped(
    value?: Omit<
        KerberosOutpostConfig,
        "pk" | "maximumTicketLifetime" | "maximumTicketRenewLifetime"
    > | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        realm_name: value["realmName"],
        allowed_enctypes:
            value["allowedEnctypes"] == null
                ? undefined
                : (value["allowedEnctypes"] as Array<any>).map(AllowedEnctypesEnumToJSON),
        master_key: value["masterKey"],
        application_slug: value["applicationSlug"],
    };
}
