/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AllowedEnctypesEnum } from "./AllowedEnctypesEnum";
import { AllowedEnctypesEnumFromJSON, AllowedEnctypesEnumToJSON } from "./AllowedEnctypesEnum";
import type { PrincipalUsernameAttributeEnum } from "./PrincipalUsernameAttributeEnum";
import {
    PrincipalUsernameAttributeEnumFromJSON,
    PrincipalUsernameAttributeEnumToJSON,
} from "./PrincipalUsernameAttributeEnum";

/**
 * KerberosProvider serializer.
 * @export
 * @interface KerberosProviderRequest
 */
export interface KerberosProviderRequest {
    /**
     *
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    name: string;
    /**
     * Flow used for authentication when the associated application is accessed by an un-authenticated user.
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    authenticationFlow?: string | null;
    /**
     * Flow used when authorizing this provider.
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    authorizationFlow?: string | null;
    /**
     * Flow used ending the session from a provider.
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    invalidationFlow?: string | null;
    /**
     *
     * @type {Array<string>}
     * @memberof KerberosProviderRequest
     */
    propertyMappings?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    realmName: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    defaultDomain?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    maximumTicketLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    maximumTicketRenewLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    defaultTicketLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    defaultTicketRenewLifetime?: string;
    /**
     *
     * @type {Array<AllowedEnctypesEnum>}
     * @memberof KerberosProviderRequest
     */
    allowedEnctypes?: Array<AllowedEnctypesEnum>;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    requirePreauthentication?: boolean;
    /**
     * Advertise PA-SPAKE preauthentication (RFC 9588).
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    spakeEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    udpEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    tcpEnabled?: boolean;
    /**
     * Enable RFC 3244 password changes through the Kerberos outpost.
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    kpasswdEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    forwardable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    renewable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    proxiable?: boolean;
    /**
     *
     * @type {PrincipalUsernameAttributeEnum}
     * @memberof KerberosProviderRequest
     */
    principalUsernameAttribute?: PrincipalUsernameAttributeEnum;
    /**
     * Certificate/key pair the KDC uses to sign PKINIT replies. Requires a private key.
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    pkinitCertificate?: string | null;
    /**
     * CA certificate used to validate PKINIT client certificates.
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    pkinitClientCa?: string | null;
    /**
     * Require RFC 8070 freshness tokens on PKINIT requests.
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    pkinitRequireFreshness?: boolean;
    /**
     * Authentication indicators asserted after successful PKINIT.
     * @type {Array<string>}
     * @memberof KerberosProviderRequest
     */
    pkinitIndicators?: Array<string>;
    /**
     * Indicators asserted after SPAKE preauthentication.
     * @type {Array<string>}
     * @memberof KerberosProviderRequest
     */
    spakeIndicators?: Array<string>;
    /**
     * Indicator asserted after encrypted-challenge preauthentication.
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    encryptedChallengeIndicator?: string;
    /**
     * Allow anonymous PKINIT requests.
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    anonymousPkinitEnabled?: boolean;
    /**
     * Enable KDC Proxy over HTTPS (MS-KKDCP).
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    kkdcpEnabled?: boolean;
    /**
     * Certificate/key pair the KDC Proxy listener uses for TLS.
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    kkdcpCertificate?: string | null;
    /**
     * Include an MS-PAC in issued tickets.
     * @type {boolean}
     * @memberof KerberosProviderRequest
     */
    pacEnabled?: boolean;
    /**
     * Domain SID used for MS-PAC identities, for example S-1-5-21-1-2-3.
     * @type {string}
     * @memberof KerberosProviderRequest
     */
    realmSid?: string;
}

/**
 * Check if a given object implements the KerberosProviderRequest interface.
 */
export function instanceOfKerberosProviderRequest(value: object): value is KerberosProviderRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (
        (!("realmName" in (value as Record<string, any>)) &&
            !("realm_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["realmName"] === undefined &&
            (value as Record<string, any>)["realm_name"] === undefined)
    )
        return false;
    return true;
}

export function KerberosProviderRequestFromJSON(json: any): KerberosProviderRequest {
    return KerberosProviderRequestFromJSONTyped(json, false);
}

export function KerberosProviderRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        authenticationFlow:
            json["authentication_flow"] === undefined
                ? undefined
                : json["authentication_flow"] === null
                  ? null
                  : json["authentication_flow"],
        authorizationFlow:
            json["authorization_flow"] === undefined
                ? undefined
                : json["authorization_flow"] === null
                  ? null
                  : json["authorization_flow"],
        invalidationFlow:
            json["invalidation_flow"] === undefined
                ? undefined
                : json["invalidation_flow"] === null
                  ? null
                  : json["invalidation_flow"],
        propertyMappings: json["property_mappings"] == null ? undefined : json["property_mappings"],
        realmName: json["realm_name"],
        defaultDomain: json["default_domain"] == null ? undefined : json["default_domain"],
        maximumTicketLifetime:
            json["maximum_ticket_lifetime"] == null ? undefined : json["maximum_ticket_lifetime"],
        maximumTicketRenewLifetime:
            json["maximum_ticket_renew_lifetime"] == null
                ? undefined
                : json["maximum_ticket_renew_lifetime"],
        defaultTicketLifetime:
            json["default_ticket_lifetime"] == null ? undefined : json["default_ticket_lifetime"],
        defaultTicketRenewLifetime:
            json["default_ticket_renew_lifetime"] == null
                ? undefined
                : json["default_ticket_renew_lifetime"],
        allowedEnctypes:
            json["allowed_enctypes"] == null
                ? undefined
                : (json["allowed_enctypes"] as Array<any>).map(AllowedEnctypesEnumFromJSON),
        requirePreauthentication:
            json["require_preauthentication"] == null
                ? undefined
                : json["require_preauthentication"],
        spakeEnabled: json["spake_enabled"] == null ? undefined : json["spake_enabled"],
        udpEnabled: json["udp_enabled"] == null ? undefined : json["udp_enabled"],
        tcpEnabled: json["tcp_enabled"] == null ? undefined : json["tcp_enabled"],
        kpasswdEnabled: json["kpasswd_enabled"] == null ? undefined : json["kpasswd_enabled"],
        forwardable: json["forwardable"] == null ? undefined : json["forwardable"],
        renewable: json["renewable"] == null ? undefined : json["renewable"],
        proxiable: json["proxiable"] == null ? undefined : json["proxiable"],
        principalUsernameAttribute:
            json["principal_username_attribute"] == null
                ? undefined
                : PrincipalUsernameAttributeEnumFromJSON(json["principal_username_attribute"]),
        pkinitCertificate:
            json["pkinit_certificate"] === undefined
                ? undefined
                : json["pkinit_certificate"] === null
                  ? null
                  : json["pkinit_certificate"],
        pkinitClientCa:
            json["pkinit_client_ca"] === undefined
                ? undefined
                : json["pkinit_client_ca"] === null
                  ? null
                  : json["pkinit_client_ca"],
        pkinitRequireFreshness:
            json["pkinit_require_freshness"] == null ? undefined : json["pkinit_require_freshness"],
        pkinitIndicators: json["pkinit_indicators"] == null ? undefined : json["pkinit_indicators"],
        spakeIndicators: json["spake_indicators"] == null ? undefined : json["spake_indicators"],
        encryptedChallengeIndicator:
            json["encrypted_challenge_indicator"] == null
                ? undefined
                : json["encrypted_challenge_indicator"],
        anonymousPkinitEnabled:
            json["anonymous_pkinit_enabled"] == null ? undefined : json["anonymous_pkinit_enabled"],
        kkdcpEnabled: json["kkdcp_enabled"] == null ? undefined : json["kkdcp_enabled"],
        kkdcpCertificate:
            json["kkdcp_certificate"] === undefined
                ? undefined
                : json["kkdcp_certificate"] === null
                  ? null
                  : json["kkdcp_certificate"],
        pacEnabled: json["pac_enabled"] == null ? undefined : json["pac_enabled"],
        realmSid: json["realm_sid"] == null ? undefined : json["realm_sid"],
    };
}

export function KerberosProviderRequestToJSON(json: any): KerberosProviderRequest {
    return KerberosProviderRequestToJSONTyped(json, false);
}

export function KerberosProviderRequestToJSONTyped(
    value?: KerberosProviderRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        authentication_flow: value["authenticationFlow"],
        authorization_flow: value["authorizationFlow"],
        invalidation_flow: value["invalidationFlow"],
        property_mappings: value["propertyMappings"],
        realm_name: value["realmName"],
        default_domain: value["defaultDomain"],
        maximum_ticket_lifetime: value["maximumTicketLifetime"],
        maximum_ticket_renew_lifetime: value["maximumTicketRenewLifetime"],
        default_ticket_lifetime: value["defaultTicketLifetime"],
        default_ticket_renew_lifetime: value["defaultTicketRenewLifetime"],
        allowed_enctypes:
            value["allowedEnctypes"] == null
                ? undefined
                : (value["allowedEnctypes"] as Array<any>).map(AllowedEnctypesEnumToJSON),
        require_preauthentication: value["requirePreauthentication"],
        spake_enabled: value["spakeEnabled"],
        udp_enabled: value["udpEnabled"],
        tcp_enabled: value["tcpEnabled"],
        kpasswd_enabled: value["kpasswdEnabled"],
        forwardable: value["forwardable"],
        renewable: value["renewable"],
        proxiable: value["proxiable"],
        principal_username_attribute: PrincipalUsernameAttributeEnumToJSON(
            value["principalUsernameAttribute"],
        ),
        pkinit_certificate: value["pkinitCertificate"],
        pkinit_client_ca: value["pkinitClientCa"],
        pkinit_require_freshness: value["pkinitRequireFreshness"],
        pkinit_indicators: value["pkinitIndicators"],
        spake_indicators: value["spakeIndicators"],
        encrypted_challenge_indicator: value["encryptedChallengeIndicator"],
        anonymous_pkinit_enabled: value["anonymousPkinitEnabled"],
        kkdcp_enabled: value["kkdcpEnabled"],
        kkdcp_certificate: value["kkdcpCertificate"],
        pac_enabled: value["pacEnabled"],
        realm_sid: value["realmSid"],
    };
}
