/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AllowedEnctypesEnum } from "./AllowedEnctypesEnum";
import { AllowedEnctypesEnumFromJSON, AllowedEnctypesEnumToJSON } from "./AllowedEnctypesEnum";
import type { PrincipalUsernameAttributeEnum } from "./PrincipalUsernameAttributeEnum";
import {
    PrincipalUsernameAttributeEnumFromJSON,
    PrincipalUsernameAttributeEnumToJSON,
} from "./PrincipalUsernameAttributeEnum";

/**
 * Kerberos provider serializer for outposts.
 * @export
 * @interface KerberosOutpostConfig
 */
export interface KerberosOutpostConfig {
    /**
     *
     * @type {number}
     * @memberof KerberosOutpostConfig
     */
    readonly pk: number;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    realmName: string;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    defaultDomain?: string;
    /**
     *
     * @type {number}
     * @memberof KerberosOutpostConfig
     */
    readonly maximumTicketLifetime: number;
    /**
     *
     * @type {number}
     * @memberof KerberosOutpostConfig
     */
    readonly maximumTicketRenewLifetime: number;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    defaultTicketLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    defaultTicketRenewLifetime?: string;
    /**
     *
     * @type {Array<AllowedEnctypesEnum>}
     * @memberof KerberosOutpostConfig
     */
    allowedEnctypes?: Array<AllowedEnctypesEnum>;
    /**
     *
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    requirePreauthentication?: boolean;
    /**
     * Advertise PA-SPAKE preauthentication (RFC 9588).
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    spakeEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    udpEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    tcpEnabled?: boolean;
    /**
     * Enable RFC 3244 password changes through the Kerberos outpost.
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    kpasswdEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    forwardable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    renewable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    proxiable?: boolean;
    /**
     *
     * @type {PrincipalUsernameAttributeEnum}
     * @memberof KerberosOutpostConfig
     */
    principalUsernameAttribute?: PrincipalUsernameAttributeEnum;
    /**
     * Certificate/key pair the KDC uses to sign PKINIT replies. Requires a private key.
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    pkinitCertificate?: string | null;
    /**
     * CA certificate used to validate PKINIT client certificates.
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    pkinitClientCa?: string | null;
    /**
     * Require RFC 8070 freshness tokens on PKINIT requests.
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    pkinitRequireFreshness?: boolean;
    /**
     * Allow anonymous PKINIT requests.
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    anonymousPkinitEnabled?: boolean;
    /**
     * Enable KDC Proxy over HTTPS (MS-KKDCP).
     * @type {boolean}
     * @memberof KerberosOutpostConfig
     */
    kkdcpEnabled?: boolean;
    /**
     * Certificate/key pair the KDC Proxy listener uses for TLS.
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    kkdcpCertificate?: string | null;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    masterKey?: string;
    /**
     *
     * @type {string}
     * @memberof KerberosOutpostConfig
     */
    applicationSlug: string;
}

/**
 * Check if a given object implements the KerberosOutpostConfig interface.
 */
export function instanceOfKerberosOutpostConfig(value: object): value is KerberosOutpostConfig {
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (
        (!("realmName" in (value as Record<string, any>)) &&
            !("realm_name" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["realmName"] === undefined &&
            (value as Record<string, any>)["realm_name"] === undefined)
    )
        return false;
    if (
        (!("maximumTicketLifetime" in (value as Record<string, any>)) &&
            !("maximum_ticket_lifetime" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["maximumTicketLifetime"] === undefined &&
            (value as Record<string, any>)["maximum_ticket_lifetime"] === undefined)
    )
        return false;
    if (
        (!("maximumTicketRenewLifetime" in (value as Record<string, any>)) &&
            !("maximum_ticket_renew_lifetime" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["maximumTicketRenewLifetime"] === undefined &&
            (value as Record<string, any>)["maximum_ticket_renew_lifetime"] === undefined)
    )
        return false;
    if (
        (!("applicationSlug" in (value as Record<string, any>)) &&
            !("application_slug" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["applicationSlug"] === undefined &&
            (value as Record<string, any>)["application_slug"] === undefined)
    )
        return false;
    return true;
}

export function KerberosOutpostConfigFromJSON(json: any): KerberosOutpostConfig {
    return KerberosOutpostConfigFromJSONTyped(json, false);
}

export function KerberosOutpostConfigFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosOutpostConfig {
    if (json == null) {
        return json;
    }
    return {
        pk: json["pk"],
        name: json["name"],
        realmName: json["realm_name"],
        defaultDomain: json["default_domain"] == null ? undefined : json["default_domain"],
        maximumTicketLifetime: json["maximum_ticket_lifetime"],
        maximumTicketRenewLifetime: json["maximum_ticket_renew_lifetime"],
        defaultTicketLifetime:
            json["default_ticket_lifetime"] == null ? undefined : json["default_ticket_lifetime"],
        defaultTicketRenewLifetime:
            json["default_ticket_renew_lifetime"] == null
                ? undefined
                : json["default_ticket_renew_lifetime"],
        allowedEnctypes:
            json["allowed_enctypes"] == null
                ? undefined
                : (json["allowed_enctypes"] as Array<any>).map(AllowedEnctypesEnumFromJSON),
        requirePreauthentication:
            json["require_preauthentication"] == null
                ? undefined
                : json["require_preauthentication"],
        spakeEnabled: json["spake_enabled"] == null ? undefined : json["spake_enabled"],
        udpEnabled: json["udp_enabled"] == null ? undefined : json["udp_enabled"],
        tcpEnabled: json["tcp_enabled"] == null ? undefined : json["tcp_enabled"],
        kpasswdEnabled: json["kpasswd_enabled"] == null ? undefined : json["kpasswd_enabled"],
        forwardable: json["forwardable"] == null ? undefined : json["forwardable"],
        renewable: json["renewable"] == null ? undefined : json["renewable"],
        proxiable: json["proxiable"] == null ? undefined : json["proxiable"],
        principalUsernameAttribute:
            json["principal_username_attribute"] == null
                ? undefined
                : PrincipalUsernameAttributeEnumFromJSON(json["principal_username_attribute"]),
        pkinitCertificate:
            json["pkinit_certificate"] === undefined
                ? undefined
                : json["pkinit_certificate"] === null
                  ? null
                  : json["pkinit_certificate"],
        pkinitClientCa:
            json["pkinit_client_ca"] === undefined
                ? undefined
                : json["pkinit_client_ca"] === null
                  ? null
                  : json["pkinit_client_ca"],
        pkinitRequireFreshness:
            json["pkinit_require_freshness"] == null ? undefined : json["pkinit_require_freshness"],
        anonymousPkinitEnabled:
            json["anonymous_pkinit_enabled"] == null ? undefined : json["anonymous_pkinit_enabled"],
        kkdcpEnabled: json["kkdcp_enabled"] == null ? undefined : json["kkdcp_enabled"],
        kkdcpCertificate:
            json["kkdcp_certificate"] === undefined
                ? undefined
                : json["kkdcp_certificate"] === null
                  ? null
                  : json["kkdcp_certificate"],
        masterKey: json["master_key"] == null ? undefined : json["master_key"],
        applicationSlug: json["application_slug"],
    };
}

export function KerberosOutpostConfigToJSON(json: any): KerberosOutpostConfig {
    return KerberosOutpostConfigToJSONTyped(json, false);
}

export function KerberosOutpostConfigToJSONTyped(
    value?: Omit<
        KerberosOutpostConfig,
        "pk" | "maximumTicketLifetime" | "maximumTicketRenewLifetime"
    > | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        realm_name: value["realmName"],
        default_domain: value["defaultDomain"],
        default_ticket_lifetime: value["defaultTicketLifetime"],
        default_ticket_renew_lifetime: value["defaultTicketRenewLifetime"],
        allowed_enctypes:
            value["allowedEnctypes"] == null
                ? undefined
                : (value["allowedEnctypes"] as Array<any>).map(AllowedEnctypesEnumToJSON),
        require_preauthentication: value["requirePreauthentication"],
        spake_enabled: value["spakeEnabled"],
        udp_enabled: value["udpEnabled"],
        tcp_enabled: value["tcpEnabled"],
        kpasswd_enabled: value["kpasswdEnabled"],
        forwardable: value["forwardable"],
        renewable: value["renewable"],
        proxiable: value["proxiable"],
        principal_username_attribute: PrincipalUsernameAttributeEnumToJSON(
            value["principalUsernameAttribute"],
        ),
        pkinit_certificate: value["pkinitCertificate"],
        pkinit_client_ca: value["pkinitClientCa"],
        pkinit_require_freshness: value["pkinitRequireFreshness"],
        anonymous_pkinit_enabled: value["anonymousPkinitEnabled"],
        kkdcp_enabled: value["kkdcpEnabled"],
        kkdcp_certificate: value["kkdcpCertificate"],
        master_key: value["masterKey"],
        application_slug: value["applicationSlug"],
    };
}
