/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KerberosProvider } from "./KerberosProvider";
import { KerberosProviderFromJSON, KerberosProviderToJSON } from "./KerberosProvider";
import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";

/**
 *
 * @export
 * @interface PaginatedKerberosProviderList
 */
export interface PaginatedKerberosProviderList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedKerberosProviderList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<KerberosProvider>}
     * @memberof PaginatedKerberosProviderList
     */
    results: Array<KerberosProvider>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedKerberosProviderList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedKerberosProviderList interface.
 */
export function instanceOfPaginatedKerberosProviderList(
    value: object,
): value is PaginatedKerberosProviderList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedKerberosProviderListFromJSON(json: any): PaginatedKerberosProviderList {
    return PaginatedKerberosProviderListFromJSONTyped(json, false);
}

export function PaginatedKerberosProviderListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedKerberosProviderList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(KerberosProviderFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedKerberosProviderListToJSON(json: any): PaginatedKerberosProviderList {
    return PaginatedKerberosProviderListToJSONTyped(json, false);
}

export function PaginatedKerberosProviderListToJSONTyped(
    value?: PaginatedKerberosProviderList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(KerberosProviderToJSON),
        autocomplete: value["autocomplete"],
    };
}
