/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KerberosServicePrincipalOutpost } from "./KerberosServicePrincipalOutpost";
import {
    KerberosServicePrincipalOutpostFromJSON,
    KerberosServicePrincipalOutpostToJSON,
} from "./KerberosServicePrincipalOutpost";
import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";

/**
 *
 * @export
 * @interface PaginatedKerberosServicePrincipalOutpostList
 */
export interface PaginatedKerberosServicePrincipalOutpostList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedKerberosServicePrincipalOutpostList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<KerberosServicePrincipalOutpost>}
     * @memberof PaginatedKerberosServicePrincipalOutpostList
     */
    results: Array<KerberosServicePrincipalOutpost>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedKerberosServicePrincipalOutpostList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedKerberosServicePrincipalOutpostList interface.
 */
export function instanceOfPaginatedKerberosServicePrincipalOutpostList(
    value: object,
): value is PaginatedKerberosServicePrincipalOutpostList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedKerberosServicePrincipalOutpostListFromJSON(
    json: any,
): PaginatedKerberosServicePrincipalOutpostList {
    return PaginatedKerberosServicePrincipalOutpostListFromJSONTyped(json, false);
}

export function PaginatedKerberosServicePrincipalOutpostListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedKerberosServicePrincipalOutpostList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(KerberosServicePrincipalOutpostFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedKerberosServicePrincipalOutpostListToJSON(
    json: any,
): PaginatedKerberosServicePrincipalOutpostList {
    return PaginatedKerberosServicePrincipalOutpostListToJSONTyped(json, false);
}

export function PaginatedKerberosServicePrincipalOutpostListToJSONTyped(
    value?: PaginatedKerberosServicePrincipalOutpostList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(KerberosServicePrincipalOutpostToJSON),
        autocomplete: value["autocomplete"],
    };
}
