/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KerberosRealmTrustOutpost } from "./KerberosRealmTrustOutpost";
import {
    KerberosRealmTrustOutpostFromJSON,
    KerberosRealmTrustOutpostToJSON,
} from "./KerberosRealmTrustOutpost";
import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";

/**
 *
 * @export
 * @interface PaginatedKerberosRealmTrustOutpostList
 */
export interface PaginatedKerberosRealmTrustOutpostList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedKerberosRealmTrustOutpostList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<KerberosRealmTrustOutpost>}
     * @memberof PaginatedKerberosRealmTrustOutpostList
     */
    results: Array<KerberosRealmTrustOutpost>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedKerberosRealmTrustOutpostList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedKerberosRealmTrustOutpostList interface.
 */
export function instanceOfPaginatedKerberosRealmTrustOutpostList(
    value: object,
): value is PaginatedKerberosRealmTrustOutpostList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedKerberosRealmTrustOutpostListFromJSON(
    json: any,
): PaginatedKerberosRealmTrustOutpostList {
    return PaginatedKerberosRealmTrustOutpostListFromJSONTyped(json, false);
}

export function PaginatedKerberosRealmTrustOutpostListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedKerberosRealmTrustOutpostList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(KerberosRealmTrustOutpostFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedKerberosRealmTrustOutpostListToJSON(
    json: any,
): PaginatedKerberosRealmTrustOutpostList {
    return PaginatedKerberosRealmTrustOutpostListToJSONTyped(json, false);
}

export function PaginatedKerberosRealmTrustOutpostListToJSONTyped(
    value?: PaginatedKerberosRealmTrustOutpostList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(KerberosRealmTrustOutpostToJSON),
        autocomplete: value["autocomplete"],
    };
}
