/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KerberosUserKeyOutpost } from "./KerberosUserKeyOutpost";
import {
    KerberosUserKeyOutpostFromJSON,
    KerberosUserKeyOutpostToJSON,
} from "./KerberosUserKeyOutpost";
import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";

/**
 *
 * @export
 * @interface PaginatedKerberosUserKeyOutpostList
 */
export interface PaginatedKerberosUserKeyOutpostList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedKerberosUserKeyOutpostList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<KerberosUserKeyOutpost>}
     * @memberof PaginatedKerberosUserKeyOutpostList
     */
    results: Array<KerberosUserKeyOutpost>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedKerberosUserKeyOutpostList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedKerberosUserKeyOutpostList interface.
 */
export function instanceOfPaginatedKerberosUserKeyOutpostList(
    value: object,
): value is PaginatedKerberosUserKeyOutpostList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedKerberosUserKeyOutpostListFromJSON(
    json: any,
): PaginatedKerberosUserKeyOutpostList {
    return PaginatedKerberosUserKeyOutpostListFromJSONTyped(json, false);
}

export function PaginatedKerberosUserKeyOutpostListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedKerberosUserKeyOutpostList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(KerberosUserKeyOutpostFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedKerberosUserKeyOutpostListToJSON(
    json: any,
): PaginatedKerberosUserKeyOutpostList {
    return PaginatedKerberosUserKeyOutpostListToJSONTyped(json, false);
}

export function PaginatedKerberosUserKeyOutpostListToJSONTyped(
    value?: PaginatedKerberosUserKeyOutpostList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(KerberosUserKeyOutpostToJSON),
        autocomplete: value["autocomplete"],
    };
}
