/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KerberosRealmTrust } from "./KerberosRealmTrust";
import { KerberosRealmTrustFromJSON, KerberosRealmTrustToJSON } from "./KerberosRealmTrust";
import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";

/**
 *
 * @export
 * @interface PaginatedKerberosRealmTrustList
 */
export interface PaginatedKerberosRealmTrustList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedKerberosRealmTrustList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<KerberosRealmTrust>}
     * @memberof PaginatedKerberosRealmTrustList
     */
    results: Array<KerberosRealmTrust>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedKerberosRealmTrustList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedKerberosRealmTrustList interface.
 */
export function instanceOfPaginatedKerberosRealmTrustList(
    value: object,
): value is PaginatedKerberosRealmTrustList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedKerberosRealmTrustListFromJSON(
    json: any,
): PaginatedKerberosRealmTrustList {
    return PaginatedKerberosRealmTrustListFromJSONTyped(json, false);
}

export function PaginatedKerberosRealmTrustListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedKerberosRealmTrustList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(KerberosRealmTrustFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedKerberosRealmTrustListToJSON(json: any): PaginatedKerberosRealmTrustList {
    return PaginatedKerberosRealmTrustListToJSONTyped(json, false);
}

export function PaginatedKerberosRealmTrustListToJSONTyped(
    value?: PaginatedKerberosRealmTrustList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(KerberosRealmTrustToJSON),
        autocomplete: value["autocomplete"],
    };
}
