/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Kerberos realm trust serializer.
 * @export
 * @interface PatchedKerberosRealmTrustRequest
 */
export interface PatchedKerberosRealmTrustRequest {
    /**
     *
     * @type {number}
     * @memberof PatchedKerberosRealmTrustRequest
     */
    provider?: number;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosRealmTrustRequest
     */
    remoteRealm?: string;
    /**
     * Intermediate realms for transited-path checking.
     * @type {Array<string>}
     * @memberof PatchedKerberosRealmTrustRequest
     */
    capaths?: Array<string>;
}

/**
 * Check if a given object implements the PatchedKerberosRealmTrustRequest interface.
 */
export function instanceOfPatchedKerberosRealmTrustRequest(
    value: object,
): value is PatchedKerberosRealmTrustRequest {
    return true;
}

export function PatchedKerberosRealmTrustRequestFromJSON(
    json: any,
): PatchedKerberosRealmTrustRequest {
    return PatchedKerberosRealmTrustRequestFromJSONTyped(json, false);
}

export function PatchedKerberosRealmTrustRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedKerberosRealmTrustRequest {
    if (json == null) {
        return json;
    }
    return {
        provider: json["provider"] == null ? undefined : json["provider"],
        remoteRealm: json["remote_realm"] == null ? undefined : json["remote_realm"],
        capaths: json["capaths"] == null ? undefined : json["capaths"],
    };
}

export function PatchedKerberosRealmTrustRequestToJSON(
    json: any,
): PatchedKerberosRealmTrustRequest {
    return PatchedKerberosRealmTrustRequestToJSONTyped(json, false);
}

export function PatchedKerberosRealmTrustRequestToJSONTyped(
    value?: PatchedKerberosRealmTrustRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        provider: value["provider"],
        remote_realm: value["remoteRealm"],
        capaths: value["capaths"],
    };
}
