/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TicketFlagsEnum } from "./TicketFlagsEnum";
import { TicketFlagsEnumFromJSON, TicketFlagsEnumToJSON } from "./TicketFlagsEnum";

/**
 * Kerberos service principal serializer.
 * @export
 * @interface PatchedKerberosServicePrincipalRequest
 */
export interface PatchedKerberosServicePrincipalRequest {
    /**
     *
     * @type {number}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    provider?: number;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    spn?: string;
    /**
     * Optional authentik user (typically a service account) whose policies are evaluated when this principal acts as a Kerberos client.
     * @type {number}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    serviceAccount?: number | null;
    /**
     * Allow this service principal to authenticate as a user for delegation.
     * @type {boolean}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    okToAuthAsDelegate?: boolean;
    /**
     *
     * @type {Array<string>}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    allowedDelegationTargets?: Array<string>;
    /**
     * Authentication indicators required to obtain tickets for this service.
     * @type {Array<string>}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    requiredAuthIndicators?: Array<string>;
    /**
     *
     * @type {Array<TicketFlagsEnum>}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    ticketFlags?: Array<TicketFlagsEnum>;
}

/**
 * Check if a given object implements the PatchedKerberosServicePrincipalRequest interface.
 */
export function instanceOfPatchedKerberosServicePrincipalRequest(
    value: object,
): value is PatchedKerberosServicePrincipalRequest {
    return true;
}

export function PatchedKerberosServicePrincipalRequestFromJSON(
    json: any,
): PatchedKerberosServicePrincipalRequest {
    return PatchedKerberosServicePrincipalRequestFromJSONTyped(json, false);
}

export function PatchedKerberosServicePrincipalRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedKerberosServicePrincipalRequest {
    if (json == null) {
        return json;
    }
    return {
        provider: json["provider"] == null ? undefined : json["provider"],
        spn: json["spn"] == null ? undefined : json["spn"],
        serviceAccount:
            json["service_account"] === undefined
                ? undefined
                : json["service_account"] === null
                  ? null
                  : json["service_account"],
        okToAuthAsDelegate:
            json["ok_to_auth_as_delegate"] == null ? undefined : json["ok_to_auth_as_delegate"],
        allowedDelegationTargets:
            json["allowed_delegation_targets"] == null
                ? undefined
                : json["allowed_delegation_targets"],
        requiredAuthIndicators:
            json["required_auth_indicators"] == null ? undefined : json["required_auth_indicators"],
        ticketFlags:
            json["ticket_flags"] == null
                ? undefined
                : (json["ticket_flags"] as Array<any>).map(TicketFlagsEnumFromJSON),
    };
}

export function PatchedKerberosServicePrincipalRequestToJSON(
    json: any,
): PatchedKerberosServicePrincipalRequest {
    return PatchedKerberosServicePrincipalRequestToJSONTyped(json, false);
}

export function PatchedKerberosServicePrincipalRequestToJSONTyped(
    value?: PatchedKerberosServicePrincipalRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        provider: value["provider"],
        spn: value["spn"],
        service_account: value["serviceAccount"],
        ok_to_auth_as_delegate: value["okToAuthAsDelegate"],
        allowed_delegation_targets: value["allowedDelegationTargets"],
        required_auth_indicators: value["requiredAuthIndicators"],
        ticket_flags:
            value["ticketFlags"] == null
                ? undefined
                : (value["ticketFlags"] as Array<any>).map(TicketFlagsEnumToJSON),
    };
}
