/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Kerberos service principal serializer.
 * @export
 * @interface PatchedKerberosServicePrincipalRequest
 */
export interface PatchedKerberosServicePrincipalRequest {
    /**
     *
     * @type {number}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    provider?: number;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    spn?: string;
    /**
     * Allow this service principal to authenticate as a user for delegation.
     * @type {boolean}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    okToAuthAsDelegate?: boolean;
    /**
     *
     * @type {Array<string>}
     * @memberof PatchedKerberosServicePrincipalRequest
     */
    allowedDelegationTargets?: Array<string>;
}

/**
 * Check if a given object implements the PatchedKerberosServicePrincipalRequest interface.
 */
export function instanceOfPatchedKerberosServicePrincipalRequest(
    value: object,
): value is PatchedKerberosServicePrincipalRequest {
    return true;
}

export function PatchedKerberosServicePrincipalRequestFromJSON(
    json: any,
): PatchedKerberosServicePrincipalRequest {
    return PatchedKerberosServicePrincipalRequestFromJSONTyped(json, false);
}

export function PatchedKerberosServicePrincipalRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedKerberosServicePrincipalRequest {
    if (json == null) {
        return json;
    }
    return {
        provider: json["provider"] == null ? undefined : json["provider"],
        spn: json["spn"] == null ? undefined : json["spn"],
        okToAuthAsDelegate:
            json["ok_to_auth_as_delegate"] == null ? undefined : json["ok_to_auth_as_delegate"],
        allowedDelegationTargets:
            json["allowed_delegation_targets"] == null
                ? undefined
                : json["allowed_delegation_targets"],
    };
}

export function PatchedKerberosServicePrincipalRequestToJSON(
    json: any,
): PatchedKerberosServicePrincipalRequest {
    return PatchedKerberosServicePrincipalRequestToJSONTyped(json, false);
}

export function PatchedKerberosServicePrincipalRequestToJSONTyped(
    value?: PatchedKerberosServicePrincipalRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        provider: value["provider"],
        spn: value["spn"],
        ok_to_auth_as_delegate: value["okToAuthAsDelegate"],
        allowed_delegation_targets: value["allowedDelegationTargets"],
    };
}
