/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AllowedEnctypesEnum } from "./AllowedEnctypesEnum";
import { AllowedEnctypesEnumFromJSON, AllowedEnctypesEnumToJSON } from "./AllowedEnctypesEnum";
import type { PrincipalUsernameAttributeEnum } from "./PrincipalUsernameAttributeEnum";
import {
    PrincipalUsernameAttributeEnumFromJSON,
    PrincipalUsernameAttributeEnumToJSON,
} from "./PrincipalUsernameAttributeEnum";

/**
 * KerberosProvider serializer.
 * @export
 * @interface PatchedKerberosProviderRequest
 */
export interface PatchedKerberosProviderRequest {
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    name?: string;
    /**
     * Flow used for authentication when the associated application is accessed by an un-authenticated user.
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    authenticationFlow?: string | null;
    /**
     * Flow used when authorizing this provider.
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    authorizationFlow?: string | null;
    /**
     * Flow used ending the session from a provider.
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    invalidationFlow?: string | null;
    /**
     *
     * @type {Array<string>}
     * @memberof PatchedKerberosProviderRequest
     */
    propertyMappings?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    realmName?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    defaultDomain?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    maximumTicketLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    maximumTicketRenewLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    defaultTicketLifetime?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    defaultTicketRenewLifetime?: string;
    /**
     *
     * @type {Array<AllowedEnctypesEnum>}
     * @memberof PatchedKerberosProviderRequest
     */
    allowedEnctypes?: Array<AllowedEnctypesEnum>;
    /**
     *
     * @type {boolean}
     * @memberof PatchedKerberosProviderRequest
     */
    requirePreauthentication?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PatchedKerberosProviderRequest
     */
    udpEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PatchedKerberosProviderRequest
     */
    tcpEnabled?: boolean;
    /**
     * Enable RFC 3244 password changes through the Kerberos outpost.
     * @type {boolean}
     * @memberof PatchedKerberosProviderRequest
     */
    kpasswdEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PatchedKerberosProviderRequest
     */
    forwardable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PatchedKerberosProviderRequest
     */
    renewable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PatchedKerberosProviderRequest
     */
    proxiable?: boolean;
    /**
     *
     * @type {PrincipalUsernameAttributeEnum}
     * @memberof PatchedKerberosProviderRequest
     */
    principalUsernameAttribute?: PrincipalUsernameAttributeEnum;
    /**
     * Certificate/key pair the KDC uses to sign PKINIT replies. Requires a private key.
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    pkinitCertificate?: string | null;
    /**
     * CA certificate used to validate PKINIT client certificates.
     * @type {string}
     * @memberof PatchedKerberosProviderRequest
     */
    pkinitClientCa?: string | null;
}

/**
 * Check if a given object implements the PatchedKerberosProviderRequest interface.
 */
export function instanceOfPatchedKerberosProviderRequest(
    value: object,
): value is PatchedKerberosProviderRequest {
    return true;
}

export function PatchedKerberosProviderRequestFromJSON(json: any): PatchedKerberosProviderRequest {
    return PatchedKerberosProviderRequestFromJSONTyped(json, false);
}

export function PatchedKerberosProviderRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedKerberosProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        authenticationFlow:
            json["authentication_flow"] === undefined
                ? undefined
                : json["authentication_flow"] === null
                  ? null
                  : json["authentication_flow"],
        authorizationFlow:
            json["authorization_flow"] === undefined
                ? undefined
                : json["authorization_flow"] === null
                  ? null
                  : json["authorization_flow"],
        invalidationFlow:
            json["invalidation_flow"] === undefined
                ? undefined
                : json["invalidation_flow"] === null
                  ? null
                  : json["invalidation_flow"],
        propertyMappings: json["property_mappings"] == null ? undefined : json["property_mappings"],
        realmName: json["realm_name"] == null ? undefined : json["realm_name"],
        defaultDomain: json["default_domain"] == null ? undefined : json["default_domain"],
        maximumTicketLifetime:
            json["maximum_ticket_lifetime"] == null ? undefined : json["maximum_ticket_lifetime"],
        maximumTicketRenewLifetime:
            json["maximum_ticket_renew_lifetime"] == null
                ? undefined
                : json["maximum_ticket_renew_lifetime"],
        defaultTicketLifetime:
            json["default_ticket_lifetime"] == null ? undefined : json["default_ticket_lifetime"],
        defaultTicketRenewLifetime:
            json["default_ticket_renew_lifetime"] == null
                ? undefined
                : json["default_ticket_renew_lifetime"],
        allowedEnctypes:
            json["allowed_enctypes"] == null
                ? undefined
                : (json["allowed_enctypes"] as Array<any>).map(AllowedEnctypesEnumFromJSON),
        requirePreauthentication:
            json["require_preauthentication"] == null
                ? undefined
                : json["require_preauthentication"],
        udpEnabled: json["udp_enabled"] == null ? undefined : json["udp_enabled"],
        tcpEnabled: json["tcp_enabled"] == null ? undefined : json["tcp_enabled"],
        kpasswdEnabled: json["kpasswd_enabled"] == null ? undefined : json["kpasswd_enabled"],
        forwardable: json["forwardable"] == null ? undefined : json["forwardable"],
        renewable: json["renewable"] == null ? undefined : json["renewable"],
        proxiable: json["proxiable"] == null ? undefined : json["proxiable"],
        principalUsernameAttribute:
            json["principal_username_attribute"] == null
                ? undefined
                : PrincipalUsernameAttributeEnumFromJSON(json["principal_username_attribute"]),
        pkinitCertificate:
            json["pkinit_certificate"] === undefined
                ? undefined
                : json["pkinit_certificate"] === null
                  ? null
                  : json["pkinit_certificate"],
        pkinitClientCa:
            json["pkinit_client_ca"] === undefined
                ? undefined
                : json["pkinit_client_ca"] === null
                  ? null
                  : json["pkinit_client_ca"],
    };
}

export function PatchedKerberosProviderRequestToJSON(json: any): PatchedKerberosProviderRequest {
    return PatchedKerberosProviderRequestToJSONTyped(json, false);
}

export function PatchedKerberosProviderRequestToJSONTyped(
    value?: PatchedKerberosProviderRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        authentication_flow: value["authenticationFlow"],
        authorization_flow: value["authorizationFlow"],
        invalidation_flow: value["invalidationFlow"],
        property_mappings: value["propertyMappings"],
        realm_name: value["realmName"],
        default_domain: value["defaultDomain"],
        maximum_ticket_lifetime: value["maximumTicketLifetime"],
        maximum_ticket_renew_lifetime: value["maximumTicketRenewLifetime"],
        default_ticket_lifetime: value["defaultTicketLifetime"],
        default_ticket_renew_lifetime: value["defaultTicketRenewLifetime"],
        allowed_enctypes:
            value["allowedEnctypes"] == null
                ? undefined
                : (value["allowedEnctypes"] as Array<any>).map(AllowedEnctypesEnumToJSON),
        require_preauthentication: value["requirePreauthentication"],
        udp_enabled: value["udpEnabled"],
        tcp_enabled: value["tcpEnabled"],
        kpasswd_enabled: value["kpasswdEnabled"],
        forwardable: value["forwardable"],
        renewable: value["renewable"],
        proxiable: value["proxiable"],
        principal_username_attribute: PrincipalUsernameAttributeEnumToJSON(
            value["principalUsernameAttribute"],
        ),
        pkinit_certificate: value["pkinitCertificate"],
        pkinit_client_ca: value["pkinitClientCa"],
    };
}
