/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The newly generated secret, or null when the field is not readable on the object
 * @export
 * @interface RotatedSecret
 */
export interface RotatedSecret {
    /**
     *
     * @type {string}
     * @memberof RotatedSecret
     */
    readonly secret: string | null;
}

/**
 * Check if a given object implements the RotatedSecret interface.
 */
export function instanceOfRotatedSecret(value: object): value is RotatedSecret {
    if (!("secret" in value) || value["secret"] === undefined) return false;
    return true;
}

export function RotatedSecretFromJSON(json: any): RotatedSecret {
    return RotatedSecretFromJSONTyped(json, false);
}

export function RotatedSecretFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotatedSecret {
    if (json == null) {
        return json;
    }
    return {
        secret: json["secret"],
    };
}

export function RotatedSecretToJSON(json: any): RotatedSecret {
    return RotatedSecretToJSONTyped(json, false);
}

export function RotatedSecretToJSONTyped(
    value?: Omit<RotatedSecret, "secret"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {};
}
