/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const TicketFlagsEnum = {
    RequiresPreauth: "requires_preauth",
    RequiresHwauth: "requires_hwauth",
    DisallowPostdated: "disallow_postdated",
    DisallowForwardable: "disallow_forwardable",
    DisallowProxiable: "disallow_proxiable",
    DisallowRenewable: "disallow_renewable",
    DisallowTgtBased: "disallow_tgt_based",
    DisallowServer: "disallow_server",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type TicketFlagsEnum = (typeof TicketFlagsEnum)[keyof typeof TicketFlagsEnum];

export function instanceOfTicketFlagsEnum(value: any): boolean {
    for (const key in TicketFlagsEnum) {
        if (Object.prototype.hasOwnProperty.call(TicketFlagsEnum, key)) {
            if (TicketFlagsEnum[key as keyof typeof TicketFlagsEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TicketFlagsEnumFromJSON(json: any): TicketFlagsEnum {
    return TicketFlagsEnumFromJSONTyped(json, false);
}

export function TicketFlagsEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TicketFlagsEnum {
    return json as TicketFlagsEnum;
}

export function TicketFlagsEnumToJSON(value?: TicketFlagsEnum | null): any {
    return value as any;
}

export function TicketFlagsEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): TicketFlagsEnum {
    return value as TicketFlagsEnum;
}
