/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum AllowedEnctypesEnum {
    Variant17 = 17,
    Variant18 = 18,
    Variant19 = 19,
    Variant20 = 20,

}

impl std::fmt::Display for AllowedEnctypesEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant17 => "17",
            Self::Variant18 => "18",
            Self::Variant19 => "19",
            Self::Variant20 => "20",
        })
    }
}
impl Default for AllowedEnctypesEnum {
    fn default() -> AllowedEnctypesEnum {
        Self::Variant17
    }
}

