/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KerberosServicePrincipalAdminRequest : Service principal management request for the kadm5 outpost.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KerberosServicePrincipalAdminRequest {
    #[serde(rename = "spn")]
    pub spn: String,
}
impl KerberosServicePrincipalAdminRequest {
    /// Service principal management request for the kadm5 outpost.
    pub fn new(spn: String) -> KerberosServicePrincipalAdminRequest {
        KerberosServicePrincipalAdminRequest {
            spn,
        }
    }
}
