/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KerberosServicePrincipalOutpost : Service principal data consumed by the KDC outpost.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KerberosServicePrincipalOutpost {
    #[serde(rename = "spn")]
    pub spn: String,
    #[serde(rename = "kvno")]
    pub kvno: i32,
    #[serde(rename = "keys")]
    pub keys: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "ok_to_auth_as_delegate")]
    pub ok_to_auth_as_delegate: bool,
    #[serde(rename = "allowed_delegation_targets")]
    pub allowed_delegation_targets: Vec<String>,
    #[serde(rename = "required_auth_indicators")]
    pub required_auth_indicators: Vec<String>,
}

impl KerberosServicePrincipalOutpost {
    /// Service principal data consumed by the KDC outpost.
    pub fn new(spn: String, kvno: i32, keys: std::collections::HashMap<String, serde_json::Value>, ok_to_auth_as_delegate: bool, allowed_delegation_targets: Vec<String>, required_auth_indicators: Vec<String>) -> KerberosServicePrincipalOutpost {
        KerberosServicePrincipalOutpost {
            spn,
            kvno,
            keys,
            ok_to_auth_as_delegate,
            allowed_delegation_targets,
            required_auth_indicators,
        }
    }
}

