/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KerberosOutpostConfig : Kerberos provider serializer for outposts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KerberosOutpostConfig {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "realm_name")]
    pub realm_name: String,
    #[serde(rename = "default_domain", skip_serializing_if = "Option::is_none")]
    pub default_domain: Option<String>,
    #[serde(rename = "maximum_ticket_lifetime")]
    pub maximum_ticket_lifetime: i32,
    #[serde(rename = "maximum_ticket_renew_lifetime")]
    pub maximum_ticket_renew_lifetime: i32,
    #[serde(rename = "default_ticket_lifetime", skip_serializing_if = "Option::is_none")]
    pub default_ticket_lifetime: Option<String>,
    #[serde(rename = "default_ticket_renew_lifetime", skip_serializing_if = "Option::is_none")]
    pub default_ticket_renew_lifetime: Option<String>,
    #[serde(rename = "allowed_enctypes", skip_serializing_if = "Option::is_none")]
    pub allowed_enctypes: Option<Vec<models::AllowedEnctypesEnum>>,
    #[serde(rename = "require_preauthentication", skip_serializing_if = "Option::is_none")]
    pub require_preauthentication: Option<bool>,
    /// Advertise PA-SPAKE preauthentication (RFC 9588).
    #[serde(rename = "spake_enabled", skip_serializing_if = "Option::is_none")]
    pub spake_enabled: Option<bool>,
    #[serde(rename = "udp_enabled", skip_serializing_if = "Option::is_none")]
    pub udp_enabled: Option<bool>,
    #[serde(rename = "tcp_enabled", skip_serializing_if = "Option::is_none")]
    pub tcp_enabled: Option<bool>,
    /// Enable RFC 3244 password changes through the Kerberos outpost.
    #[serde(rename = "kpasswd_enabled", skip_serializing_if = "Option::is_none")]
    pub kpasswd_enabled: Option<bool>,
    #[serde(rename = "forwardable", skip_serializing_if = "Option::is_none")]
    pub forwardable: Option<bool>,
    #[serde(rename = "renewable", skip_serializing_if = "Option::is_none")]
    pub renewable: Option<bool>,
    #[serde(rename = "proxiable", skip_serializing_if = "Option::is_none")]
    pub proxiable: Option<bool>,
    #[serde(rename = "principal_username_attribute", skip_serializing_if = "Option::is_none")]
    pub principal_username_attribute: Option<models::PrincipalUsernameAttributeEnum>,
    /// Certificate/key pair the KDC uses to sign PKINIT replies. Requires a private key.
    #[serde(rename = "pkinit_certificate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pkinit_certificate: Option<Option<uuid::Uuid>>,
    /// CA certificate used to validate PKINIT client certificates.
    #[serde(rename = "pkinit_client_ca", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pkinit_client_ca: Option<Option<uuid::Uuid>>,
    /// Require RFC 8070 freshness tokens on PKINIT requests.
    #[serde(rename = "pkinit_require_freshness", skip_serializing_if = "Option::is_none")]
    pub pkinit_require_freshness: Option<bool>,
    /// Authentication indicators asserted after successful PKINIT.
    #[serde(rename = "pkinit_indicators", skip_serializing_if = "Option::is_none")]
    pub pkinit_indicators: Option<Vec<String>>,
    /// Indicators asserted after SPAKE preauthentication.
    #[serde(rename = "spake_indicators", skip_serializing_if = "Option::is_none")]
    pub spake_indicators: Option<Vec<String>>,
    /// Indicator asserted after encrypted-challenge preauthentication.
    #[serde(rename = "encrypted_challenge_indicator", skip_serializing_if = "Option::is_none")]
    pub encrypted_challenge_indicator: Option<String>,
    /// Enable RFC 6560 OTP preauthentication backed by the user's authentik TOTP and static authenticator devices.
    #[serde(rename = "otp_enabled", skip_serializing_if = "Option::is_none")]
    pub otp_enabled: Option<bool>,
    /// Authentication indicators asserted after successful OTP preauthentication.
    #[serde(rename = "otp_indicators", skip_serializing_if = "Option::is_none")]
    pub otp_indicators: Option<Vec<String>>,
    /// Allow anonymous PKINIT requests.
    #[serde(rename = "anonymous_pkinit_enabled", skip_serializing_if = "Option::is_none")]
    pub anonymous_pkinit_enabled: Option<bool>,
    /// Enable KDC Proxy over HTTPS (MS-KKDCP).
    #[serde(rename = "kkdcp_enabled", skip_serializing_if = "Option::is_none")]
    pub kkdcp_enabled: Option<bool>,
    /// Certificate/key pair the KDC Proxy listener uses for TLS.
    #[serde(rename = "kkdcp_certificate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kkdcp_certificate: Option<Option<uuid::Uuid>>,
    /// Include an MS-PAC in issued tickets.
    #[serde(rename = "pac_enabled", skip_serializing_if = "Option::is_none")]
    pub pac_enabled: Option<bool>,
    /// Domain SID used for MS-PAC identities, for example S-1-5-21-1-2-3.
    #[serde(rename = "realm_sid", skip_serializing_if = "Option::is_none")]
    pub realm_sid: Option<String>,
    /// Push full MIT Kerberos database dumps to replica KDCs.
    #[serde(rename = "kprop_enabled", skip_serializing_if = "Option::is_none")]
    pub kprop_enabled: Option<bool>,
    #[serde(rename = "kprop_targets", skip_serializing_if = "Option::is_none")]
    pub kprop_targets: Option<Vec<String>>,
    /// Service principal used to authenticate kprop pushes.
    #[serde(rename = "kprop_client_spn", skip_serializing_if = "Option::is_none")]
    pub kprop_client_spn: Option<String>,
    /// MIT database master password used to encrypt full kprop dumps.
    #[serde(rename = "kprop_master_password", skip_serializing_if = "Option::is_none")]
    pub kprop_master_password: Option<String>,
    /// Interval in seconds between full kprop pushes.
    #[serde(rename = "kprop_interval", skip_serializing_if = "Option::is_none")]
    pub kprop_interval: Option<u32>,
    #[serde(rename = "master_key", skip_serializing_if = "Option::is_none")]
    pub master_key: Option<String>,
    #[serde(rename = "application_slug")]
    pub application_slug: String,
}

impl KerberosOutpostConfig {
    /// Kerberos provider serializer for outposts.
    pub fn new(pk: i32, name: String, realm_name: String, maximum_ticket_lifetime: i32, maximum_ticket_renew_lifetime: i32, application_slug: String) -> KerberosOutpostConfig {
        KerberosOutpostConfig {
            pk,
            name,
            realm_name,
            default_domain: None,
            maximum_ticket_lifetime,
            maximum_ticket_renew_lifetime,
            default_ticket_lifetime: None,
            default_ticket_renew_lifetime: None,
            allowed_enctypes: None,
            require_preauthentication: None,
            spake_enabled: None,
            udp_enabled: None,
            tcp_enabled: None,
            kpasswd_enabled: None,
            forwardable: None,
            renewable: None,
            proxiable: None,
            principal_username_attribute: None,
            pkinit_certificate: None,
            pkinit_client_ca: None,
            pkinit_require_freshness: None,
            pkinit_indicators: None,
            spake_indicators: None,
            encrypted_challenge_indicator: None,
            otp_enabled: None,
            otp_indicators: None,
            anonymous_pkinit_enabled: None,
            kkdcp_enabled: None,
            kkdcp_certificate: None,
            pac_enabled: None,
            realm_sid: None,
            kprop_enabled: None,
            kprop_targets: None,
            kprop_client_spn: None,
            kprop_master_password: None,
            kprop_interval: None,
            master_key: None,
            application_slug,
        }
    }
}

