/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KerberosOutpostConfig : Kerberos provider serializer for outposts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KerberosOutpostConfig {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "realm_name")]
    pub realm_name: String,
    #[serde(rename = "maximum_ticket_lifetime")]
    pub maximum_ticket_lifetime: i32,
    #[serde(rename = "maximum_ticket_renew_lifetime")]
    pub maximum_ticket_renew_lifetime: i32,
    #[serde(rename = "allowed_enctypes", skip_serializing_if = "Option::is_none")]
    pub allowed_enctypes: Option<Vec<models::AllowedEnctypesEnum>>,
    #[serde(rename = "master_key", skip_serializing_if = "Option::is_none")]
    pub master_key: Option<String>,
    #[serde(rename = "application_slug")]
    pub application_slug: String,
}

impl KerberosOutpostConfig {
    /// Kerberos provider serializer for outposts.
    pub fn new(pk: i32, name: String, realm_name: String, maximum_ticket_lifetime: i32, maximum_ticket_renew_lifetime: i32, application_slug: String) -> KerberosOutpostConfig {
        KerberosOutpostConfig {
            pk,
            name,
            realm_name,
            maximum_ticket_lifetime,
            maximum_ticket_renew_lifetime,
            allowed_enctypes: None,
            master_key: None,
            application_slug,
        }
    }
}

