/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KerberosUserKeyOutpost : User key data consumed by the KDC outpost.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KerberosUserKeyOutpost {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "kvno")]
    pub kvno: i32,
    #[serde(rename = "salt")]
    pub salt: String,
    #[serde(rename = "keys")]
    pub keys: std::collections::HashMap<String, serde_json::Value>,
}

impl KerberosUserKeyOutpost {
    /// User key data consumed by the KDC outpost.
    pub fn new(username: String, kvno: i32, salt: String, keys: std::collections::HashMap<String, serde_json::Value>) -> KerberosUserKeyOutpost {
        KerberosUserKeyOutpost {
            username,
            kvno,
            salt,
            keys,
        }
    }
}

