/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KerberosCheckAccess : Policy access data consumed by the KDC outpost.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KerberosCheckAccess {
    #[serde(rename = "access")]
    pub access: models::PolicyTestResult,
}

impl KerberosCheckAccess {
    /// Policy access data consumed by the KDC outpost.
    pub fn new(access: models::PolicyTestResult) -> KerberosCheckAccess {
        KerberosCheckAccess {
            access,
        }
    }
}

