/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KerberosServicePrincipalOutpost : Service principal data consumed by the KDC outpost.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KerberosServicePrincipalOutpost {
    #[serde(rename = "spn")]
    pub spn: String,
    #[serde(rename = "kvno")]
    pub kvno: i32,
    #[serde(rename = "keys")]
    pub keys: std::collections::HashMap<String, serde_json::Value>,
}

impl KerberosServicePrincipalOutpost {
    /// Service principal data consumed by the KDC outpost.
    pub fn new(spn: String, kvno: i32, keys: std::collections::HashMap<String, serde_json::Value>) -> KerberosServicePrincipalOutpost {
        KerberosServicePrincipalOutpost {
            spn,
            kvno,
            keys,
        }
    }
}

