/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedKerberosServicePrincipalOutpostList {
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
    #[serde(rename = "results")]
    pub results: Vec<models::KerberosServicePrincipalOutpost>,
    #[serde(rename = "autocomplete")]
    pub autocomplete: std::collections::HashMap<String, serde_json::Value>,
}

impl PaginatedKerberosServicePrincipalOutpostList {
    pub fn new(pagination: models::Pagination, results: Vec<models::KerberosServicePrincipalOutpost>, autocomplete: std::collections::HashMap<String, serde_json::Value>) -> PaginatedKerberosServicePrincipalOutpostList {
        PaginatedKerberosServicePrincipalOutpostList {
            pagination,
            results,
            autocomplete,
        }
    }
}

