/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrincipalUsernameAttributeEnum {
    #[serde(rename = "username")]
    Username,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "upn")]
    Upn,

}

impl std::fmt::Display for PrincipalUsernameAttributeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Username => write!(f, "username"),
            Self::Email => write!(f, "email"),
            Self::Upn => write!(f, "upn"),
        }
    }
}

impl Default for PrincipalUsernameAttributeEnum {
    fn default() -> PrincipalUsernameAttributeEnum {
        Self::Username
    }
}

