/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TicketFlagsEnum {
    #[serde(rename = "requires_preauth")]
    RequiresPreauth,
    #[serde(rename = "requires_hwauth")]
    RequiresHwauth,
    #[serde(rename = "disallow_postdated")]
    DisallowPostdated,
    #[serde(rename = "disallow_forwardable")]
    DisallowForwardable,
    #[serde(rename = "disallow_proxiable")]
    DisallowProxiable,
    #[serde(rename = "disallow_renewable")]
    DisallowRenewable,
    #[serde(rename = "disallow_tgt_based")]
    DisallowTgtBased,
    #[serde(rename = "disallow_server")]
    DisallowServer,
}

impl std::fmt::Display for TicketFlagsEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RequiresPreauth => write!(f, "requires_preauth"),
            Self::RequiresHwauth => write!(f, "requires_hwauth"),
            Self::DisallowPostdated => write!(f, "disallow_postdated"),
            Self::DisallowForwardable => write!(f, "disallow_forwardable"),
            Self::DisallowProxiable => write!(f, "disallow_proxiable"),
            Self::DisallowRenewable => write!(f, "disallow_renewable"),
            Self::DisallowTgtBased => write!(f, "disallow_tgt_based"),
            Self::DisallowServer => write!(f, "disallow_server"),
        }
    }
}

impl Default for TicketFlagsEnum {
    fn default() -> TicketFlagsEnum {
        Self::RequiresPreauth
    }
}
